/* ============================================================
   粵學堂 · 学习内容数据
   粤拼（Jyutping）标注，数字 1-6 为声调
   ============================================================ */

const DATA = {

/* ---------- 1. 语音系统 ---------- */
initials: [
  {sym:'b', jp:'b', ex:'巴', exjp:'baa1', note:'双唇不送气清塞音'},
  {sym:'p', jp:'p', ex:'怕', exjp:'paa3', note:'双唇送气清塞音'},
  {sym:'m', jp:'m', ex:'媽', exjp:'maa1', note:'双唇鼻音'},
  {sym:'f', jp:'f', ex:'花', exjp:'faa1', note:'唇齿清擦音'},
  {sym:'d', jp:'d', ex:'打', exjp:'daa2', note:'舌尖不送气清塞音'},
  {sym:'t', jp:'t', ex:'他', exjp:'taa1', note:'舌尖送气清塞音'},
  {sym:'n', jp:'n', ex:'那', exjp:'naa5', note:'舌尖鼻音'},
  {sym:'l', jp:'l', ex:'啦', exjp:'laa1', note:'舌尖边音'},
  {sym:'g', jp:'g', ex:'家', exjp:'gaa1', note:'舌根不送气清塞音'},
  {sym:'k', jp:'k', ex:'卡', exjp:'kaa1', note:'舌根送气清塞音'},
  {sym:'ng', jp:'ng', ex:'牙', exjp:'ngaa4', note:'舌根鼻音'},
  {sym:'h', jp:'h', ex:'蝦', exjp:'haa1', note:'喉清擦音'},
  {sym:'gw', jp:'gw', ex:'瓜', exjp:'gwaa1', note:'圆唇舌根不送气'},
  {sym:'kw', jp:'kw', ex:'誇', exjp:'kwaa1', note:'圆唇舌根送气'},
  {sym:'w', jp:'w', ex:'蛙', exjp:'waa1', note:'圆唇半元音'},
  {sym:'z', jp:'z', ex:'渣', exjp:'zaa1', note:'舌尖不送气塞擦音'},
  {sym:'c', jp:'c', ex:'叉', exjp:'caa1', note:'舌尖送气塞擦音'},
  {sym:'s', jp:'s', ex:'沙', exjp:'saa1', note:'舌尖清擦音'},
  {sym:'j', jp:'j', ex:'也', exjp:'jaa5', note:'硬颚半元音'},
],

finals: [
  {sym:'aa', ex:'花 / 爸', exjp:'faa1 / baa1', grp:'a 系'},
  {sym:'aai', ex:'街', exjp:'gaai1', grp:'a 系'},
  {sym:'aau', ex:'咬', exjp:'ngaau5', grp:'a 系'},
  {sym:'aam', ex:'衫', exjp:'saam1', grp:'a 系'},
  {sym:'aan', ex:'山', exjp:'saan1', grp:'a 系'},
  {sym:'aang', ex:'行（口語）', exjp:'haang4', grp:'a 系'},
  {sym:'aap', ex:'鴨', exjp:'aap3', grp:'a 系 · 入声'},
  {sym:'aat', ex:'八', exjp:'baat3', grp:'a 系 · 入声'},
  {sym:'aak', ex:'百', exjp:'baak3', grp:'a 系 · 入声'},
  {sym:'ai', ex:'雞', exjp:'gai1', grp:'a 系'},
  {sym:'au', ex:'牛', exjp:'ngau4', grp:'a 系'},
  {sym:'am', ex:'心', exjp:'sam1', grp:'a 系'},
  {sym:'an', ex:'新', exjp:'san1', grp:'a 系'},
  {sym:'ang', ex:'生', exjp:'sang1', grp:'a 系'},
  {sym:'ap', ex:'十', exjp:'sap6', grp:'a 系 · 入声'},
  {sym:'at', ex:'一', exjp:'jat1', grp:'a 系 · 入声'},
  {sym:'ak', ex:'北', exjp:'bak1', grp:'a 系 · 入声'},
  {sym:'e', ex:'車', exjp:'ce1', grp:'e 系'},
  {sym:'ei', ex:'你', exjp:'nei5', grp:'e 系'},
  {sym:'eu', ex:'掉（口語）', exjp:'deu6', grp:'e 系'},
  {sym:'em', ex:'舔（口語）', exjp:'lem2', grp:'e 系'},
  {sym:'eng', ex:'贏', exjp:'jeng4', grp:'e 系'},
  {sym:'ep', ex:'夾（口語）', exjp:'gep6', grp:'e 系 · 入声'},
  {sym:'ek', ex:'石', exjp:'sek6', grp:'e 系 · 入声'},
  {sym:'eoi', ex:'水', exjp:'seoi2', grp:'eo 系'},
  {sym:'eon', ex:'春', exjp:'ceon1', grp:'eo 系'},
  {sym:'eong', ex:'雙', exjp:'soeng1', grp:'eo 系'},
  {sym:'eot', ex:'出', exjp:'ceot1', grp:'eo 系 · 入声'},
  {sym:'eok', ex:'削', exjp:'soek3', grp:'eo 系 · 入声'},
  {sym:'i', ex:'詩', exjp:'si1', grp:'i 系'},
  {sym:'iu', ex:'笑', exjp:'siu3', grp:'i 系'},
  {sym:'im', ex:'點', exjp:'dim2', grp:'i 系'},
  {sym:'in', ex:'天', exjp:'tin1', grp:'i 系'},
  {sym:'ing', ex:'聽', exjp:'ting1', grp:'i 系'},
  {sym:'ip', ex:'碟', exjp:'dip6', grp:'i 系 · 入声'},
  {sym:'it', ex:'熱', exjp:'jit6', grp:'i 系 · 入声'},
  {sym:'ik', ex:'食', exjp:'sik6', grp:'i 系 · 入声'},
  {sym:'o', ex:'火', exjp:'fo2', grp:'o 系'},
  {sym:'oi', ex:'菜', exjp:'coi3', grp:'o 系'},
  {sym:'ou', ex:'好', exjp:'hou2', grp:'o 系'},
  {sym:'on', ex:'乾', exjp:'gon1', grp:'o 系'},
  {sym:'ong', ex:'糖', exjp:'tong4', grp:'o 系'},
  {sym:'ot', ex:'渴', exjp:'hot3', grp:'o 系 · 入声'},
  {sym:'ok', ex:'落', exjp:'lok6', grp:'o 系 · 入声'},
  {sym:'u', ex:'夫', exjp:'fu1', grp:'u 系'},
  {sym:'ui', ex:'杯', exjp:'bui1', grp:'u 系'},
  {sym:'un', ex:'盤', exjp:'pun4', grp:'u 系'},
  {sym:'ung', ex:'東', exjp:'dung1', grp:'u 系'},
  {sym:'ut', ex:'闊', exjp:'fut3', grp:'u 系 · 入声'},
  {sym:'uk', ex:'屋', exjp:'uk1', grp:'u 系 · 入声'},
  {sym:'yu', ex:'書', exjp:'syu1', grp:'yu 系'},
  {sym:'yun', ex:'圈', exjp:'hyun1', grp:'yu 系'},
  {sym:'yut', ex:'月', exjp:'jyut6', grp:'yu 系 · 入声'},
  {sym:'m', ex:'唔', exjp:'m4', grp:'鼻音韵（自成音节）'},
  {sym:'ng', ex:'五', exjp:'ng5', grp:'鼻音韵（自成音节）'},
],

tones: [
  {num:'1', name:'阴平', contour:'55', desc:'高平：声音平而高，像唱歌定音', ex:'詩', exjp:'si1', ex2:'衣', ex2jp:'ji1'},
  {num:'2', name:'阴上', contour:'35', desc:'高升：由中音升到高音，像疑问上扬', ex:'史', exjp:'si2', ex2:'椅', ex2jp:'ji2'},
  {num:'3', name:'阴去', contour:'33', desc:'中平：不高不低，平直输出', ex:'試', exjp:'si3', ex2:'意', ex2jp:'ji3'},
  {num:'4', name:'阳平', contour:'21', desc:'低降：从低再往下降，低沉', ex:'時', exjp:'si4', ex2:'移', ex2jp:'ji4'},
  {num:'5', name:'阳上', contour:'13', desc:'低升：从最低升起来，像问"嗯？"', ex:'市', exjp:'si5', ex2:'耳', ex2jp:'ji5'},
  {num:'6', name:'阳去', contour:'22', desc:'低平：比第3声低，平直', ex:'事', exjp:'si6', ex2:'二', ex2jp:'ji6'},
  {num:'7', name:'上入', contour:'1', desc:'入声·高：韵尾 -p/-t/-k，短促收尾', ex:'色', exjp:'sik1', ex2:'一', ex2jp:'jat1'},
  {num:'8', name:'中入', contour:'3', desc:'入声·中：短促收尾，高度同第3声', ex:'錫', exjp:'sik3', ex2:'八', ex2jp:'baat3'},
  {num:'9', name:'下入', contour:'6', desc:'入声·低：短促收尾，高度同第6声', ex:'食', exjp:'sik6', ex2:'月', ex2jp:'jyut6'},
],

/* ---------- 2. 场景词汇 ---------- */
vocabCategories: [
{
  id:'food', name:'饮食', icon:'🍜', words:[
    {han:'飲茶', jp:'jam2 caa4', mand:'喝早茶', ex:'我哋聽日去飲茶。', exjp:'ngo5 dei6 ting1 jat6 heoi3 jam2 caa4.', exmand:'我们明天去喝早茶。'},
    {han:'蝦餃', jp:'haa1 gaau2', mand:'虾饺', ex:'蝦餃好鮮。', exjp:'haa1 gaau2 hou2 sin1.', exmand:'虾饺很鲜美。'},
    {han:'燒賣', jp:'siu1 maai6', mand:'烧麦', ex:'一籠燒賣幾錢？', exjp:'jat1 lung4 siu1 maai6 gei2 cin2?', exmand:'一笼烧麦多少钱？'},
    {han:'蛋撻', jp:'daan6 taat1', mand:'蛋挞', ex:'新鮮出爐嘅蛋撻。', exjp:'san1 sin1 ceot1 lou2 ge3 daan6 taat1.', exmand:'新鲜出炉的蛋挞。'},
    {han:'雲吞麵', jp:'wan4 tan1 min6', mand:'馄饨面', ex:'我食雲吞麵，唔該。', exjp:'ngo5 sik6 wan4 tan1 min6, m4 goi1.', exmand:'我要馄饨面，谢谢。'},
    {han:'煲仔飯', jp:'bou1 zai2 faan6', mand:'煲仔饭', ex:'煲仔飯要等十五分鐘。', exjp:'bou1 zai2 faan6 jiu3 dang2 sap6 ng5 fan1 zung1.', exmand:'煲仔饭要等十五分钟。'},
    {han:'叉燒', jp:'caa1 siu1', mand:'叉烧', ex:'叉燒飯加例湯。', exjp:'caa1 siu1 faan6 gaa1 lai6 tong1.', exmand:'叉烧饭加例汤。'},
    {han:'奶茶', jp:'naai5 caa4', mand:'奶茶', ex:'奶茶飛冰，唔該。', exjp:'naai5 caa4 fei1 bing1, m4 goi1.', exmand:'奶茶不加冰，谢谢。'},
    {han:'菠蘿油', jp:'bo1 lo4 jau2', mand:'菠萝油', ex:'菠蘿油配凍檸茶一流。', exjp:'bo1 lo4 jau2 pui3 dung3 ning2 caa4 jat1 lau4.', exmand:'菠萝油配冻柠檬茶一流。'},
    {han:'腸粉', jp:'coeng2 fan2', mand:'肠粉', ex:'齋腸粉落豉油。', exjp:'zaai1 coeng2 fan2 lok6 si6 jau4.', exmand:'斋肠粉加酱油。'},
    {han:'白粥', jp:'baak6 zuk1', mand:'白粥', ex:'病咗飲白粥好啲。', exjp:'beng6 zo2 jam2 baak6 zuk1 hou2 di1.', exmand:'生病了喝白粥好一些。'},
    {han:'大排檔', jp:'daai6 paai4 dong3', mand:'大排档', ex:'大排檔啲鑊氣十足。', exjp:'daai6 paai4 dong3 di1 wok6 hei3 sap6 zuk1.', exmand:'大排档的锅气很足。'},
    {han:'白飯', jp:'baak6 faan6', mand:'米饭', ex:'要碗白飯，唔該。', exjp:'jiu3 wun2 baak6 faan6, m4 goi1.', exmand:'要一碗米饭，谢谢。'},
    {han:'湯水', jp:'tong1 seoi2', mand:'老火汤', ex:'屋企煲咗湯水。', exjp:'uk1 kei2 bou1 zo2 tong1 seoi2.', exmand:'家里煲了汤。'},
    {han:'糖水', jp:'tong4 seoi2', mand:'甜品', ex:'食完飯食碗糖水。', exjp:'sik6 jyun4 faan6 sik6 wun2 tong4 seoi2.', exmand:'吃完饭喝碗糖水。'},
    {han:'菠蘿包', jp:'bo1 lo4 baau1', mand:'菠萝包', ex:'菠蘿油要趁熱食。', exjp:'bo1 lo4 jau2 jiu3 can3 jit6 sik6.', exmand:'菠萝油要趁热吃。'},
    {han:'點心', jp:'dim2 sam1', mand:'点心', ex:'點心車推過嚟喇。', exjp:'dim2 sam1 ce1 teoi1 gwo3 lai4 laa3.', exmand:'点心车推过来了。'},
    {han:'齋啡', jp:'zaai1 fe1', mand:'黑咖啡', ex:'我飲齋啡，唔加糖。', exjp:'ngo5 jam2 zaai1 fe1, m4 gaa1 tong4.', exmand:'我喝黑咖啡，不加糖。'},
    {han:'檸茶', jp:'ning4 mung4 caa4', mand:'柠檬茶', ex:'凍檸茶少甜。', exjp:'dung3 ning4 mung4 caa4 siu2 tim4.', exmand:'冻柠茶少糖。'},  
  {han:'牛腩麵', jp:'ngau4 naam5 min6', mand:'牛腩面', ex:'呢間鋪頭嘅牛腩麵好出名。', exjp:'ni1 gaan1 pou3 tau4 ge3 ngau4 naam5 min6 hou2 ceot1 ming4.', exmand:'这家店的牛腩面很有名。'},
  {han:'車仔麵', jp:'ce1 zai2 min6', mand:'车仔面', ex:'食車仔麵可以自己揀配料。', exjp:'sik6 ce1 zai2 min6 ho2 ji5 zi6 gei2 gaam2 pui3 liu2.', exmand:'吃车仔面可以自己选配料。'},
  {han:'炒飯', jp:'caau2 faan6', mand:'炒饭', ex:'揚州炒飯好大碟。', exjp:'joeng4 zau1 caau2 faan6 hou2 daai6 dip6.', exmand:'扬州炒饭很大一份。'},
  {han:'鴛鴦', jp:'jyun1 joeng1', mand:'鸳鸯（咖啡奶茶混合）', ex:'我要一杯熱鴛鴦。', exjp:'ngo5 jiu3 jat1 bui1 jit6 jyun1 joeng1.', exmand:'我要一杯热鸳鸯。'},
  {han:'蛋治', jp:'daan6 zi6', mand:'鸡蛋三明治', ex:'早餐食咗個蛋治。', exjp:'zou2 caan1 sik6 zo2 go3 daan6 zi6.', exmand:'早餐吃了一个鸡蛋三明治。'},
  {han:'多士', jp:'do1 si2', mand:'吐司', ex:'多士要烘底。', exjp:'do1 si2 jiu3 hung1 dai2.', exmand:'吐司要烤底。'},
  {han:'餐蛋麵', jp:'caan1 daan6 min6', mand:'餐蛋面', ex:'茶餐廳最平係餐蛋麵。', exjp:'caa4 caan1 teng1 zeoi3 peng4 hai6 caan1 daan6 min6.', exmand:'茶餐厅最便宜的是餐蛋面。'},
  {han:'撈麵', jp:'lou1 min6', mand:'捞面', ex:'雲吞撈麵加腩汁。', exjp:'wan4 tan1 lou1 min6 gaa1 naam5 zap1.', exmand:'云吞捞面加腩汁。'},
  {han:'魚蛋', jp:'jyu4 daan2', mand:'鱼蛋', ex:'街邊檔嘅魚蛋好彈牙。', exjp:'gaai1 bin1 dong3 ge3 jyu4 daan2 hou2 daan6 ngaa4.', exmand:'街边摊的鱼蛋很弹牙。'},
  {han:'牛雜', jp:'ngau4 zaap6', mand:'牛杂', ex:'牛雜麵好惹味。', exjp:'ngau4 zaap6 min6 hou2 je5 mei6.', exmand:'牛杂面很够味。'},
  {han:'打邊爐', jp:'daa2 bin1 lou4', mand:'吃火锅', ex:'冬天最啱打邊爐。', exjp:'dung1 tin1 zeoi3 ngaam1 daa2 bin1 lou4.', exmand:'冬天最适合吃火锅。'}]},
{
  id:'transport', name:'交通', icon:'🚌', words:[
    {han:'巴士', jp:'baa1 si2', mand:'公交车', ex:'我搭巴士返工。', exjp:'ngo5 daap3 baa1 si2 faan1 gung1.', exmand:'我坐公交上班。'},
    {han:'地鐵', jp:'dei6 tit3', mand:'地铁', ex:'坐地鐵最快。', exjp:'co5 dei6 tit3 zeoi3 faai3.', exmand:'坐地铁最快。'},
    {han:'的士', jp:'dik1 si2', mand:'出租车', ex:'幫我截架的士。', exjp:'bong1 ngo5 zit6 gaa3 dik1 si2.', exmand:'帮我拦辆出租车。'},
    {han:'小巴', jp:'siu2 baa1', mand:'小巴', ex:'小巴冇位就唔上。', exjp:'siu2 baa1 mou5 wai2 zau6 m4 soeng5.', exmand:'小巴没座位就不上。'},
    {han:'電車', jp:'din6 ce1', mand:'叮叮车', ex:'電車慢行睇風景。', exjp:'din6 ce1 maan6 haang4 tai2 fung1 ging2.', exmand:'叮叮车慢行看风景。'},
    {han:'渡輪', jp:'dou6 leon4', mand:'渡轮', ex:'坐渡輪過海睇維港。', exjp:'co5 dou6 leon4 gwo3 hoi2 tai2 wai4 gong2.', exmand:'坐渡轮过海看维港。'},
    {han:'紅綠燈', jp:'hung4 luk6 dang1', mand:'红绿灯', ex:'紅綠燈轉咗。', exjp:'hung4 luk6 dang1 zyun3 zo2.', exmand:'红绿灯变了。'},
    {han:'上車', jp:'soeng5 ce1', mand:'上车', ex:'唔該，我哋上車先。', exjp:'m4 goi1, ngo5 dei6 soeng5 ce1 sin1.', exmand:'不好意思，我们先上车。'},
    {han:'落車', jp:'lok6 ce1', mand:'下车', ex:'我下一站落車。', exjp:'ngo5 haa6 jat1 zaam6 lok6 ce1.', exmand:'我下一站下车。'},
    {han:'轉車', jp:'zyun3 ce1', mand:'换乘', ex:'金鐘要轉車。', exjp:'gam1 zung1 jiu3 zyun3 ce1.', exmand:'金钟要换乘。'},
    {han:'八達通', jp:'baat3 daat6 tung1', mand:'八达通卡', ex:'八達通嘟一嘟就得。', exjp:'baat3 daat6 tung1 duk1 jat1 duk1 zau6 dak1.', exmand:'八达通刷一下就行。'},
    {han:'車站', jp:'ce1 zaam6', mand:'车站', ex:'我喺車站等你。', exjp:'ngo5 hai2 ce1 zaam6 dang2 nei5.', exmand:'我在车站等你。'},
    {han:'塞車', jp:'sak1 ce1', mand:'堵车', ex:'依家塞車塞到傻。', exjp:'ji1 gaa1 sak1 ce1 sak1 dou3 so4.', exmand:'现在堵车堵得厉害。'},
    {han:'搭車', jp:'daap3 ce1', mand:'乘车', ex:'我搭車返工。', exjp:'ngo5 daap3 ce1 faan1 gung1.', exmand:'我坐车上班。'},
    {han:'行路', jp:'haang4 lou6', mand:'走路', ex:'我哋行路過去啦。', exjp:'ngo5 dei6 haang4 lou6 gwo3 heoi3 laa1.', exmand:'我们走路过去吧。'},
    {han:'司機', jp:'si1 gei1', mand:'司机', ex:'司機大哥，前面轉左。', exjp:'si1 gei1 daai6 go1, cin4 min6 zyun3 zo2.', exmand:'司机大哥，前面左转。'},  
  {han:'港鐵', jp:'gong2 tit3', mand:'港铁', ex:'我日日搭港鐵返工。', exjp:'ngo5 jat6 jat6 daap3 gong2 tit3 faan1 gung1.', exmand:'我每天坐港铁上班。'},
  {han:'電單車', jp:'din6 daan1 ce1', mand:'摩托车', ex:'佢揸電單車好快。', exjp:'keoi5 zaa1 din6 daan1 ce1 hou2 faai3.', exmand:'他骑摩托车很快。'},
  {han:'單車', jp:'daan1 ce1', mand:'自行车', ex:'踩單車可以鍛鍊身體。', exjp:'caai2 daan1 ce1 ho2 ji5 dyun6 lin6 san1 tai2.', exmand:'骑自行车可以锻炼身体。'},
  {han:'船', jp:'syun4', mand:'船', ex:'搭船過海睇風景。', exjp:'daap3 syun4 gwo3 hoi2 tai2 fung1 ging2.', exmand:'坐船过海看风景。'},
  {han:'飛機', jp:'fei1 gei1', mand:'飞机', ex:'搭飛機要提早到機場。', exjp:'daap3 fei1 gei1 jiu3 tai4 zou2 dou3 gei1 coeng4.', exmand:'坐飞机要提早到机场。'},
  {han:'火車', jp:'fo2 ce1', mand:'火车', ex:'火車站好多人。', exjp:'fo2 ce1 zaam6 hou2 do1 jan4.', exmand:'火车站很多人。'},
  {han:'行人路', jp:'hang4 jan4 lou6', mand:'人行道', ex:'行馬路要行行人路。', exjp:'haang4 maa5 lou6 jiu3 haang4 hang4 jan4 lou6.', exmand:'过马路要走人行道。'},
  {han:'斑馬線', jp:'baan1 maa5 sin3', mand:'斑马线', ex:'過馬路記得行斑馬線。', exjp:'gwo3 maa5 lou6 gei3 dak1 haang4 baan1 maa5 sin3.', exmand:'过马路记得走斑马线。'},
  {han:'油站', jp:'jau4 zaam6', mand:'加油站', ex:'架車冇油，要去油站。', exjp:'gaa3 ce1 mou5 jau4, jiu3 heoi3 jau4 zaam6.', exmand:'车没油了，要去加油站。'},
  {han:'泊車', jp:'paak3 ce1', mand:'停车', ex:'呢度唔准泊車。', exjp:'ni1 dou6 m4 zeon2 paak3 ce1.', exmand:'这里不准停车。'},
  {han:'隧道', jp:'seoi6 dou6', mand:'隧道', ex:'過海隧道夜晚好塞車。', exjp:'gwo3 hoi2 seoi6 dou6 je6 maan5 hou2 sak1 ce1.', exmand:'过海隧道晚上很堵车。'},
  {han:'月台', jp:'jyut6 toi4', mand:'站台', ex:'架車仲未到月台。', exjp:'gaa3 ce1 zung6 mei6 dou3 jyut6 toi4.', exmand:'车还没到站台。'},
  {han:'車費', jp:'ce1 fai3', mand:'车费', ex:'車費越嚟越貴。', exjp:'ce1 fai3 jyut6 lai4 jyut6 gwai3.', exmand:'车费越来越贵。'},
  {han:'快線', jp:'faai3 sin3', mand:'快车道', ex:'快線俾快車行。', exjp:'faai3 sin3 bei2 faai3 ce1 haang4.', exmand:'快车道给快车走。'}]},
{
  id:'shopping', name:'购物', icon:'🛍️', words:[
    {han:'買嘢', jp:'maai5 je5', mand:'买东西', ex:'我出去買嘢。', exjp:'ngo5 ceot1 heoi3 maai5 je5.', exmand:'我出去买东西。'},
    {han:'平價', jp:'peng4 gaa3', mand:'便宜', ex:'呢度啲嘢好平價。', exjp:'ni1 dou6 di1 je5 hou2 peng4 gaa3.', exmand:'这里的东西很便宜。'},
    {han:'貴', jp:'gwai3', mand:'贵', ex:'太貴啦，平啲啦。', exjp:'taai3 gwai3 laa1, peng4 di1 laa1.', exmand:'太贵了，便宜点吧。'},
    {han:'減價', jp:'gaam2 gaa3', mand:'降价', ex:'大減價，買二送一。', exjp:'daai6 gaam2 gaa3, maai5 ji6 sung3 jat1.', exmand:'大减价，买二送一。'},
    {han:'收銀處', jp:'sau1 ngan4 cyu5', mand:'收银台', ex:'去收銀處埋單。', exjp:'heoi3 sau1 ngan4 cyu5 maai4 daan1.', exmand:'去收银台结账。'},
    {han:'袋', jp:'doi6', mand:'袋子', ex:'唔該畀個膠袋我。', exjp:'m4 goi1 bei2 go3 gaau1 doi6 ngo5.', exmand:'请给我一个塑料袋。'},
    {han:'找錢', jp:'zaau2 cin2', mand:'找零', ex:'唔使找錢喇。', exjp:'m4 sai2 zaau2 cin2 laa3.', exmand:'不用找零了。'},
    {han:'試身', jp:'si3 san1', mand:'试穿', ex:'呢件可以試身嗎？', exjp:'ni1 gin6 ho2 ji5 si3 san1 maa1?', exmand:'这件可以试穿吗？'},
    {han:'尺寸', jp:'cek3 cyun3', mand:'尺寸', ex:'有冇大一個碼？', exjp:'jau5 mou5 daai6 jat1 go3 maa5?', exmand:'有没有大一码？'},
    {han:'現金', jp:'jin6 gam1', mand:'现金', ex:'用現金定八達通？', exjp:'jung6 jin6 gam1 ding6 baat3 daat6 tung1?', exmand:'用现金还是八达通？'},
    {han:'信用卡', jp:'seon3 jung6 kaat1', mand:'信用卡', ex:'信用卡埋單，多謝。', exjp:'seon3 jung6 kaat1 maai4 daan1, do1 ze6.', exmand:'信用卡结账，谢谢。'},
    {han:'打折', jp:'daa2 zit3', mand:'打折', ex:'依家打七折。', exjp:'ji1 gaa1 daa2 cat1 zit3.', exmand:'现在打七折。'},
    {han:'價錢', jp:'gaa3 cin2', mand:'价格', ex:'呢件衫價錢貴唔貴？', exjp:'ni1 gin6 saam1 gaa3 cin2 gwai3 m4 gwai3?', exmand:'这件衣服价格贵不贵？'},
    {han:'講價', jp:'gong2 gaa3', mand:'砍价', ex:'街市可以講價。', exjp:'gaai1 si5 ho2 ji5 gong2 gaa3.', exmand:'菜市场可以砍价。'},
    {han:'平嘢', jp:'peng4 je5', mand:'便宜货', ex:'呢度好多平嘢。', exjp:'ni1 dou6 hou2 do1 peng4 je5.', exmand:'这里很多便宜货。'},
    {han:'送貨', jp:'sung3 fo3', mand:'送货', ex:'大件嘢可以送貨上門。', exjp:'daai6 gin6 je5 ho2 ji5 sung3 fo3 soeng6 mun4.', exmand:'大件商品可以送货上门。'},  
  {han:'街市', jp:'gaai1 si5', mand:'菜市场', ex:'阿媽日日去街市買餸。', exjp:'aa3 maa1 jat6 jat6 heoi3 gaai1 si5 maai5 sung3.', exmand:'妈妈每天去菜市场买菜。'},
  {han:'超市', jp:'ciu1 si5', mand:'超市', ex:'超市夜晚有特價。', exjp:'ciu1 si5 je6 maan5 jau5 dak6 gaa3.', exmand:'超市晚上有特价。'},
  {han:'商場', jp:'soeng1 coeng4', mand:'商场', ex:'呢個商場好大。', exjp:'ni1 go3 soeng1 coeng4 hou2 daai6.', exmand:'这个商场很大。'},
  {han:'便利店', jp:'bin6 lei6 dim3', mand:'便利店', ex:'便利店廿四小時營業。', exjp:'bin6 lei6 dim3 jaa6 sei3 siu2 si4 jing4 jip6.', exmand:'便利店二十四小时营业。'},
  {han:'排隊', jp:'paai4 deoi2', mand:'排队', ex:'買嘢要排隊。', exjp:'maai5 je5 jiu3 paai4 deoi2.', exmand:'买东西要排队。'},
  {han:'揀', jp:'gaam2', mand:'挑选', ex:'你自己揀一件啦。', exjp:'nei5 zi6 gei2 gaam2 jat1 gin6 laa1.', exmand:'你自己挑一件吧。'},
  {han:'發票', jp:'faat3 piu3', mand:'发票', ex:'唔該開張發票。', exjp:'m4 goi1 hoi1 zoeng1 faat3 piu3.', exmand:'请开张发票。'},
  {han:'散紙', jp:'saan3 zi2', mand:'零钱', ex:'有冇散紙？', exjp:'jau5 mou5 saan3 zi2?', exmand:'有零钱吗？'},
  {han:'銀紙', jp:' ngan4 zi2', mand:'纸币', ex:'我只有銀紙，冇散紙。', exjp:'ngo5 zi2 jau5 ngan4 zi2, mou5 saan3 zi2.', exmand:'我只有纸币，没有零钱。'},
  {han:'碌卡', jp:'luk1 kaat1', mand:'刷卡', ex:'可以碌卡俾錢。', exjp:'ho2 ji5 luk1 kaat1 bei2 cin2.', exmand:'可以刷卡付款。'},
  {han:'優惠', jp:'jau1 wai6', mand:'优惠', ex:'呢排有八折優惠。', exjp:'ni1 paai4 jau5 baat3 zit3 jau1 wai6.', exmand:'最近有八折优惠。'},
  {han:'贈品', jp:'zang6 ban2', mand:'赠品', ex:'買滿一百蚊送贈品。', exjp:'maai5 mun5 jat1 baak3 man1 sung3 zang6 ban2.', exmand:'买满一百块送赠品。'},
  {han:'退款', jp:'teoi3 faan2', mand:'退款', ex:'唔啱可以退款。', exjp:'m4 ngaam1 ho2 ji5 teoi3 faan2.', exmand:'不合适可以退款。'},
  {han:'平過', jp:'peng4 gwo3', mand:'比……便宜', ex:'街市平過超市。', exjp:'gaai1 si5 peng4 gwo3 ciu1 si5.', exmand:'菜市场比超市便宜。'}]},
{
  id:'social', name:'社交', icon:'🙋', words:[
    {han:'你好', jp:'nei5 hou2', mand:'你好', ex:'你好，我係小明。', exjp:'nei5 hou2, ngo5 hai6 siu2 ming4.', exmand:'你好，我是小明。'},
    {han:'早晨', jp:'zou2 san4', mand:'早上好', ex:'早晨，飲咗茶未？', exjp:'zou2 san4, jam2 zo2 caa4 mei6?', exmand:'早上好，喝过早茶了吗？'},
    {han:'唔該', jp:'m4 goi1', mand:'谢谢 / 劳驾', ex:'唔該晒！', exjp:'m4 goi1 saai3!', exmand:'太感谢了！'},
    {han:'多謝', jp:'do1 ze6', mand:'谢谢（受赠）', ex:'多謝你幫我。', exjp:'do1 ze6 nei5 bong1 ngo5.', exmand:'谢谢你帮我。'},
    {han:'對唔住', jp:'deoi3 m4 zyu6', mand:'对不起', ex:'對唔住，我遲到咗。', exjp:'deoi3 m4 zyu6, ngo5 ci4 dou3 zo2.', exmand:'对不起，我迟到了。'},
    {han:'再見', jp:'zoi3 gin3', mand:'再见', ex:'再見，下次見。', exjp:'zoi3 gin3, haa6 ci3 gin3.', exmand:'再见，下次见。'},
    {han:'係呀', jp:'hai6 aa3', mand:'是的', ex:'係呀，我係香港人。', exjp:'hai6 aa3, ngo5 hai6 hoeng1 gong2 jan4.', exmand:'是的，我是香港人。'},
    {han:'唔係', jp:'m4 hai6', mand:'不是', ex:'唔係，你認錯人喇。', exjp:'m4 hai6, nei5 jing6 co3 jan4 laa3.', exmand:'不是，你认错人了。'},
    {han:'傾偈', jp:'king1 gai2', mand:'聊天', ex:'得閒過嚟傾偈。', exjp:'dak1 haan4 gwo3 lai4 king1 gai2.', exmand:'有空过来聊天。'},
    {han:'得閒', jp:'dak1 haan4', mand:'有空', ex:'你得閒嗎？', exjp:'nei5 dak1 haan4 maa1?', exmand:'你有空吗？'},
    {han:'恭喜', jp:'gung1 hei2', mand:'恭喜', ex:'恭喜發財！', exjp:'gung1 hei2 faat3 coi4!', exmand:'恭喜发财！'},
    {han:'幾好', jp:'gei2 hou2', mand:'挺好', ex:'最近點呀？幾好呀。', exjp:'zeoi3 gan6 dim2 aa3? gei2 hou2 aa3.', exmand:'最近怎么样？挺好的。'},
    {han:'早抖', jp:'zou2 tau2', mand:'晚安', ex:'聽日見，早抖。', exjp:'ting1 jat6 gin3, zou2 tau2.', exmand:'明天见，晚安。'},
    {han:'努力', jp:'nou5 lik6', mand:'加油', ex:'努力啲，實得嘅！', exjp:'nou5 lik6 di1, sat6 dak1 ge3!', exmand:'再努力点，一定能行！'},
    {han:'保重', jp:'bou2 zung6', mand:'保重', ex:'你保重身體呀。', exjp:'nei5 bou2 zung6 san1 tai2 aa3.', exmand:'你保重身体啊。'},
    {han:'失陪', jp:'sat1 pui4', mand:'失陪', ex:'我有啲事，失陪先。', exjp:'ngo5 jau5 di1 si6, sat1 pui4 sin1.', exmand:'我有点事，先失陪了。'},  
  {han:'拜拜', jp:'baai1 baai3', mand:'再见（口语）', ex:'拜拜，聽日見。', exjp:'baai1 baai3, ting1 jat6 gin3.', exmand:'拜拜，明天见。'},
  {han:'有冇時間', jp:'jau5 mou5 si4 gaan3', mand:'有没有时间', ex:'你有冇時間聽日食飯？', exjp:'nei5 jau5 mou5 si4 gaan3 ting1 jat6 sik6 faan6?', exmand:'你明天有没有时间吃饭？'},
  {han:'應承', jp:'jing1 sing4', mand:'答应', ex:'佢應承咗幫我。', exjp:'keoi5 jing1 sing4 zo2 bong1 ngo5.', exmand:'他答应帮我了。'},
  {han:'拒絕', jp:'keoi5 zyut6', mand:'拒绝', ex:'佢拒絕咗個邀請。', exjp:'keoi5 keoi5 zyut6 zo2 go3 jiu1 cing2.', exmand:'他拒绝了邀请。'},
  {han:'客氣', jp:'haak3 hei3', mand:'客气', ex:'你唔使咁客氣。', exjp:'nei5 m4 sai2 gam3 haak3 hei3.', exmand:'你不用这么客气。'},
  {han:'麻煩', jp:'maa4 faan4', mand:'麻烦', ex:'唔好意思，麻煩你。', exjp:'m4 hou2 ji3 si1, maa4 faan4 nei5.', exmand:'不好意思，麻烦你。'},
  {han:'幫手', jp:'bong1 sau2', mand:'帮忙', ex:'可以幫手搬嘢嗎？', exjp:'ho2 ji5 bong1 sau2 bun1 je5 maa3?', exmand:'可以帮忙搬东西吗？'},
  {han:'掛住', jp:'gwaa3 zyu6', mand:'想念', ex:'我好掛住屋企。', exjp:'ngo5 hou2 gwaa3 zyu6 uk1 kei2.', exmand:'我很想家。'},
  {han:'遲到', jp:'ci4 dou3', mand:'迟到', ex:'唔好意思，我遲到咗。', exjp:'m4 hou2 ji3 si1, ngo5 ci4 dou3 zo2.', exmand:'不好意思，我迟到了。'},
  {han:'早走', jp:'zou2 zau2', mand:'早退/提前走', ex:'佢有事先早走。', exjp:'keoi5 jau5 si6 sin1 zou2 zau2.', exmand:'他有事先提前走。'},
  {han:'唔使客氣', jp:'m4 sai2 haak3 hei3', mand:'不客气', ex:'唔使客氣，應該嘅。', exjp:'m4 sai2 haak3 hei3, jing1 goi1 ge3.', exmand:'不客气，应该的。'},
  {han:'好久不見', jp:'hou2 gau2 bat1 gin3', mand:'好久不见', ex:'好久不見，你瘦咗。', exjp:'hou2 gau2 bat1 gin3, nei5 sau3 zo2.', exmand:'好久不见，你瘦了。'},
  {han:'冇問題', jp:'mou5 man6 tai4', mand:'没问题', ex:'冇問題，交俾我。', exjp:'mou5 man6 tai4, gaau1 bei2 ngo5.', exmand:'没问题，交给我。'},
  {han:'啱啱好', jp:'ngaam1 ngaam1 hou2', mand:'刚好', ex:'呢個價錢啱啱好。', exjp:'ni1 go3 gaa3 cin2 ngaam1 ngaam1 hou2.', exmand:'这个价钱刚好。'}]},
{
  id:'family', name:'家庭', icon:'👨‍👩‍👧', words:[
    {han:'老豆', jp:'lou5 dau6', mand:'爸爸', ex:'我老豆好中意飲茶。', exjp:'ngo5 lou5 dau6 hou2 zung1 ji3 jam2 caa4.', exmand:'我爸爸很喜欢喝早茶。'},
    {han:'阿媽', jp:'aa3 maa1', mand:'妈妈', ex:'阿媽煮飯好好食。', exjp:'aa3 maa1 zyu2 faan6 hou2 hou2 sik6.', exmand:'妈妈做饭很好吃。'},
    {han:'阿哥', jp:'aa3 go1', mand:'哥哥', ex:'我阿哥喺銀行做嘢。', exjp:'ngo5 aa3 go1 hai2 ngan4 hong4 zou6 je5.', exmand:'我哥哥在银行工作。'},
    {han:'家姐', jp:'gaa1 ze1', mand:'姐姐', ex:'家姐教我講粵語。', exjp:'gaa1 ze1 gaau3 ngo5 gong2 jyut6 jyu5.', exmand:'姐姐教我讲粤语。'},
    {han:'細佬', jp:'sai3 lou2', mand:'弟弟', ex:'細佬成日打機。', exjp:'sai3 lou2 seng4 jat6 daa2 gei1.', exmand:'弟弟整天打游戏。'},
    {han:'細妹', jp:'sai3 mui6', mand:'妹妹', ex:'細妹好錫我。', exjp:'sai3 mui6 hou2 sek3 ngo5.', exmand:'妹妹很疼我。'},
    {han:'阿爺', jp:'aa3 je4', mand:'爷爷', ex:'阿爺朝早去晨運。', exjp:'aa3 je4 ziu1 zou2 heoi3 san4 wan6.', exmand:'爷爷早上晨练。'},
    {han:'阿嫲', jp:'aa3 maa4', mand:'奶奶', ex:'阿嫲講古仔好叻。', exjp:'aa3 maa4 gong2 gu2 zai2 hou2 lek1.', exmand:'奶奶很会讲故事。'},
    {han:'老婆', jp:'lou5 po4', mand:'老婆', ex:'我老婆係老師。', exjp:'ngo5 lou5 po4 hai6 lou5 si1.', exmand:'我老婆是老师。'},
    {han:'老公', jp:'lou5 gung1', mand:'老公', ex:'我老公煮嘢好叻。', exjp:'ngo5 lou5 gung1 zyu2 je5 hou2 lek1.', exmand:'我老公很会做饭。'},
    {han:'仔', jp:'zai2', mand:'儿子', ex:'我個仔讀小學。', exjp:'ngo5 go3 zai2 duk6 siu2 hok6.', exmand:'我儿子上小学。'},
    {han:'女', jp:'neoi5', mand:'女儿', ex:'我個女好乖。', exjp:'ngo5 go3 neoi5 hou2 gwaai1.', exmand:'我女儿很乖。'},
    {han:'表姐', jp:'biu2 ze1', mand:'表姐', ex:'表姐喺廣州做嘢。', exjp:'biu2 ze1 hai2 gwong2 zau1 zou6 je5.', exmand:'表姐在广州工作。'},
    {han:'堂哥', jp:'tong4 go1', mand:'堂哥', ex:'堂哥結婚喇。', exjp:'tong4 go1 git3 fan1 laa3.', exmand:'堂哥结婚了。'},
    {han:'新抱', jp:'san1 pou5', mand:'儿媳妇', ex:'佢新抱好孝順。', exjp:'keoi5 san1 pou5 hou2 haau3 seon6.', exmand:'他儿媳妇很孝顺。'},
    {han:'女婿', jp:'neoi5 sai3', mand:'女婿', ex:'女婿請食飯。', exjp:'neoi5 sai3 ceng2 sik6 faan6.', exmand:'女婿请吃饭。'},  
  {han:'爸爸', jp:'baa1 baa1', mand:'爸爸', ex:'爸爸返咗工。', exjp:'baa1 baa1 faan1 zo2 gung1.', exmand:'爸爸去上班了。'},
  {han:'媽咪', jp:'maa1 mi4', mand:'妈妈', ex:'媽咪煮飯好好食。', exjp:'maa1 mi4 zyu2 faan6 hou2 hou2 sik6.', exmand:'妈妈做的饭很好吃。'},
  {han:'妹妹', jp:'mui6 mui6', mand:'妹妹', ex:'我妹妹好得意。', exjp:'ngo5 mui6 mui6 hou2 dak1 ji3.', exmand:'我妹妹很可爱。'},
  {han:'弟弟', jp:'dai6 dai6', mand:'弟弟', ex:'弟弟仲未起身。', exjp:'dai6 dai6 zung6 mei6 hei2 san1.', exmand:'弟弟还没起床。'},
  {han:'公公', jp:'gung1 gung1', mand:'外公', ex:'公公成日去公園。', exjp:'gung1 gung1 seng4 jat6 heoi3 gung1 jyun2.', exmand:'外公经常去公园。'},
  {han:'婆婆', jp:'po4 po2', mand:'外婆', ex:'婆婆好錫我。', exjp:'po4 po2 hou2 sek3 ngo5.', exmand:'外婆很疼我。'},
  {han:'舅父', jp:'kau5 fu6', mand:'舅舅', ex:'舅父帶我哋去玩。', exjp:'kau5 fu6 daai3 ngo5 dei6 heoi3 waan2.', exmand:'舅舅带我们去玩。'},
  {han:'姑媽', jp:'gu1 maa1', mand:'姑妈', ex:'姑媽喺外國住。', exjp:'gu1 maa1 hai2 ngoi6 gwok3 zyu6.', exmand:'姑妈在国外住。'},
  {han:'姨媽', jp:'ji4 maa1', mand:'姨妈', ex:'姨媽買咗啲生果嚟。', exjp:'ji4 maa1 maai5 zo2 di1 saang1 gwo2 lai4.', exmand:'姨妈买了些水果来。'},
  {han:'表妹', jp:'biu2 mui6', mand:'表妹', ex:'表妹考試考得好好。', exjp:'biu2 mui6 haau2 si3 haau2 dak1 hou2 hou2.', exmand:'表妹考得很好。'},
  {han:'堂弟', jp:'tong4 dai6', mand:'堂弟', ex:'堂弟同我一樣大。', exjp:'tong4 dai6 tung4 ngo5 jat1 joeng6 daai6.', exmand:'堂弟和我一样大。'},
  {han:'伯父', jp:'baak3 fu6', mand:'伯父', ex:'伯父好鍾意食魚。', exjp:'baak3 fu6 hou2 zung1 ji3 sik6 jyu4.', exmand:'伯父很喜欢吃鱼。'},
  {han:'叔父', jp:'suk1 fu6', mand:'叔叔', ex:'叔父喺茶樓等我。', exjp:'suk1 fu6 hai2 caa4 lau4 dang2 ngo5.', exmand:'叔叔在茶楼等我。'},
  {han:'孫女', jp:'syun1 neoi5', mand:'孙女', ex:'公公好錫個孫女。', exjp:'gung1 gung1 hou2 sek3 go3 syun1 neoi5.', exmand:'外公很疼孙女。'}]},
{
  id:'weather', name:'天气', icon:'🌧️', words:[
    {han:'天氣', jp:'tin1 hei3', mand:'天气', ex:'今日天氣好好。', exjp:'gam1 jat6 tin1 hei3 hou2 hou2.', exmand:'今天天气很好。'},
    {han:'落雨', jp:'lok6 jyu5', mand:'下雨', ex:'落雨記得帶遮。', exjp:'lok6 jyu5 gei3 dak1 daai3 ze1.', exmand:'下雨记得带伞。'},
    {han:'打風', jp:'daa2 fung1', mand:'台风来袭', ex:'聽日打風，唔使返工。', exjp:'ting1 jat6 daa2 fung1, m4 sai2 faan1 gung1.', exmand:'明天台风，不用上班。'},
    {han:'熱', jp:'jit6', mand:'热', ex:'今日熱到飛起。', exjp:'gam1 jat6 jit6 dou3 fei1 hei2.', exmand:'今天热得不行。'},
    {han:'凍', jp:'dung3', mand:'冷', ex:'好凍，着多件衫。', exjp:'hou2 dung3, zoek3 do1 gin6 saam1.', exmand:'很冷，多穿件衣服。'},
    {han:'潮濕', jp:'ciu4 sap1', mand:'潮湿', ex:'春天好潮濕。', exjp:'ceon1 tin1 hou2 ciu4 sap1.', exmand:'春天很潮湿。'},
    {han:'晴朗', jp:'cing4 long5', mand:'晴朗', ex:'天朗氣清，去行山。', exjp:'tin1 long5 hei3 cing1, heoi3 haang4 saan1.', exmand:'天朗气清，去爬山。'},
    {han:'陰天', jp:'jam1 tin1', mand:'阴天', ex:'陰天冇太陽，好舒服。', exjp:'jam1 tin1 mou5 taai3 joeng4, hou2 syu1 fuk6.', exmand:'阴天没太阳，很舒服。'},
    {han:'打雷', jp:'daa2 leoi4', mand:'打雷', ex:'打雷落大雨。', exjp:'daa2 leoi4 lok6 daai6 jyu5.', exmand:'打雷下大雨。'},
    {han:'彩虹', jp:'coi2 hung4', mand:'彩虹', ex:'雨後有彩虹。', exjp:'jyu5 hau6 jau5 coi2 hung4.', exmand:'雨后出彩虹。'},
    {han:'天氣預報', jp:'tin1 hei3 bou3 gou3', mand:'天气预报', ex:'天氣預報話聽日落雨。', exjp:'tin1 hei3 bou3 gou3 waa6 ting1 jat6 lok6 jyu5.', exmand:'天气预报说明天下雨。'},
    {han:'颱風', jp:'toi4 fung1', mand:'台风', ex:'颱風到，記得關窗。', exjp:'toi4 fung1 dou3, gei3 dak1 gwaan1 coeng1.', exmand:'台风来了，记得关窗。'},
    {han:'雷暴', jp:'leoi4 bou6', mand:'雷暴', ex:'今晚有雷暴。', exjp:'gam1 maan5 jau5 leoi4 bou6.', exmand:'今晚有雷暴。'},
    {han:'涼爽', jp:'loeng4 song2', mand:'凉爽', ex:'秋天涼爽好多。', exjp:'cau1 tin1 loeng4 song2 hou2 do1.', exmand:'秋天凉爽很多。'},  
  {han:'落雪', jp:'lok6 syut3', mand:'下雪', ex:'北方先會落雪。', exjp:'bak1 fong1 sin1 wui5 lok6 syut3.', exmand:'北方才会下雪。'},
  {han:'風', jp:'fung1', mand:'风', ex:'今日好大風。', exjp:'gam1 jat6 hou2 daai6 fung1.', exmand:'今天风很大。'},
  {han:'雨', jp:'jyu5', mand:'雨', ex:'記得帶遮，聽日會落雨。', exjp:'gei3 dak1 daai3 ze1, ting1 jat6 wui5 lok6 jyu5.', exmand:'记得带伞，明天会下雨。'},
  {han:'陽光', jp:'joeng4 gwong1', mand:'阳光', ex:'今日陽光普照。', exjp:'gam1 jat6 joeng4 gwong1 pou2 ziu3.', exmand:'今天阳光普照。'},
  {han:'炎熱', jp:'jim4 jit6', mand:'炎热', ex:'夏天好炎熱。', exjp:'haa6 tin1 hou2 jim4 jit6.', exmand:'夏天很炎热。'},
  {han:'寒冷', jp:'hon4 laang5', mand:'寒冷', ex:'冬天天氣寒冷。', exjp:'dung1 tin1 tin1 hei3 hon4 laang5.', exmand:'冬天天气寒冷。'},
  {han:'涼', jp:'loeng4', mand:'凉快', ex:'秋天好涼。', exjp:'cau1 tin1 hou2 loeng4.', exmand:'秋天很凉快。'},
  {han:'和暖', jp:'wo4 nyun5', mand:'暖和', ex:'今日天氣和暖。', exjp:'gam1 jat6 tin1 hei3 wo4 nyun5.', exmand:'今天天气暖和。'},
  {han:'悶熱', jp:'mun6 jit6', mand:'闷热', ex:'落雨前好悶熱。', exjp:'lok6 jyu5 cin4 hou2 mun6 jit6.', exmand:'下雨前很闷热。'},
  {han:'乾燥', jp:'gon1 cou3', mand:'干燥', ex:'秋冬天氣乾燥。', exjp:'cau1 dung1 tin1 hei3 gon1 cou3.', exmand:'秋冬天气干燥。'},
  {han:'濕度', jp:'sap1 dou6', mand:'湿度', ex:'今日濕度好高。', exjp:'gam1 jat6 sap1 dou6 hou2 gou1.', exmand:'今天湿度很高。'},
  {han:'溫度', jp:'wan1 dou6', mand:'温度', ex:'今日溫度有幾多？', exjp:'gam1 jat6 wan1 dou6 jau5 gei2 do1?', exmand:'今天温度多少？'},
  {han:'天文台', jp:'tin1 man4 toi4', mand:'天文台', ex:'天文台掛咗八號波。', exjp:'tin1 man4 toi4 gwaa3 zo2 baat3 hou6 bo1.', exmand:'天文台挂起八号风球。'},
  {han:'黑雨', jp:'hak1 jyu5', mand:'黑色暴雨警告', ex:'黑雨警告一出就要停課。', exjp:'hak1 jyu5 ging2 gou3 jat1 ceot1 zau6 jiu3 ting4 fo3.', exmand:'黑色暴雨警告一出就要停课。'},
  {han:'暴雨', jp:'bou6 jyu5', mand:'暴雨', ex:'昨日落咗一場暴雨。', exjp:'zok3 jat6 lok6 zo2 jat1 coeng4 bou6 jyu5.', exmand:'昨天下了一场暴雨。'},
  {han:'閃電', jp:'sim2 din6', mand:'闪电', ex:'閃電之後就打雷。', exjp:'sim2 din6 zi1 hau6 zau6 daa2 leoi4.', exmand:'闪电之后就打雷。'}]},
{
  id:'time', name:'时间', icon:'🕐', words:[
    {han:'而家', jp:'ji4 gaa1', mand:'现在', ex:'而家幾點？', exjp:'ji4 gaa1 gei2 dim2?', exmand:'现在几点？'},
    {han:'今日', jp:'gam1 jat6', mand:'今天', ex:'今日係星期幾？', exjp:'gam1 jat6 hai6 sing1 kei4 gei2?', exmand:'今天星期几？'},
    {han:'聽日', jp:'ting1 jat6', mand:'明天', ex:'聽日見。', exjp:'ting1 jat6 gin3.', exmand:'明天见。'},
    {han:'尋日', jp:'cam4 jat6', mand:'昨天', ex:'尋日去咗邊？', exjp:'cam4 jat6 heoi3 zo2 bin1?', exmand:'昨天去哪儿了？'},
    {han:'朝早', jp:'ziu1 zou2', mand:'早上', ex:'朝早做運動。', exjp:'ziu1 zou2 zou6 wan6 dung6.', exmand:'早上做运动。'},
    {han:'晏晝', jp:'aan3 zau3', mand:'中午', ex:'晏晝食咩呀？', exjp:'aan3 zau3 sik6 me1 aa3?', exmand:'中午吃什么？'},
    {han:'下晝', jp:'haa6 zau3', mand:'下午', ex:'下晝三點開會。', exjp:'haa6 zau3 saam1 dim2 hoi1 wui2.', exmand:'下午三点开会。'},
    {han:'夜晚', jp:'je6 maan5', mand:'晚上', ex:'夜晚出去食飯。', exjp:'je6 maan5 ceot1 heoi3 sik6 faan6.', exmand:'晚上出去吃饭。'},
    {han:'幾點', jp:'gei2 dim2', mand:'几点', ex:'你幾點返到屋企？', exjp:'nei5 gei2 dim2 faan1 dou3 uk1 kei2?', exmand:'你几点回到家？'},
    {han:'一分鐘', jp:'jat1 fan1 zung1', mand:'一分钟', ex:'等我一分鐘。', exjp:'dang2 ngo5 jat1 fan1 zung1.', exmand:'等我一下。'},
    {han:'禮拜', jp:'lai5 baai3', mand:'星期', ex:'禮拜六去街。', exjp:'lai5 baai3 luk6 heoi3 gaai1.', exmand:'星期六逛街。'},
    {han:'依家', jp:'ji1 gaa1', mand:'现在（口语）', ex:'依家冇時間。', exjp:'ji1 gaa1 mou5 si4 gaan3.', exmand:'现在没时间。'},
    {han:'前日', jp:'cin4 jat6', mand:'前天', ex:'前日我去咗深圳。', exjp:'cin4 jat6 ngo5 heoi3 zo2 sam1 zan3.', exmand:'前天我去了深圳。'},
    {han:'後日', jp:'hau6 jat6', mand:'后天', ex:'後日先得閒。', exjp:'hau6 jat6 sin1 dak1 haan4.', exmand:'后天才有空。'},
    {han:'星期日', jp:'sing1 kei4 jat6', mand:'星期天', ex:'星期日放假。', exjp:'sing1 kei4 jat6 fong3 gaa3.', exmand:'星期天放假。'},
    {han:'半夜', jp:'bun3 je6', mand:'半夜', ex:'半夜都唔瞓。', exjp:'bun3 je6 dou1 m4 fan3.', exmand:'半夜还不睡。'}
  ,
  {han:'秒', jp:'miu5', mand:'秒', ex:'等我一秒。', exjp:'dang2 ngo5 jat1 miu5.', exmand:'等我一下。'},
  {han:'鐘頭', jp:'zung1 tau4', mand:'小时', ex:'我瞓咗八個鐘頭。', exjp:'ngo5 fan3 zo2 baat3 go3 zung1 tau4.', exmand:'我睡了八个小时。'},
  {han:'半個鐘', jp:'bun3 go3 zung1', mand:'半小时', ex:'半個鐘後見。', exjp:'bun3 go3 zung1 hau6 gin3.', exmand:'半小时后见。'},
  {han:'一個鐘', jp:'jat1 go3 zung1', mand:'一小时', ex:'一個鐘就到。', exjp:'jat1 go3 zung1 zau6 dou3.', exmand:'一个小时就到。'},
  {han:'凌晨', jp:'ling4 san4', mand:'凌晨', ex:'凌晨先返到屋企。', exjp:'ling4 san4 sin1 faan1 dou3 uk1 kei2.', exmand:'凌晨才回到家。'},
  {han:'中午', jp:'zung1 ng5', mand:'中午', ex:'中午約咗人食飯。', exjp:'zung1 ng5 joek3 zo2 jan4 sik6 faan6.', exmand:'中午约了人吃饭。'},
  {han:'黃昏', jp:'wong4 fan1', mand:'黄昏', ex:'黃昏嘅天好靚。', exjp:'wong4 fan1 ge3 tin1 hou2 leng3.', exmand:'黄昏的天空很美。'},
  {han:'通宵', jp:'tung1 siu1', mand:'通宵', ex:'佢溫書溫到通宵。', exjp:'keoi5 wan1 syu1 wan1 dou3 tung1 siu1.', exmand:'他复习到通宵。'},
  {han:'成日', jp:'seng4 jat6', mand:'整天/经常', ex:'佢成日遲到。', exjp:'keoi5 seng4 jat6 ci4 dou3.', exmand:'他经常迟到。'},
  {han:'平時', jp:'ping4 si4', mand:'平时', ex:'我平時七點起身。', exjp:'ngo5 ping4 si4 cat1 dim2 hei2 san1.', exmand:'我平时七点起床。'},
  {han:'有時', jp:'jau5 si4', mand:'有时', ex:'我有時會去跑步。', exjp:'ngo5 jau5 si4 wui5 heoi3 paau2 bou6.', exmand:'我有时会去跑步。'},
  {han:'將來', jp:'zoeng1 loi4', mand:'将来', ex:'將來想做醫生。', exjp:'zoeng1 loi4 soeng2 zou6 ji1 sang1.', exmand:'将来想当医生。'},
  {han:'過去', jp:'gwo3 heoi3', mand:'过去', ex:'過去嘅事唔好再諗。', exjp:'gwo3 heoi3 ge3 si6 m4 hou2 zoi3 nam2.', exmand:'过去的事不要再想。'},
  {han:'幾耐', jp:'gei2 noi6', mand:'多久', ex:'你學咗粵語幾耐？', exjp:'nei5 hok6 zo2 jyut6 jyu5 gei2 noi6?', exmand:'你学粤语多久了？'}]},
{
  id:'numbers', name:'数字', icon:'🔢', words:[
    {han:'一', jp:'jat1', mand:'一', ex:'我飲一杯奶茶。', exjp:'ngo5 jam2 jat1 bui1 naai5 caa4.', exmand:'我喝一杯奶茶。'},
    {han:'二', jp:'ji6', mand:'二', ex:'兩個人食飯。（量詞前多説"兩"）', exjp:'loeng5 go3 jan4 sik6 faan6.', exmand:'两个人吃饭。'},
    {han:'三', jp:'saam1', mand:'三', ex:'三杯咖啡。', exjp:'saam1 bui1 gaa3 fe1.', exmand:'三杯咖啡。'},
    {han:'四', jp:'sei3', mand:'四', ex:'四張飛。（四諧"死"，港人避諱）', exjp:'sei3 zoeng1 fei1.', exmand:'四张票。'},
    {han:'五', jp:'ng5', mand:'五', ex:'五蚊一個。', exjp:'ng5 man1 jat1 go3.', exmand:'五块钱一个。'},
    {han:'六', jp:'luk6', mand:'六', ex:'六六大順。', exjp:'luk6 luk6 daai6 seon6.', exmand:'六六大顺。'},
    {han:'七', jp:'cat1', mand:'七', ex:'七點鐘起身。', exjp:'cat1 dim2 zung1 hei2 san1.', exmand:'七点起床。'},
    {han:'八', jp:'baat3', mand:'八', ex:'八蚊一支水。（八諧"發"）', exjp:'baat3 man1 jat1 zi1 seoi2.', exmand:'八块钱一瓶水。'},
    {han:'九', jp:'gau2', mand:'九', ex:'九點開會。', exjp:'gau2 dim2 hoi1 wui2.', exmand:'九点开会。'},
    {han:'十', jp:'sap6', mand:'十', ex:'十蚊找返兩蚊。', exjp:'sap6 man1 zaau2 faan1 loeng5 man1.', exmand:'十块钱找两块。'},
    {han:'百', jp:'baak3', mand:'百', ex:'呢件衫要幾百蚊。', exjp:'ni1 gin6 saam1 jiu3 gei2 baak3 man1.', exmand:'这件衣服要几百块。'},
    {han:'萬', jp:'maan6', mand:'万', ex:'香港有七百幾萬人。', exjp:'hoeng1 gong2 jau5 cat1 baak3 gei2 maan6 jan4.', exmand:'香港有七百多万人。'},
    {han:'十一', jp:'sap6 jat1', mand:'十一', ex:'我住十一樓。', exjp:'ngo5 zyu6 sap6 jat1 lau2.', exmand:'我住十一楼。'},
    {han:'二十', jp:'ji6 sap6', mand:'二十', ex:'二十蚊可以買。', exjp:'ji6 sap6 man1 ho2 ji5 maai5.', exmand:'二十块可以买。'},
    {han:'三十', jp:'saa1 sap6', mand:'三十', ex:'佢三十歲。', exjp:'keoi5 saa1 sap6 seoi3.', exmand:'他三十岁。'},
    {han:'一百', jp:'jat1 baak3', mand:'一百', ex:'一百蚊有找。', exjp:'jat1 baak3 man1 jau5 zaa2.', exmand:'一百块还有找零。'},  
  {han:'零', jp:'ling4', mand:'零', ex:'電話號碼入面有個零。', exjp:'din6 waa2 hou6 maa5 jap6 min6 jau5 go3 ling4.', exmand:'电话号码里有个零。'},
  {han:'千', jp:'cin1', mand:'千', ex:'呢部電話要幾千蚊。', exjp:'ni1 bou6 din6 waa2 jiu3 gei2 cin1 man1.', exmand:'这部手机要几千块。'},
  {han:'億', jp:'jik1', mand:'亿', ex:'香港人口有幾百萬。', exjp:'hoeng1 gong2 jan4 hau2 jau5 gei2 baak3 maan6.', exmand:'香港人口有几百万。'},
  {han:'兩', jp:'loeng5', mand:'两', ex:'兩個人一齊去。', exjp:'loeng5 go3 jan4 jat1 cai4 heoi3.', exmand:'两个人一起去。'},
  {han:'二十一', jp:'ji6 sap6 jat1', mand:'二十一', ex:'我今年二十一歲。', exjp:'ngo5 gam1 nin4 ji6 sap6 jat1 seoi3.', exmand:'我今年二十一岁。'},
  {han:'三十二', jp:'saam1 sap6 ji6', mand:'三十二', ex:'巴士三十二號去邊？', exjp:'baa1 si2 saam1 sap6 ji6 hou6 heoi3 bin1?', exmand:'三十二路公交车去哪？'},
  {han:'九十九', jp:'gau2 sap6 gau2', mand:'九十九', ex:'九十九蚊，找返一蚊。', exjp:'gau2 sap6 gau2 man1, zaau2 faan1 jat1 man1.', exmand:'九十九块，找一块。'},
  {han:'一百零一', jp:'jat1 baak3 ling4 jat1', mand:'一百零一', ex:'一百零一分，好犀利！', exjp:'jat1 baak3 ling4 jat1 fan1, hou2 sai1 lei6!', exmand:'一百零一分，好厉害！'},
  {han:'一千', jp:'jat1 cin1', mand:'一千', ex:'呢度有一千人。', exjp:'ni1 dou6 jau5 jat1 cin1 jan4.', exmand:'这里有一千人。'},
  {han:'半', jp:'bun3', mand:'一半', ex:'分一半俾你。', exjp:'fan1 jat1 bun3 bei2 nei5.', exmand:'分一半给你。'},
  {han:'幾多', jp:'gei2 do1', mand:'多少', ex:'呢個幾多錢？', exjp:'ni1 go3 gei2 do1 cin2?', exmand:'这个多少钱？'},
  {han:'幾百', jp:'gei2 baak3', mand:'几百', ex:'入場要幾百蚊。', exjp:'jap6 coeng4 jiu3 gei2 baak3 man1.', exmand:'入场要几百块。'},
  {han:'第一', jp:'dai6 jat1', mand:'第一', ex:'佢考到第一。', exjp:'keoi5 haau2 dou3 dai6 jat1.', exmand:'他考了第一。'},
  {han:'號碼', jp:'hou6 maa5', mand:'号码', ex:'記低我個電話號碼。', exjp:'gei3 dai1 ngo5 go3 din6 waa2 hou6 maa5.', exmand:'记下我的电话号码。'}]},

{
  id:'body', name:'身体部位', icon:'🦵', words:[
    {han:'頭', jp:'tau4', mand:'头', ex:'頭有啲痛。', exjp:'tau4 jau5 di1 tung3.', exmand:'头有点痛。'},
    {han:'眼', jp:'ngaan5', mand:'眼睛', ex:'眼瞓就瞓啦。', exjp:'ngaan5 fan3 zau6 fan3 laa1.', exmand:'困了就睡吧。'},
    {han:'耳', jp:'ji5', mand:'耳朵', ex:'耳仔好靈。', exjp:'ji5 zai2 hou2 ling4.', exmand:'耳朵很灵。'},
    {han:'鼻', jp:'bei6', mand:'鼻子', ex:'鼻塞好辛苦。', exjp:'bei6 sak1 hou2 san1 fu2.', exmand:'鼻塞很难受。'},
    {han:'口', jp:'hau2', mand:'嘴巴', ex:'開口講粵語啦。', exjp:'hoi1 hau2 gong2 jyut6 jyu5 laa1.', exmand:'开口说粤语吧。'},
    {han:'牙', jp:'ngaa4', mand:'牙齿', ex:'刷咗牙未呀？', exjp:'caat3 zo2 ngaa4 mei6 aa3?', exmand:'刷牙了没？'},
    {han:'手', jp:'sau2', mand:'手', ex:'手袋唔記得帶。', exjp:'sau2 doi6 m4 gei3 dak1 daai3.', exmand:'手提包忘了带。'},
    {han:'腳', jp:'goek3', mand:'脚', ex:'運動完腳好攰。', exjp:'wan6 dung6 jyun4 goek3 hou2 gui6.', exmand:'运动完腿很累。'},
    {han:'心', jp:'sam1', mand:'心', ex:'個心跳得好快。', exjp:'go3 sam1 tiu3 dak1 hou2 faai3.', exmand:'心跳得很快。'},
    {han:'肚', jp:'tou5', mand:'肚子', ex:'肚餓啦，去食飯。', exjp:'tou5 ngo6 laa1, heoi3 sik6 faan6.', exmand:'肚子饿了，去吃饭。'},
    {han:'頭髮', jp:'tau4 faat3', mand:'头发', ex:'頭髮好長，要剪喇。', exjp:'tau4 faat3 hou2 coeng4, jiu3 zin2 laa3.', exmand:'头发很长，该剪了。'},
    {han:'膊頭', jp:'bok3 tau4', mand:'肩膀', ex:'膊頭有啲緊。', exjp:'bok3 tau4 jau5 di1 gan2.', exmand:'肩膀有点紧。'},
  
  {han:'面', jp:'min6', mand:'脸', ex:'佢塊面好紅。', exjp:'keoi5 faai3 min6 hou2 hung4.', exmand:'他的脸很红。'},
  {han:'額頭', jp:'ngaak6 tau4', mand:'额头', ex:'發燒要摸下額頭。', exjp:'faat3 siu1 jiu3 mo2 haa5 ngaak6 tau4.', exmand:'发烧要摸一下额头。'},
  {han:'眉毛', jp:'mei4 mou4', mand:'眉毛', ex:'佢嘅眉毛好濃。', exjp:'keoi5 ge3 mei4 mou4 hou2 nung4.', exmand:'他的眉毛很浓。'},
  {han:'眼皮', jp:'ngaan5 pei4', mand:'眼皮', ex:'眼皮跳代表有嘢發生。', exjp:'ngaan5 pei4 tiu3 doi6 biu2 jau5 je5 faat3 sang1.', exmand:'眼皮跳代表有事情发生。'},
  {han:'耳仔', jp:'ji5 zai2', mand:'耳朵（口语）', ex:'大聲啲，我耳仔唔好。', exjp:'daai6 seng1 di1, ngo5 ji5 zai2 m4 hou2.', exmand:'大声点，我耳朵不好。'},
  {han:'嘴', jp:'zeoi2', mand:'嘴', ex:'唔好亂講嘢，收埋你把嘴。', exjp:'m4 hou2 lyun6 gong2 je5, sau1 maai4 nei5 baa2 zeoi2.', exmand:'别乱说话，闭上你的嘴。'},
  {han:'脷', jp:'lei6', mand:'舌头', ex:'辣到條脷都痺。', exjp:'laat6 dou3 tiu4 lei6 dou1 bei3.', exmand:'辣得舌头都麻了。'},
  {han:'頸', jp:'geng2', mand:'脖子', ex:'做運動小心整親條頸。', exjp:'zou6 wan6 dung6 siu2 sam1 zing2 can1 tiu4 geng2.', exmand:'做运动小心弄伤脖子。'},
  {han:'喉嚨', jp:'hau4 lung4', mand:'喉咙', ex:'我喉嚨痛。', exjp:'ngo5 hau4 lung4 tung3.', exmand:'我喉咙痛。'},
  {han:'手指', jp:'sau2 zi2', mand:'手指', ex:'切嘢小心手指。', exjp:'cit3 je5 siu2 sam1 sau2 zi2.', exmand:'切东西小心手指。'},
  {han:'手指甲', jp:'sau2 zi2 gaap3', mand:'指甲', ex:'手指甲好長，剪下佢。', exjp:'sau2 zi2 gaap3 hou2 coeng4, zin2 haa5 keoi5.', exmand:'指甲很长，剪一下。'},
  {han:'膝頭哥', jp:'sat1 tau4 go1', mand:'膝盖', ex:'我膝頭哥整親咗。', exjp:'ngo5 sat1 tau4 go1 zing2 can1 zo2.', exmand:'我的膝盖受伤了。'},
  {han:'腳趾', jp:'goek3 zi2', mand:'脚趾', ex:'十隻腳趾都有甲。', exjp:'sap6 zek3 goek3 zi2 dou1 jau5 gaap3.', exmand:'十个脚趾都有指甲。'},
  {han:'背脊', jp:'bui3 zek3', mand:'背', ex:'坐姿唔好會腰酸背痛。', exjp:'co5 zi1 m4 hou2 wui5 jiu1 syun1 bui3 tung3.', exmand:'坐姿不好会腰酸背痛。'},
  {han:'腰', jp:'jiu1', mand:'腰', ex:'搬嘢小心扭親條腰。', exjp:'bun1 je5 siu2 sam1 nau2 can1 tiu4 jiu1.', exmand:'搬东西小心扭到腰。'},
  {han:'屁股', jp:'pei3 gu2', mand:'屁股', ex:'跌親個屁股好痛。', exjp:'dit3 can1 go3 pei3 gu2 hou2 tung3.', exmand:'摔到屁股很痛。'},
  {han:'肚臍', jp:'tou5 ci4', mand:'肚脐', ex:'肚臍好怕凍。', exjp:'tou5 ci4 hou2 paa3 dung3.', exmand:'肚脐很怕冷。'},
  {han:'腳踭', jp:'goek3 zaang1', mand:'脚后跟', ex:'新鞋刮腳踭。', exjp:'san1 haai4 gwaat3 goek3 zaang1.', exmand:'新鞋磨脚后跟。'}]},
{
  id:'school', name:'校园学习', icon:'🎒', words:[
    {han:'學校', jp:'hok6 haau6', mand:'学校', ex:'學校幾點放學？', exjp:'hok6 haau6 gei2 dim2 fong3 hok6?', exmand:'学校几点放学？'},
    {han:'老師', jp:'lou5 si1', mand:'老师', ex:'老師好嚴格。', exjp:'lou5 si1 hou2 jim4 gaak3.', exmand:'老师很严格。'},
    {han:'學生', jp:'hok6 saang1', mand:'学生', ex:'學生證帶咗未？', exjp:'hok6 saang1 zing3 daai3 zo2 mei6?', exmand:'学生证带了没？'},
    {han:'同學', jp:'tung4 hok6', mand:'同学', ex:'我同佢係同學。', exjp:'ngo5 tung4 keoi5 hai6 tung4 hok6.', exmand:'我和他是同学。'},
    {han:'課本', jp:'fo3 bun2', mand:'课本', ex:'課本喺書包度。', exjp:'fo3 bun2 hai2 syu1 baau1 dou6.', exmand:'课本在书包里。'},
    {han:'書包', jp:'syu1 baau1', mand:'书包', ex:'書包好重。', exjp:'syu1 baau1 hou2 cung5.', exmand:'书包很重。'},
    {han:'鉛筆', jp:'jyun4 bat1', mand:'铅笔', ex:'借支鉛筆用下。', exjp:'ze3 zi1 jyun4 bat1 jung6 haa5.', exmand:'借支铅笔用一下。'},
    {han:'寫字', jp:'se2 zi6', mand:'写字', ex:'學寫字要慢慢嚟。', exjp:'hok6 se2 zi6 jiu3 maan6 maan6 lai4.', exmand:'学写字要慢慢来。'},
    {han:'讀書', jp:'duk6 syu1', mand:'读书', ex:'細路仔要讀書。', exjp:'sai3 lou6 zai2 jiu3 duk6 syu1.', exmand:'小孩子要读书。'},
    {han:'考試', jp:'haau2 si3', mand:'考试', ex:'考試之前要温書。', exjp:'haau2 si3 zi1 cin4 jiu3 wan1 syu1.', exmand:'考试之前要复习。'},
    {han:'作業', jp:'zok3 jip6', mand:'作业', ex:'今日作業多唔多？', exjp:'gam1 jat6 zok3 jip6 do1 m4 do1?', exmand:'今天作业多不多？'},
    {han:'放假', jp:'fong3 gaa3', mand:'放假', ex:'放暑假去旅行。', exjp:'fong3 syu3 gaa3 heoi3 leoi5 hang4.', exmand:'放暑假去旅行。'},
  
  {han:'課室', jp:'fo3 sat1', mand:'教室', ex:'課室裏面好安靜。', exjp:'fo3 sat1 leoi5 min6 hou2 on1 zing6.', exmand:'教室里很安静。'},
  {han:'操場', jp:'cou1 coeng4', mand:'操场', ex:'落課去操場玩。', exjp:'lok6 fo3 heoi3 cou1 coeng4 waan2.', exmand:'下课去操场玩。'},
  {han:'圖書館', jp:'tou4 syu1 gun2', mand:'图书馆', ex:'圖書館唔准講嘢。', exjp:'tou4 syu1 gun2 m4 zeon2 gong2 je5.', exmand:'图书馆不准说话。'},
  {han:'實驗室', jp:'sat6 jim6 sat1', mand:'实验室', ex:'實驗室做實驗要小心。', exjp:'sat6 jim6 sat1 zou6 sat6 jim6 jiu3 siu2 sam1.', exmand:'在实验室做实验要小心。'},
  {han:'校長', jp:'haau6 zoeng2', mand:'校长', ex:'校長喺禮堂講嘢。', exjp:'haau6 zoeng2 hai2 lai5 tong4 gong2 je5.', exmand:'校长在礼堂讲话。'},
  {han:'班主任', jp:'baan1 zyu2 jam1', mand:'班主任', ex:'班主任叫我哋做功課。', exjp:'baan1 zyu2 jam1 giu3 ngo5 dei6 zou6 gung1 fo3.', exmand:'班主任叫我们做作业。'},
  {han:'教科書', jp:'gaau3 fo3 syu1', mand:'教科书', ex:'記得帶教科書返學。', exjp:'gei3 dak1 daai3 gaau3 fo3 syu1 faan1 hok6.', exmand:'记得带教科书上学。'},
  {han:'練習冊', jp:'lin6 zaap6 caak3', mand:'练习册', ex:'練習冊做咗未？', exjp:'lin6 zaap6 caak3 zou6 zo2 mei6?', exmand:'练习册做完了吗？'},
  {han:'文具', jp:'man4 geoi6', mand:'文具', ex:'書包入面有好多文具。', exjp:'syu1 baau1 jap6 min6 jau5 hou2 do1 man4 geoi6.', exmand:'书包里有很多文具。'},
  {han:'尺', jp:'cek3', mand:'尺子', ex:'借把尺俾我。', exjp:'ze3 baa2 cek3 bei2 ngo5.', exmand:'借把尺子给我。'},
  {han:'擦膠', jp:'caat3 gaau1', mand:'橡皮擦', ex:'寫錯字用擦膠擦走。', exjp:'se2 co3 zi6 jung6 caat3 gaau1 caat3 zau2.', exmand:'写错字用橡皮擦擦掉。'},
  {han:'顏色筆', jp:'ngaan4 sik1 bat1', mand:'彩笔', ex:'顏色筆畫畫好好玩。', exjp:'ngaan4 sik1 bat1 waa6 waa2 hou2 hou2 waan2.', exmand:'用彩笔画画很好玩。'},
  {han:'默書', jp:'mak6 syu1', mand:'默写', ex:'聽日要默書，記得溫書。', exjp:'ting1 jat6 jiu3 mak6 syu1, gei3 dak1 wan1 syu1.', exmand:'明天要默写，记得复习。'},
  {han:'背書', jp:'bui6 syu1', mand:'背书', ex:'背書背到好熟。', exjp:'bui6 syu1 bui6 dou3 hou2 suk6.', exmand:'背书背得很熟。'},
  {han:'補習', jp:'bou2 zaap6', mand:'补习', ex:'放學之後去補習。', exjp:'fong3 hok6 zi1 hau6 heoi3 bou2 zaap6.', exmand:'放学之后去补习。'},
  {han:'留堂', jp:'lau4 tong4', mand:'留堂（课后留校）', ex:'遲交功課要留堂。', exjp:'ci4 gaau1 gung1 fo3 jiu3 lau4 tong4.', exmand:'迟交作业要留堂。'},
  {han:'學期', jp:'hok6 kei4', mand:'学期', ex:'呢個學期就快完。', exjp:'ni1 go3 hok6 kei4 zau6 faai3 jyun4.', exmand:'这个学期快结束了。'},
  {han:'畢業', jp:'bat1 jip6', mand:'毕业', ex:'下年就畢業。', exjp:'haa6 nin4 zau6 bat1 jip6.', exmand:'明年就毕业。'}]},

{
  id:'fun', name:'休闲娱乐', icon:'🎮', words:[
    {han:'睇戲', jp:'tai2 hei3', mand:'看电影', ex:'今晚去唔去睇戲？', exjp:'gam1 maan5 heoi3 m4 heoi3 tai2 hei3?', exmand:'今晚去不去看电影？'},
    {han:'唱K', jp:'coeng3 kei1', mand:'唱K', ex:'我哋去唱K啦。', exjp:'ngo5 dei6 heoi3 coeng3 kei1 laa1.', exmand:'我们去唱K吧。'},
    {han:'行山', jp:'haang4 saan1', mand:'爬山', ex:'星期日去行山。', exjp:'sing1 kei4 jat6 heoi3 haang4 saan1.', exmand:'星期天去爬山。'},
    {han:'游水', jp:'jau4 seoi2', mand:'游泳', ex:'夏天好興游水。', exjp:'haa6 tin1 hou2 hing1 jau4 seoi2.', exmand:'夏天流行游泳。'},
    {han:'打機', jp:'daa2 gei1', mand:'打游戏', ex:'打機打到通宵。', exjp:'daa2 gei1 daa2 dou3 tung1 siu1.', exmand:'打游戏打通宵。'},
    {han:'睇波', jp:'tai2 bo1', mand:'看球赛', ex:'今晚睇波睇到好夜。', exjp:'gam1 maan5 tai2 bo1 tai2 dou3 hou2 je6.', exmand:'今晚看球看到很晚。'},
    {han:'影相', jp:'jing2 soeng2', mand:'拍照', ex:'同我影張相呀。', exjp:'tung4 ngo5 jing2 zoeng1 soeng2 aa3.', exmand:'帮我拍张照呀。'},
    {han:'聽歌', jp:'teng1 go1', mand:'听歌', ex:'我成日聽歌。', exjp:'ngo5 seng4 jat6 teng1 go1.', exmand:'我经常听歌。'},
    {han:'睇書', jp:'tai2 syu1', mand:'看书', ex:'得閒就睇書。', exjp:'dak1 haan4 zau6 tai2 syu1.', exmand:'有空就看书。'},
    {han:'去旅行', jp:'heoi3 leoi5 hang4', mand:'去旅游', ex:'暑假去旅行。', exjp:'syu3 gaa3 heoi3 leoi5 hang4.', exmand:'暑假去旅游。'},
    {han:'睇演唱會', jp:'tai2 jin2 coeng3 wui2', mand:'看演唱会', ex:'睇演唱會好激動。', exjp:'tai2 jin2 coeng3 wui2 hou2 gik1 dung6.', exmand:'看演唱会很激动。'},
    {han:'釣魚', jp:'diu3 jyu2', mand:'钓鱼', ex:'爺爺鍾意釣魚。', exjp:'je4 je4 zung1 ji3 diu3 jyu2.', exmand:'爷爷喜欢钓鱼。'},
  
  {han:'踩單車', jp:'caai2 daan1 ce1', mand:'骑自行车', ex:'假日去海旁踩單車。', exjp:'gaa2 jat6 heoi3 hoi2 pong4 caai2 daan1 ce1.', exmand:'假日去海边骑自行车。'},
  {han:'跑步', jp:'paau2 bou6', mand:'跑步', ex:'我日日早上跑步。', exjp:'ngo5 jat6 jat6 zou2 soeng6 paau2 bou6.', exmand:'我每天早上去跑步。'},
  {han:'做運動', jp:'zou6 wan6 dung6', mand:'做运动', ex:'做運動身體好。', exjp:'zou6 wan6 dung6 san1 tai2 hou2.', exmand:'做运动身体好。'},
  {han:'睇漫畫', jp:'tai2 maan6 waa2', mand:'看漫画', ex:'佢最鍾意睇漫畫。', exjp:'keoi5 zeoi3 zung1 ji3 tai2 maan6 waa2.', exmand:'他最喜欢看漫画。'},
  {han:'打羽毛球', jp:'daa2 jyu5 mou4 kau4', mand:'打羽毛球', ex:'我哋去打羽毛球啦。', exjp:'ngo5 dei6 heoi3 daa2 jyu5 mou4 kau4 laa1.', exmand:'我们去打羽毛球吧。'},
  {han:'踢波', jp:'tek3 bo1', mand:'踢球', ex:'落課去操場踢波。', exjp:'lok6 fo3 heoi3 cou1 coeng4 tek3 bo1.', exmand:'下课去操场踢球。'},
  {han:'打籃球', jp:'daa2 laam4 kau4', mand:'打篮球', ex:'佢打籃球好叻。', exjp:'keoi5 daa2 laam4 kau4 hou2 lek1.', exmand:'他打篮球很厉害。'},
  {han:'玩手機', jp:'waan2 sau2 gei1', mand:'玩手机', ex:'唔好成日玩手機。', exjp:'m4 hou2 seng4 jat6 waan2 sau2 gei1.', exmand:'不要整天玩手机。'},
  {han:'開派對', jp:'hoi1 paai3 deoi3', mand:'开派对', ex:'生日開派對慶祝。', exjp:'saang1 jat6 hoi1 paai3 deoi3 hing3 zuk1.', exmand:'生日开派对庆祝。'},
  {han:'行街', jp:'haang4 gaai1', mand:'逛街', ex:'我哋去行街買嘢。', exjp:'ngo5 dei6 heoi3 haang4 gaai1 maai5 je5.', exmand:'我们去逛街买东西。'},
  {han:'食嘢', jp:'sik6 je5', mand:'吃东西', ex:'肚餓就去食嘢。', exjp:'tou5 ngo6 zau6 heoi3 sik6 je5.', exmand:'饿了就去吃东西。'},
  {han:'打麻雀', jp:'daa2 maa4 zoek3', mand:'打麻将', ex:'新年一家人打麻雀。', exjp:'san1 nin4 jat1 gaa1 jan4 daa2 maa4 zoek3.', exmand:'新年一家人打麻将。'},
  {han:'睇電視', jp:'tai2 din6 si6', mand:'看电视', ex:'食完飯睇電視。', exjp:'sik6 jyun4 faan6 tai2 din6 si6.', exmand:'吃完饭看电视。'},
  {han:'聽音樂', jp:'teng1 jam1 ngok6', mand:'听音乐', ex:'聽音樂可以放鬆。', exjp:'teng1 jam1 ngok6 ho2 ji5 fong3 sung1.', exmand:'听音乐可以放松。'},
  {han:'露營', jp:'lou6 jing4', mand:'露营', ex:'去郊外露營好開心。', exjp:'heoi3 gaau1 ngoi6 lou6 jing4 hou2 hoi1 sam1.', exmand:'去郊外露营很开心。'},
  {han:'潛水', jp:'cim4 seoi2', mand:'潜水', ex:'佢學緊潛水。', exjp:'keoi5 hok6 gan2 cim4 seoi2.', exmand:'他在学潜水。'},
  {han:'滑雪', jp:'waat6 syut3', mand:'滑雪', ex:'去日本滑雪好好玩。', exjp:'heoi3 jat6 bun2 waat6 syut3 hou2 hou2 waan2.', exmand:'去日本滑雪很好玩。'},
  {han:'燒烤', jp:'siu1 haau1', mand:'烧烤', ex:'週末約朋友燒烤。', exjp:'zau1 mut6 joek3 pang4 jau5 siu1 haau1.', exmand:'周末约朋友烧烤。'}]},
],

/* ---------- 3. 对话场景 ---------- */
dialogues: [
{
  id:'dimsum', title:'茶楼饮茶', emoji:'🍵', level:'初级', desc:'点心纸、点心车，坐低叹番一盅两件。', tags:['饮食','礼貌','点餐'], lines:[
    {speaker:'侍应', han:'早晨，幾位呀？', jp:'zou2 san4, gei2 wai2 aa3?', mand:'早上好，几位呀？'},
    {speaker:'食客', han:'兩位，唔該。', jp:'loeng5 wai2, m4 goi1.', mand:'两位，谢谢。'},
    {speaker:'侍应', han:'飲咩茶呀？', jp:'jam2 me1 caa4 aa3?', mand:'喝什么茶呀？'},
    {speaker:'食客', han:'普洱啦。', jp:'pou2 lei2 laa1.', mand:'普洱吧。'},
    {speaker:'侍应', han:'要啲咩點心？', jp:'jiu3 di1 me1 dim2 sam1?', mand:'要点什么点心？'},
    {speaker:'食客', han:'蝦餃同燒賣，仲要一碟腸粉。', jp:'haa1 gaau2 tung4 siu1 maai6, zung6 jiu3 jat1 dip6 coeng2 fan2.', mand:'虾饺和烧麦，还要一碟肠粉。'},
    {speaker:'侍应', han:'好，唔該稍等。', jp:'hou2, m4 goi1 saau1 dang2.', mand:'好的，请稍等。'},
    {speaker:'食客', han:'唔該，埋單！', jp:'m4 goi1, maai4 daan1!', mand:'麻烦，买单！'},
    {speaker:'侍应', han:'盛惠八十八蚊。', jp:'sing6 wai6 baat3 sap6 baat3 man1.', mand:'一共八十八块。'},
  ]},
{
  id:'market', title:'街市买菜', emoji:'🥬', level:'初级', desc:'问价、讲价、称重，街市对话最生活化。', tags:['购物','砍价','食物'], lines:[
    {speaker:'档主', han:'早晨，想買啲咩呀？', jp:'zou2 san4, soeng2 maai5 di1 me1 aa3?', mand:'早上好，想买点什么呀？'},
    {speaker:'顾客', han:'呢啲菜新唔新鮮㗎？', jp:'ni1 di1 coi3 san1 m4 san1 sin1 gaa3?', mand:'这菜新鲜吗？'},
    {speaker:'档主', han:'好新鮮㗎，今朝先到。', jp:'hou2 san1 sin1 gaa3, gam1 ziu1 sin1 dou3.', mand:'很新鲜，今早刚到。'},
    {speaker:'顾客', han:'幾錢一斤呀？', jp:'gei2 cin2 jat1 gan1 aa3?', mand:'多少钱一斤呀？'},
    {speaker:'档主', han:'十蚊一斤咋。', jp:'sap6 man1 jat1 gan1 zaa3.', mand:'才十块钱一斤。'},
    {speaker:'顾客', han:'咁平？畀兩斤我啦。', jp:'gam3 peng4? bei2 loeng5 gan1 ngo5 laa1.', mand:'这么便宜？给我两斤吧。'},
    {speaker:'档主', han:'好，廿蚊。仲要唔要啲咩？', jp:'hou2, jaa6 man1. zung6 jiu3 m4 jiu3 di1 me1?', mand:'好，二十块。还要点别的吗？'},
    {speaker:'顾客', han:'唔使喇，唔該。', jp:'m4 sai2 laa3, m4 goi1.', mand:'不用了，谢谢。'},
    {speaker:'档主', han:'多謝，慢慢行！', jp:'do1 ze6, maan6 maan6 haang4!', mand:'谢谢，慢走！'},
  ]},
{
  id:'bus', title:'搭巴士', emoji:'🚌', level:'入门', desc:'问路线上车、拍八达通、报站落车。', tags:['交通','问询'], lines:[
    {speaker:'乘客', han:'唔該，呢架車去唔去中環㗎？', jp:'m4 goi1, ni1 gaa3 ce1 heoi3 m4 heoi3 zung1 waan4 gaa3?', mand:'请问，这趟车去不去中环呀？'},
    {speaker:'司机', han:'去，上嚟啦。', jp:'heoi3, soeng5 lai4 laa1.', mand:'去，上来吧。'},
    {speaker:'乘客', han:'唔該，八達通。', jp:'m4 goi1, baat3 daat6 tung1.', mand:'谢谢，刷八达通。'},
    {speaker:'司机', han:'得喇。', jp:'dak1 laa3.', mand:'行了。'},
    {speaker:'乘客', han:'司機，中環站係咪下一個站呀？', jp:'si1 gei1, zung1 waan4 zaam6 hai6 mai6 haa6 jat1 go3 zaam6 aa3?', mand:'司机，中环站是下一站吗？'},
    {speaker:'司机', han:'唔係，仲有一個站先到。', jp:'m4 hai6, zung6 jau5 jat1 go3 zaam6 sin1 dou3.', mand:'不是，还要一个站才到。'},
    {speaker:'乘客', han:'咁到咗話我知得唔得呀？', jp:'gam3 dou3 zo2 waa6 ngo5 zi1 dak1 m4 dak1 aa3?', mand:'那到了叫我一声行吗？'},
    {speaker:'司机', han:'冇問題。', jp:'mou5 man6 tai4.', mand:'没问题。'},
  ]},
{
  id:'chachaanteng', title:'茶餐厅落单', emoji:'🍛', level:'入门', desc:'常餐、冻饮加钱、飞冰走糖，港式快餐暗语。', tags:['饮食','点餐'], lines:[
    {speaker:'侍应', han:'食啲咩呀？', jp:'sik6 di1 me1 aa3?', mand:'吃点什么呀？'},
    {speaker:'顾客', han:'一個常餐，凍奶茶，飛冰。', jp:'jat1 go3 soeng4 caan1, dung3 naai5 caa4, fei1 bing1.', mand:'一个常餐，冻奶茶，去冰。'},
    {speaker:'侍应', han:'常餐跟餐飲，凍飲加兩蚊喎。', jp:'soeng4 caan1 gan1 caan1 jam2, dung3 jam2 gaa1 loeng5 man1 wo3.', mand:'常餐含饮品，冻饮要加两块钱哦。'},
    {speaker:'顾客', han:'冇所謂，照要。', jp:'mou5 so2 wai6, ziu3 jiu3.', mand:'没关系，照要。'},
    {speaker:'侍应', han:'好嘅，即刻嚟。', jp:'hou2 ge3, zik1 hak1 lai4.', mand:'好的，马上来。'},
  ]},
{
  id:'direction', title:'问路', emoji:'🗺️', level:'入门', desc:'在街头向路人问路，练习方位与指路表达。', tags:['出行','问询'], lines:[
    {speaker:'游客', han:'唔該，我想去星光大道，點樣行呀？', jp:'m4 goi1, ngo5 soeng2 heoi3 sing1 gwong1 daai6 dou6, dim2 joeng2 haang4 aa3?', mand:'请问，我想去星光大道，怎么走呀？'},
    {speaker:'路人', han:'沿住海旁一直行，五分鐘就到。', jp:'jyun4 zyu6 hoi2 pong4 jat1 zik6 haang4, ng5 fan1 zung1 zau6 dou3.', mand:'沿着海边一直走，五分钟就到。'},
    {speaker:'游客', han:'咁近㗎，唔該晒！', jp:'gam3 kan5 gaa3, m4 goi1 saai3!', mand:'这么近呀，太感谢了！'},
    {speaker:'路人', han:'唔使客氣。', jp:'m4 sai2 haak3 hei3.', mand:'不客气。'},
  ]},
{
  id:'doctor', title:'睇医生', emoji:'🩺', level:'初级', desc:'挂号问诊，描述病症，听懂医嘱。', tags:['健康','就医'], lines:[
    {speaker:'护士', han:'你邊度唔舒服呀？', jp:'nei5 bin1 dou6 m4 syu1 fuk6 aa3?', mand:'你哪里不舒服呀？'},
    {speaker:'病人', han:'我頭痛，仲有啲發燒。', jp:'ngo5 tau4 tung3, zung6 jau5 di1 faat3 siu1.', mand:'我头痛，还有点发烧。'},
    {speaker:'护士', han:'幾耐喇？', jp:'gei2 noi6 laa3?', mand:'多久了？'},
    {speaker:'病人', han:'兩日喇。', jp:'loeng5 jat6 laa3.', mand:'两天了。'},
    {speaker:'护士', han:'好，坐低等陣，醫生好快叫你。', jp:'hou2, co5 dai1 dang2 zan6, ji1 sang1 hou2 faai3 giu3 nei5.', mand:'好，坐下等会儿，医生很快叫你。'},
  ]},

{
  id:'airport', title:'機場過關', emoji:'✈️', level:'中级',
  desc:'搭飞机出行，问路、赶时间、道别一次搞掂。',
  tags:['交通','出行','问询'],
  lines:[
    {speaker:'乘客', han:'請問去機場嘅巴士喺邊度搭？', jp:'cing2 man6 heoi3 gei1 coeng4 ge3 baa1 si2 hai2 bin1 dou6 daap3?', mand:'请问去机场的巴士在哪里坐？'},
    {speaker:'職員', han:'行前少少，五分鐘後有車。', jp:'haang4 cin4 siu2 siu2, ng5 fan1 zung1 hau6 jau5 ce1.', mand:'往前走一点，五分钟后有车。'},
    {speaker:'乘客', han:'幾耐先到機場呀？', jp:'gei2 noi6 sin1 dou3 gei1 coeng4 aa3?', mand:'多久能到机场呀？'},
    {speaker:'職員', han:'唔塞車就四十分鐘。', jp:'m4 sak1 ce1 zau6 sei3 sap6 fan1 zung1.', mand:'不堵车就四十分钟。'},
    {speaker:'乘客', han:'我搭十點半嘅機，會唔會遲呀？', jp:'ngo5 daap3 sap6 dim2 bun3 ge3 gei1, wui5 m4 wui5 ci4 aa3?', mand:'我乘十点半的飞机，会晚吗？'},
    {speaker:'職員', han:'依家先八點，實嚟得切。', jp:'ji1 gaa1 sin1 baat3 dim2, sat6 lai4 dak1 cit3.', mand:'现在才八点，一定来得及。'},
    {speaker:'乘客', han:'唔該晒！', jp:'m4 goi1 saai3!', mand:'谢谢！'},
    {speaker:'職員', han:'唔使客氣，旅途愉快。', jp:'m4 sai2 haak3 hei3, leoi5 tou4 jyu4 faai3.', mand:'不客气，旅途愉快。'},
  ],
},
{
  id:'rent', title:'睇樓租房', emoji:'🏠', level:'中级',
  desc:'租屋必问：面积、租金、管理费，同业主倾价。',
  tags:['生活','租房','讲价'],
  lines:[
    {speaker:'業主', han:'你好，睇樓呀？就係呢個單位。', jp:'nei5 hou2, tai2 lau2 aa3? zau6 hai6 ni1 go3 daan1 wai2.', mand:'你好，看房吗？就是这个单位。'},
    {speaker:'租客', han:'你個單位幾多呎呀？', jp:'nei5 go3 daan1 wai2 gei2 do1 cek3 aa3?', mand:'你的单位多少平方呎呀？'},
    {speaker:'業主', han:'四百呎，兩房一廳，夠住。', jp:'sei3 baak3 cek3, loeng5 fong2 jat1 teng1, gau3 zyu6.', mand:'四百呎，两房一厅，够住。'},
    {speaker:'租客', han:'月租幾多？包唔包管理費？', jp:'jyut6 zou1 gei2 do1? baau1 m4 baau1 gun2 lei5 fai3?', mand:'月租多少？包不包管理费？'},
    {speaker:'業主', han:'一萬八蚊，包管理費同水電。', jp:'jat1 maan6 baat3 man1, baau1 gun2 lei5 fai3 tung4 seoi2 din6.', mand:'一万八块，包管理费和水电。'},
    {speaker:'租客', han:'有冇得平啲呀？', jp:'jau5 mou5 dak1 peng4 di1 aa3?', mand:'能便宜一点吗？'},
    {speaker:'業主', han:'最多平五百，再平就蝕本。', jp:'zeoi3 do1 peng4 ng5 baak3, zoi3 peng4 zau6 sit6 bun2.', mand:'最多便宜五百，再便宜就亏本。'},
    {speaker:'租客', han:'咁我返去諗吓先。', jp:'gam2 ngo5 faan1 heoi3 nam2 haa5 sin1.', mand:'那我回去想想再说。'},
  ],
},
{
  id:'karaoke', title:'唱K約局', emoji:'🎤', level:'初级',
  desc:'约朋友唱K，订房、点歌、轮麦一条龙。',
  tags:['娱乐','邀约','唱歌'],
  lines:[
    {speaker:'朋友A', han:'今晚去唔去唱K呀？', jp:'gam1 maan5 heoi3 m4 heoi3 coeng3 kei1 aa3?', mand:'今晚去不去唱K呀？'},
    {speaker:'朋友B', han:'好呀，約多幾個friend一齊。', jp:'hou2 aa3, joek3 do1 gei2 go3 friend jat1 cai4.', mand:'好呀，多约几个朋友一起。'},
    {speaker:'朋友A', han:'訂咗房未？我哋六個人。', jp:'deng6 zo2 fong2 mei6? ngo5 dei6 luk6 go3 jan4.', mand:'订了房没？我们六个人。'},
    {speaker:'朋友B', han:'未呀，依家打去訂。', jp:'mei6 aa3, ji1 gaa1 daa2 heoi3 deng6.', mand:'还没，现在打去订。'},
    {speaker:'朋友A', han:'唱粵語歌定國語歌多？', jp:'coeng3 jyut6 jyu5 go1 ding6 gwok3 jyu5 go1 do1?', mand:'唱粤语歌多还是国语歌多？'},
    {speaker:'朋友B', han:'梗係粵語歌，練吓發音。', jp:'gang2 hai6 jyut6 jyu5 go1, lin6 haa5 faat3 jam1.', mand:'当然是粤语歌，练练发音。'},
    {speaker:'朋友A', han:'我點咗《海闊天空》，到你唱。', jp:'ngo5 dim2 zo2 hoi2 fut3 tin1 hung1, dou3 nei5 coeng3.', mand:'我点了《海阔天空》，轮到你唱。'},
    {speaker:'朋友B', han:'好嘢！嗌支可樂先。', jp:'hou2 je5! aai3 zi1 ho2 lok6 sin1.', mand:'好耶！先叫杯可乐。'},
  ],
},
],

/* ---------- 4. 语法专栏 ---------- */
grammar: [
{
  id:'measure', num:'01', title:'量词面面观：个、只、条、嚿…', intro:'粤语的量词比普通话更"精细"：同一物品在两种语言里可能用不同的量词，同一个量词也可能覆盖完全不同的物品。量词用错，一听就知道不是本地人。',
  sections:[
    {h:'高频量词速查', type:'table', head:['量词','常用对象','例句'],
     rows:[['个 go3','人、家庭、职业','一个朋友 / 呢个问题'],['只 zek3','动物、鞋子、碗','一只鸡 / 三只鞋'],['条 tiu4','长条物、鱼、路','一条鱼 / 呢条街'],['张 zoeng1','纸、桌子、票','一张飞（票）'],['件 gin6','衣服、事情、行李','一件衫 / 一件大事'],['杯 bui1','饮品','一杯奶茶'],['碗 wun2','饭、面','一碗云吞面'],['碟 dip6','菜、点心','一碟肠粉'],['樽 zeon1','瓶装物','一樽水'],['部 bou6','机器、车辆','一部手机 / 一部车'],['架 gaa3','车辆','一架的士'],['粒 nap1','小圆物、药','一粒糖 / 一粒药'],['嚿 gau6','块状物（粗粝感）','一嚿石 / 一嚿饭'],['碌 luk1','柱状物','一碌蔗（甘蔗）'],['份 fan6','文件、套餐','一份报纸']]},
    {h:'易混量词对比', type:'table', head:['场景','粤语','普通话'],
     rows:[['一辆车','一架车 / 一部车','一辆车'],['一栋楼','一幢楼 / 一楝楼','一栋楼'],['一床被子','一张被','一床被子'],['一条裤子','一条裤','一条裤子'],['一只狗','一只狗','一只狗（一条狗）'],['一家餐厅','一间餐厅','一家餐厅']]},
    {h:'小贴士', type:'note', body:'量词前接「呢 / 嗰」表"这 / 那"：呢个（这个）、嗰只（那只）。「一」在量词前常读轻声 jat1，口语常说成"咁多"时要记得数一数量词配搭。'},
  ],
  examples:[
    {han:'呢個問題好簡單。', jp:'ni1 go3 man6 tai4 hou2 gaan2 daan1.', mand:'这个问题很简单。'},
    {han:'我要一碟腸粉同兩杯奶茶。', jp:'ngo5 jiu3 jat1 dip6 coeng2 fan2 tung4 loeng5 bui1 naai5 caa4.', mand:'我要一碟肠粉和两杯奶茶。'},
    {han:'嗰只貓好得意。', jp:'go2 zek3 maau1 hou2 dak1 ji3.', mand:'那只猫很可爱。'},
    {han:'一嚿飯都食唔晒。', jp:'jat1 gau6 faan6 dou1 sik6 m4 saai3.', mand:'一坨饭都吃不完。'},
  ]},
{
  id:'particles', num:'02', title:'语气词大观：啦、喎、㗎、咩、咋…', intro:'语气词是粤语的灵魂。同样的句子，换上不同的句尾语气词，意思、态度天差地别。这也是普通话母语者最头疼、也最"出味"的部分。',
  sections:[
    {h:'句尾语气词速查', type:'table', head:['语气词','语气/含义','例句'],
     rows:[['啦 laa1','肯定、催促、舒缓','唔该埋单啦。'],['喎 wo3','提醒对方不知道的事','冻饮加两蚊喎。'],['㗎 gaa3','反问/强调事实','佢好叻㗎！'],['咩 me1','疑问（意外）','你唔系去咗咩？'],['咋 zaa3','仅此而已（轻描淡写）','十蚊咋。'],['啫 ze1','而已（略不耐）','慢慢嚟啫。'],['呀 aa3','疑问（轻松）','你食咗饭未呀？'],['喇 laa3','已然、完成','我食完喇。'],['啦嘛 laa1 maa3','理所当然','冇办法啦嘛。'],['先 sin1','先、再（句尾表"再说"）','你睇下先。']]},
    {h:'三个高频词细说', type:'text', body:'「啦」：表肯定与商量，普通话的"吧/了"都有它的影子。「喎」：提醒对方一个TA不知道的事实，带点"喂，听我说"的意味。「㗎」：反问或强调，句调往上扬。'},
    {h:'小贴士', type:'note', body:'语气词可以和「呀」「啦」叠加，如"得啦呀"。语气词发音要轻而短，语调才是真正决定含义的部分——多听多模仿。'},
  ],
  examples:[
    {han:'唔該，埋單啦。', jp:'m4 goi1, maai4 daan1 laa1.', mand:'麻烦，买单吧。'},
    {han:'呢度好出名㗎！', jp:'ni1 dou6 hou2 ceot1 meng2 gaa3!', mand:'这里很有名呢！'},
    {han:'你唔係話嚟咩？', jp:'nei5 m4 hai6 waa6 lai4 me1?', mand:'你不是说要来吗？'},
    {han:'唔使驚喎，我喺度。', jp:'m4 sai2 geng1 wo3, ngo5 hai2 dou6.', mand:'别怕哦，我在这。'},
  ]},
{
  id:'aspect', num:'03', title:'动词体貌：咗、紧、过、开、下', intro:'粤语用句尾助词表达动作的状态，跟普通话的"了、着、过"大致对应，但用法更精细、更日常。',
  sections:[
    {h:'体貌助词速查', type:'table', head:['助词','含义','例句'],
     rows:[['咗 zo2','完成（类似"了"）','我食咗饭。'],['紧 gan2','进行中（类似"着"）','佢睇紧电视。'],['过 gwo3','曾经经历','我去过香港。'],['开 hoi1','习惯性动作','我食开呢间。'],['下 haa5','尝试一下','试下先。'],['完 jyun4','完成（尾）','我做完工先讲。']]},
    {h:'「咗」和「紧」', type:'text', body:'「咗」表示动作已经完成，相当于"……了"；「紧」表示正在进行，相当于"……着/正在……"。注意它们都放在动词后面、宾语前面。'},
    {h:'「开」的妙用', type:'text', body:'「食开」「做开」表示一直以来的习惯，隐含"我经常这样，所以理所当然"。例如「我食开呢间茶餐厅」= 我常来这家，很熟。'},
  ],
  examples:[
    {han:'我食咗飯喇。', jp:'ngo5 sik6 zo2 faan6 laa3.', mand:'我吃过饭了。'},
    {han:'佢而家睇緊電視。', jp:'keoi5 ji4 gaa1 tai2 gan2 din6 si6.', mand:'他现在正在看电视。'},
    {han:'你去過廣州未呀？', jp:'nei5 heoi3 gwo3 gwong2 zau1 mei6 aa3?', mand:'你去过广州没有呀？'},
    {han:'試下先啦。', jp:'si3 haa5 sin1 laa1.', mand:'先试试看吧。'},
  ]},
{
  id:'hai6', num:'04', title:'「系」字家族：系、唔系、系咪…', intro:'粤语的「系」对应普通话的"是"，但衍生出一整套高频表达，几乎每句话都绕不开它。',
  sections:[
    {h:'「系」的用法', type:'table', head:['表达','含义','例句'],
     rows:[['系 hai6','是','我系老师。'],['唔系 m4 hai6','不是','我唔系老师。'],['系咪 hai6 mai6','是不是（疑问）','佢系咪嚟㗎？'],['系咩 hai6 me1','是吗（反问）','系咩？唔系啩。'],['系啦 hai6 laa1','对啊（附和）','系啦，我都咁话。'],['系话 hai6 waa6','就是说','系话，不如去饮茶？']]},
    {h:'「系」vs 普通话"是"', type:'text', body:'粤语「系」除了表判断，还常用来附和对方（系啦！）。疑问句常用「系咪」直接问，不用"是不是"那么长的结构。'},
  ],
  examples:[
    {han:'我係香港人。', jp:'ngo5 hai6 hoeng1 gong2 jan4.', mand:'我是香港人。'},
    {han:'佢係咪你朋友呀？', jp:'keoi5 hai6 mai6 nei5 pang4 jau5 aa3?', mand:'他是不是你朋友呀？'},
    {han:'係啦，我都係咁諗。', jp:'hai6 laa1, ngo5 dou1 hai6 gam2 nam2.', mand:'是啊，我也这么想。'},
  ]},
{
  id:'position', num:'05', title:'位置与虚词：喺、响、嚟、去、俾、同', intro:'几个小词撑起粤语的空间与关系表达：在哪、去哪、给谁、跟谁。',
  sections:[
    {h:'位置词', type:'table', head:['词','含义','例句'],
     rows:[['喺 hai2','在（某处）','我喺屋企。'],['响 hoeng2','在（口语，同"喺"）','佢响公司。'],['嚟 lai4','来','你快啲嚟！'],['去 heoi3','去','我哋去街。'],['返 faan1','回','放工返屋企。']]},
    {h:'关系词', type:'table', head:['词','含义','例句'],
     rows:[['俾 bei2','给 / 被','俾支笔我；俾人闹'],['同 tung4','和 / 跟','我同你去。'],['帮 bong1','帮','帮我影张相。'],['畀 bei2','给（同"俾"）','畀钱先。']]},
    {h:'「俾」的双重身份', type:'text', body:'「俾」既是"给"（俾我 = 给我），也是被动标记（俾人闹 = 被人骂）。小心别混淆。'},
  ],
  examples:[
    {han:'我而家喺地鐵站。', jp:'ngo5 ji4 gaa1 hai2 dei6 tit3 zaam6.', mand:'我现在在地铁站。'},
    {han:'快啲嚟啦，等你啊。', jp:'faai3 di1 lai4 laa1, dang2 nei5 aa3.', mand:'快点来啦，等你呢。'},
    {han:'俾支筆我用下。', jp:'bei2 zi1 bat1 ngo5 jung6 haa5.', mand:'借支笔给我用一下。'},
    {han:'我同朋友食緊飯。', jp:'ngo5 tung4 pang4 jau5 sik6 gan2 faan6.', mand:'我和朋友正在吃饭。'},
  ]},
{
  id:'compare', num:'06', title:'比较句：A 好过 B', intro:'粤语比较句用「过」不用"比"：A 好过 B = A 比 B 好。结构简洁，一学就会。',
  sections:[
    {h:'基本结构', type:'table', head:['结构','含义','例句'],
     rows:[['A + 形容词 + 过 + B','A比B更…','地铁快过巴士。'],['A + 形容词 + 过 + B + 好多','A比B…得多','佢高过我好多。'],['有 + B + 咁 + 形容词','有B那么…','你有佢咁高咩？'],['冇 + B + 咁 + 形容词','没B那么…','我冇佢咁高。']]},
    {h:'程度加强', type:'text', body:'要表示"得多"，在「过」后面加「好多」；表示"一点"，加「啲」：好过佢啲（比他好一点）。'},
  ],
  examples:[
    {han:'地鐵快過巴士。', jp:'dei6 tit3 faai3 gwo3 baa1 si2.', mand:'地铁比公交快。'},
    {han:'佢高過我好多。', jp:'keoi5 gou1 gwo3 ngo5 hou2 do1.', mand:'他比我高很多。'},
    {han:'我冇你咁識講嘢。', jp:'ngo5 mou5 nei5 gam3 sik1 gong2 je5.', mand:'我没你那么会说话。'},
  ]},
{
  id:'negation', num:'07', title:'否定表达：唔、冇、未、咪、唔使…', intro:'粤语的否定词各有分工：唔=不、冇=没有、未=还没、咪=别。用错一个，意思就变了。',
  sections:[
    {h:'否定词速查', type:'table', head:['词','含义','例句'],
     rows:[['唔 m4','不','唔好 / 唔得 / 唔知'],['冇 mou5','没有','冇钱 / 冇时间'],['未 mei6','还没','未食饭'],['咪 mai5','别（祈使）','咪乱讲！'],['唔使 m4 sai2','不用','唔使客气'],['唔该 m4 goi1','劳驾/谢谢','唔该埋单']]},
    {h:'「唔」的否定小词', type:'text', body:'唔好（不好/别）、唔得（不行）、唔知（不知道）、唔明（不明白）……「唔」后面直接加动词或形容词，像普通话"不"一样灵活。'},
    {h:'「冇」vs「未」', type:'text', body:'「冇」强调"没有"这个状态（冇钱=没钱）；「未」强调"还没做"（未食饭=还没吃饭）。回答"食咗饭未？"时，说「未呀」就是"还没呢"。'},
  ],
  examples:[
    {han:'我唔知佢喺邊。', jp:'ngo5 m4 zi1 keoi5 hai2 bin1.', mand:'我不知道他在哪。'},
    {han:'我冇錢買飛。', jp:'ngo5 mou5 cin4 maai5 fei1.', mand:'我没钱买票。'},
    {han:'你食咗飯未？未呀。', jp:'nei5 sik6 zo2 faan6 mei6? mei6 aa3.', mand:'你吃饭了吗？还没呢。'},
    {han:'咪嘈啦！', jp:'mai5 cou4 laa1!', mand:'别吵啦！'},
  ]},
{
  id:'question', num:'08', title:'疑问词全家福：咩、点、几时、边度、点解…', intro:'粤语疑问词和普通话差异较大，但数量少、规律强，记熟这一套就能问遍天下。',
  sections:[
    {h:'疑问词速查', type:'table', head:['粤语','含义','例句'],
     rows:[['咩 me1','什么','食咩呀？'],['边个 bin1 go3','谁','边个嚟㗎？'],['边度 bin1 dou6','哪里','去边度呀？'],['几时 gei2 si4','什么时候','几时出发？'],['点解 dim2 gaai2','为什么','点解迟到呀？'],['点 dim2','怎么','点去呀？'],['几点 gei2 dim2','几点','而家几点？'],['几多 gei2 do1','多少','几多钱呀？'],['点样 dim2 joeng2','怎么样','点样行呀？']]},
    {h:'「咩」的多重身份', type:'text', body:'「咩」表"什么"（食咩=吃什么），也可以单独用在句尾表反问（你唔嚟咩？=你不来吗？）。'},
    {h:'正反疑问', type:'text', body:'用「A唔A」结构：去唔去（去不去）、系唔系（是不是）、好唔好（好不好），加句尾「呀」更自然。'},
  ],
  examples:[
    {han:'你食咩呀？', jp:'nei5 sik6 me1 aa3?', mand:'你吃什么呀？'},
    {han:'呢度去邊度最近？', jp:'ni1 dou6 heoi3 bin1 dou6 zeoi3 kan5?', mand:'这里去哪最近？'},
    {han:'點解你唔嚟？', jp:'dim2 gaai2 nei5 m4 lai4?', mand:'为什么你不来？'},
    {han:'你聽日去唔去飲茶？', jp:'nei5 ting1 jat6 heoi3 m4 heoi3 jam2 caa4?', mand:'你明天去不去喝早茶？'},
  ]},
{
  id:'degree', num:'09', title:'程度副词：好、几、劲、超、鬼咁…', intro:'普通话说"很、非常"，粤语说「好、几、劲」。口语里还有一堆夸张又生动的说法，越地道越有趣。',
  sections:[
    {h:'程度副词速查', type:'table', head:['副词','程度','例句'],
     rows:[['好 hou2','很（中性）','好靓'],['几 gei2','挺（温和）','几好食'],['劲 ging6','超（夸张）','劲好玩'],['超 ciu1','超（年轻人口语）','超正'],['鬼咁 gwai2 gam3','超（俏皮）','鬼咁靓'],['冇得顶 mou5 dak1 deng2','没得顶/极好','佢嘅厨艺冇得顶']]},
    {h:'「好」的用法', type:'text', body:'「好」是最高频的程度副词：好靓、好正、好正点。注意「好」也可以单用表"好/行/可以"（好！= 好！行！）。'},
    {h:'夸张系表达', type:'text', body:'「鬼咁」带俏皮感：「鬼咁靓」= 靓到爆。「冇得顶」= 无可挑剔。这种带情绪的夸张说法，最能体现粤语的生猛。'},
  ],
  examples:[
    {han:'呢間嘢好正㗎！', jp:'ni1 gaan1 je5 hou2 zeng3 gaa3!', mand:'这家店超棒的呢！'},
    {han:'今日熱到飛起。', jp:'gam1 jat6 jit6 dou3 fei1 hei2.', mand:'今天热得要命。'},
    {han:'佢講粵語鬼咁流利。', jp:'keoi5 gong2 jyut6 jyu5 gwai2 gam3 lau4 lei6.', mand:'他说粤语超级流利。'},
    {han:'呢碟叉燒冇得頂！', jp:'ni1 dip6 caa1 siu1 mou5 dak1 deng2!', mand:'这碟叉烧没得挑！'},
  ]},
{
  id:'reduplication', num:'10', title:'叠字口语：食食下、行行下、谂谂吓', intro:'动词叠用+「下」表示动作进行到一半，是粤语特有的节奏感表达。',
  sections:[
    {h:'核心结构', type:'table', head:['结构','含义','例句'],
     rows:[['V + V + 下','正…到一半（突然）','食食下先发现冇餸'],['V + V + 吓','试着做做','谂谂吓先'],['V + 咗 + V','做完（强调完成）','做咗先讲'],['V + 嚟 + V + 去','反复折腾','行来行去']]},
    {h:'「食食下」的妙处', type:'text', body:'「食食下」= 吃着吃着，后面常接转折：食食下先发现（吃着吃着才发现）。这种"动作中途"的表达，普通话里没有直接对应，是粤语味的标志。'},
  ],
  examples:[
    {han:'我行行下先記起冇帶鎖匙。', jp:'ngo5 haang4 haang4 haa5 sin1 gei3 hei2 mou5 daai3 so2 si4.', mand:'我走着走着才想起没带钥匙。'},
    {han:'佢講講下突然停咗。', jp:'keoi5 gong2 gong2 haa5 dat6 jin4 ting4 zo2.', mand:'他说着说着突然停了。'},
    {han:'你諗諗吓先，唔使急。', jp:'nei5 nam2 nam2 haa5 sin1, m4 sai2 gap1.', mand:'你先想想，不用急。'},
  ]},
],

/* ---------- 5. 文化趣知 ---------- */
culture: {
  sayings: [
    {han:'馬死落地行', jp:'maa5 sei2 lok6 dei6 haang4', meaning:'车到山前必有路，办法总比困难多。', story:'旧时出行靠马，马死了就只能下地走路。比喻遇到变故也要继续前行，办法总比困难多。'},
    {han:'有錢使得鬼推磨', jp:'jau5 cin4 sai2 dak1 gwai2 teoi1 mo6', meaning:'有钱能使鬼推磨。', story:'只要有钱，连鬼都愿意替你干活。讽刺金钱万能，也提醒人别被钱牵着走。'},
    {han:'雞髀打人牙鉸軟', jp:'gai1 bei2 daa2 jan4 ngaa4 gaau3 jyun5', meaning:'吃人嘴软，拿人手短。', story:'髀=鸡腿，牙铰=下巴。用鸡腿"打"你的下巴，你的嘴就软了——收了人家的好处，自然说不出硬话。'},
    {han:'食得鹹魚抵得渴', jp:'sik6 dak1 haam4 jyu2 dai2 dak1 hot3', meaning:'敢做就要敢当，拿了好处就要承担后果。', story:'吃了咸鱼就要忍得住口渴。比喻既然选择了一条路，就要接受它带来的麻烦。'},
    {han:'執輸行頭，慘過敗家', jp:'zap1 syu1 haang4 tau4, caam2 gwo3 baai6 gaa1', meaning:'样样落后于人，比败家更惨。', story:'执输=吃亏落后；行头=走在最前（此处反语）。事事抢不到先机，比挥霍家产还惨，提醒人要进取。'},
    {han:'蘇州過後無艇搭', jp:'sou1 zau1 gwo3 hau6 mou4 teng5 daap3', meaning:'机不可失，时不再来。', story:'以前坐船去苏州，错过了就没船了。比喻机会稍纵即逝，要当机立断。'},
    {han:'朝朝早，飲早茶', jp:'ziu1 ziu1 zou2, jam2 zou2 caa4', meaning:'天天早晨喝早茶，日子过得悠闲。', story:'广东人一天从"叹早茶"开始，一盅两件慢慢叹，是一种刻在骨子里的生活态度。'},
    {han:'一世人兩兄弟', jp:'jat1 sai3 jan4 loeng5 hing1 dai6', meaning:'一辈子两兄弟，手足情深。', story:'粤语"一世人"=一辈子。强调兄弟情谊要珍惜一辈子，常用来形容过命交情。'},
    {han:'見高拜，見低踩', jp:'gin3 gou1 baai3, gin3 dai1 caai2', meaning:'见高就拜，见低就踩（势利眼）。', story:'对上阿谀奉承，对下踩低欺压，讽刺趋炎附势的势利小人。'},
    {han:'偷雞唔到蝕揸米', jp:'tau1 gai1 m4 dou3 sit6 zaa1 mai5', meaning:'偷鸡不成蚀把米。', story:'想偷鸡没偷着，反而搭进去一把米。比喻想占便宜反倒吃了亏。'},
    {han:'死雞撐飯蓋', jp:'sei2 gai1 caang3 faan6 goi3', meaning:'死鸭子嘴硬。', story:'鸡都死了还硬撑着锅盖。比喻明知理亏却死不认错，嘴硬到底。'},
    {han:'十個光頭九個富', jp:'sap6 go3 gwong1 tau4 gau2 go3 fu3', meaning:'十个光头九个富。', story:'民间戏谑的说法：光头的人多半有钱。茶楼里最常见的玩笑开场白之一。'},  ],
  xiehou: [
    {front:'老公潑扇', back:'悽（妻）涼', jp:'lou5 gung1 put3 sin3 — cat1 loeng4', meaning:'形容处境凄凉、寒酸。', story:'老公给老婆扇扇子——"妻凉"谐音"凄凉"，一语双关，冷幽默十足。'},
    {front:'啞巴食黃連', back:'有苦自己知', jp:'aa2 baa1 sik6 wong4 lin4 — jau5 fu2 zi6 gei2 zi1', meaning:'有苦说不出，只能自己扛。', story:'黄连极苦，哑巴吃了说不出，只能自己知道。粤语版比普通话版更强调"自己扛"。'},
    {front:'老鼠拉龜', back:'冇哂符', jp:'lou2 syu2 laai1 gwai1 — mou5 saai3 fu4', meaning:'无从下手，无计可施。', story:'老鼠想拖走乌龟，龟壳太滑太硬，怎么都使不上劲——"冇哂符"= 没辙了。'},
    {front:'茶樓搬家', back:'另起爐灶', jp:'caa4 lau2 bun1 gaa1 — ling6 hei2 lou4 zou3', meaning:'另起炉灶，重新开始。', story:'茶楼搬走，蒸笼炉灶自然要重新搭。比喻放弃旧摊子，从头再来。'},
    {front:'貓兒洗面', back:'咁上吓', jp:'maau1 ji4 sai2 min6 — gam3 soeng5 haa5', meaning:'随便应付，敷衍了事。', story:'猫洗脸只是随意抹两下，哪算认真洗？"咁上吓"= 差不多应付过去。'},
    {front:'閻羅王嫁女', back:'鬼要', jp:'jip4 lo4 wong4 gaa3 neoi5 — gwai2 jiu3', meaning:'没人要、没人稀罕。', story:'阎罗王嫁女儿，只有鬼才要。讽刺东西太差或人缘太差，没人愿意接手。'},
    {front:'鐵公雞', back:'一毛不拔', jp:'tit3 gung1 gai1 — jat1 mou4 bat1 bat6', meaning:'极其吝啬。', story:'铁做的公鸡，毛都拔不下来。形容一毛不拔的守财奴。'},
    {front:'盲人點燈', back:'白費蠟', jp:'maang4 jan4 dim2 dang1 — baak6 fai3 laap6', meaning:'白费功夫。', story:'瞎子点灯，浪费蜡烛。比喻做了也没用、白折腾的事。'},
    {front:'黃皮樹了哥', back:'唔熟唔食', jp:'wong4 pei4 syu6 liu1 go1 — m4 suk6 m4 sik6', meaning:'专坑熟人。', story:'黄皮树上的八哥专挑熟的果子吃，谐音"唔熟唔食"——专挑熟识的人下手。'},
    {front:'阿茂整餅', back:'冇嗰樣整嗰樣', jp:'aa3 mau6 zing2 beng2 — mou5 go2 joeng6 zing2 go2 joeng6', meaning:'多管闲事、没事找事。', story:'阿茂做饼，缺哪样就做哪样，后来引申为没那样偏做那样，多此一举。'},  ],
  life: [
    {title:'茶餐厅：丝袜奶茶与暗语', tag:'饮食', desc:'丝袜奶茶、鸳鸯、飞冰、走糖、多士……茶餐厅有自己的语言系统。', story:'茶餐厅是香港的"平民食堂"：奶茶用丝袜滤网反复撞茶，香浓顺滑；"飞冰"=不要冰块，"走糖"=不加糖。点一份"常餐"（套餐），就是最地道的港式体验。'},
    {title:'叮叮车：百年电车', tag:'交通', desc:'1904年开到今天的香港电车，因"叮叮"的铃声得名。', story:'沿着港岛北岸缓缓穿行的双层电车，是香港最便宜的观光方式。坐上层前排，吹着海风看街景，是本地人的怀旧仪式。'},
    {title:'大排档：街头镬气', tag:'饮食', desc:'街头小炒摊档，讲究大火快炒的"镬气"。', story:'铁锅猛火，油星四溅，一碟干炒牛河端上来还冒着烟——这就是大排档的魅力。可惜如今传统大排档越来越少，能吃到的都是情怀。'},
    {title:'凉茶铺：苦口良药', tag:'生活', desc:'廿四味、龟苓膏、五花茶，一碗苦茶治百病。', story:'广东人信"苦口良药"：廿四味用二十四种草药熬制，苦到皱眉，却是降火神器。以前街头凉茶铺挂个铜葫芦，就是招牌。'},
    {title:'鹅颈桥打小人', tag:'习俗', desc:'惊蛰日到鹅颈桥，把小人踩在脚下。', story:'每年惊蛰，湾仔鹅颈桥下就热闹起来：阿婆用拖鞋狠狠拍打纸扎小人，口中念念有词，把霉运统统赶走。这是香港最"出圈"的民间习俗之一。'},
    {title:'盆菜：围村大宴', tag:'习俗', desc:'新界围村的传统菜式，一层层堆满好意头。', story:'一个大木盆，由下而上堆着萝卜、猪肉、鸡、鱼、蚝豉，寓意"盆满钵满"。逢年过节，全村围坐一桌，一盆菜吃出团圆味。'},
    {title:'霓虹灯：不夜城的名片', tag:'城市', desc:'密密匝匝的霓虹招牌，曾是香港夜景的标志。', story:'"东方之珠"的夜景，一半靠维港灯光，一半靠街角招牌。如今传统霓虹渐被LED取代，但霓虹仍是香港留给世界的文化符号。'},
    {title:'「一盅两件」叹世界', tag:'饮食', desc:'一壶茶、两件点心，慢慢叹（享受）。', story:'"叹茶"的"叹"是享受的意思。清晨茶楼里，老伯看报，阿婆倾偈，一盅两件可以坐一上午——这种慢，是香港另一种节奏。'},
    {title:'烧腊铺：斩料加餸', tag:'饮食', desc:'叉烧、烧鹅、白切鸡，买回家"加餸"（加菜）。', story:'"斩料"=到烧腊铺买熟食。家里来客或想加菜就去斩料：烧鹅配姜蓉、叉烧配蜜汁，肥瘦相间一口满足。'},
    {title:'天星小轮：维港百年渡轮', tag:'交通', desc:'往返尖沙咀与中环的百年渡轮。', story:'1888年启航的天星小轮，是维港最便宜的渡海方式。上层吹海风看两岸摩天楼，下层听轮机声看浪花，两种风景两种心情。'},
    {title:'鸭寮街：淘货圣地', tag:'城市', desc:'深水埗的电子零件与二手市场。', story:'鸭寮街是深水埗的露天市集：二手相机、电子零件、古董、唱片……懂行的人能淘到宝，是港片里市井气最浓的街道之一。'},
    {title:'兰桂坊：夜色与微醺', tag:'城市', desc:'中环后街的酒吧一条街。', story:'白天是中环写字楼的后巷，入夜变成霓虹闪烁的酒吧街。万圣节、圣诞夜人潮涌涌，是香港夜生活的代名词。'},
    {title:'幻彩咏香江：维港灯光秀', tag:'城市', desc:'每晚八点的维港灯光音乐汇演。', story:'每晚8点，维港两岸40多座大厦同步亮起灯光音乐秀，游客与本地人一起在星光大道看这幕城市灯光剧。'},
    {title:'大坑舞火龙：中秋习俗', tag:'习俗', desc:'大坑村中秋舞火龙驱瘟疫。', story:'中秋前后，大坑村上百人舞动插满线香的火龙穿街过巷，源自百年前驱除瘟疫的传说，现已是国家级非遗。'},  ],

  festival: [
    {han:'派利是', jp:'paai3 lai6 si6', meaning:'新年派红包，寓意大吉大利。', story:'"利是"=红包，已婚人士给未婚者派，图个好意头。"利利是是"=顺顺利利。'},
    {han:'行花街', jp:'haang4 faa1 gaai1', meaning:'除夕夜逛年宵花市，买年花迎新春。', story:'"年卅晚，行花街"——金桔、桃花、水仙，买一盆好意头回家。花市开到凌晨，人头攒动是广府共同的年味。'},
    {han:'食團年飯', jp:'sik6 tyun4 nin4 faan6', meaning:'除夕全家围炉，年年有"余"。', story:'团年饭必有鱼（年年有余）、鸡（有计）、发菜蚝豉（发财好市），一家大小齐齐整整，是全年最重要的一餐。'},
    {han:'睇龍舟', jp:'tai2 lung4 zau1', meaning:'端午赛龙舟，鼓声震天。', story:'端午前后，从赤柱到大澳都有龙舟赛。龙舟手跟着鼓点齐桨，岸上观众呐喊助威，"扒龙舟"是端午重头戏。'},
    {han:'食粽子', jp:'sik6 zung2 zi2', meaning:'咸甜粽之争，港式粽偏爱咸。', story:'港式粽以咸肉粽为主：糯米包着咸蛋黄、五花肉、冬菇、瑶柱，蒸足几小时，拆开粽叶香气扑鼻。'},
    {han:'做冬', jp:'zou6 dung1', meaning:'冬至大过年，全家做冬。', story:'广东人重视冬至，认为"冬大过年"。当晚全家围炉打边炉（火锅），寓意团圆温暖。'},
    {han:'盂蘭燒衣', jp:'jyu4 laan4 siu1 ji1', meaning:'农历七月，街头烧衣祭祖。', story:'农历七月是"鬼月"，街头巷尾可见烧衣纸、祭幽魂，戏棚上演神功戏，是岭南独特的民间信仰景观。'},
    {han:'食盆菜', jp:'sik6 pun4 coi3', meaning:'围村大盆菜，盆满钵满。', story:'新界围村过年过节食盆菜：一盆层层叠叠的菜，由上而下寓意"盆满钵满"，全村同吃一盆，吃的是热闹与团圆。'},
  ],
  food: [
    {title:'雞蛋仔', tag:'街头小食', desc:'外脆内软的蜂巢状小食。', story:'蛋浆倒进蜂巢状铁模现烤，出炉外脆内软、蛋香扑鼻。趁热掰开，一口一个圆球，是港片里出镜率最高的小食。'},
    {title:'格仔餅', tag:'街头小食', desc:'夹着炼乳花生的格子饼。', story:'和鸡蛋仔同源的格子形华夫饼，趁热涂牛油、炼乳、花生酱，咬下去外脆内糯，甜到心头。'},
    {title:'咖喱魚蛋', tag:'街头小食', desc:'弹牙鱼蛋配浓咖喱汁。', story:'鱼蛋先炸后浸咖喱汁，竹签一串边走边吃，是便利店和街头档的招牌，电影《重庆森林》里就有它。'},
    {title:'碗仔翅', tag:'街头小食', desc:'平民版"鱼翅羹"。', story:'用粉丝、冬菇、肉丝仿鱼翅熬成的羹，加浙醋、麻油、胡椒粉，几蚊一碗，是"贫民鱼翅"的智慧。'},
    {title:'魚蛋粉', tag:'街头小食', desc:'鱼蛋河粉加紫菜。', story:'汤清味鲜：鱼蛋弹牙、鱼片嫩滑，配河粉和紫菜，撒葱花，是港人早餐和宵夜的心头好。'},
    {title:'燒賣', tag:'街头小食', desc:'鱼蓉烧卖，点心档常客。', story:'港式烧卖以鱼肉为主料，弹牙鲜美，配辣油更好吃。茶楼一盅两件里有它，街头小食档也有它。'},
    {title:'砵仔糕', tag:'街头小食', desc:'红糖钵仔糕，用竹签挑着吃。', story:'用粘米粉和红糖蒸成，口感Q弹，用竹签沿边挑起，经典吃法是中间戳个洞。传统口味有红豆和白糖两种。'},
    {title:'車仔麵', tag:'街头小食', desc:'自选配料的自由组合面。', story:'以前流动摊档推着车卖面，客人自选鱼蛋、猪皮、萝卜、牛腩等配料，自由组合，一碗面吃出几十种搭配。'},
  ],
  tvb: [
    {han:'做人最緊要開心', jp:'zou6 jan4 zeoi3 gan2 jiu3 hoi1 sam1', meaning:'做人最重要开心。', story:'《溏心风暴》等剧集高频台词，成为港剧"人生哲理"的代表，也是网上最火的粤语梗之一。'},
    {han:'你講乜嘢呀', jp:'nei5 gong2 mat1 je5 aa3', meaning:'你说什么呀。', story:'港剧里表达惊讶或疑惑的万能句，语气不同意思不同：可以是疑问，也可以是吐槽。'},
    {han:'有冇搞錯呀', jp:'jau5 mou5 gaau2 co3 aa3', meaning:'有没有搞错。', story:'表达不满或无语的经典台词，配上"瞪眼"表情，是TVB演员的标配表演。'},
    {han:'唔係掛', jp:'m4 hai6 gwaa3', meaning:'不会吧。', story:'听到难以置信的事时的反应，"挂"是语气词，拖长音效果更佳，网络上常写作"唔系呱"。'},
    {han:'講呢啲', jp:'gong2 ni1 di1', meaning:'说这些（见外了）。', story:'《使徒行者》后爆火的金句："讲呢啲"表面是"说这些干嘛"，实际是"咱们谁跟谁，别客气"。'},
    {han:'世界變晒啦', jp:'sai3 gaai3 bin3 saai3 laa1', meaning:'世界变完了/世道变了。', story:'长辈感叹时代变化的常用语，带点无奈和幽默，是港剧"老戏骨"的经典台词。'},
  ],
}
};
