/* ============================================================
   粵學堂 · 学习内容数据
   粤拼（Jyutping）标注，数字 1-6 为声调
   ============================================================ */

const DATA = {

/* ---------- 1. 语音系统 ---------- */
initials: [
  {sym:'b', jp:'b', ex:'巴', exjp:'baa1', note:'双唇不送气清塞音'},
  {sym:'p', jp:'p', ex:'怕', exjp:'paa3', note:'双唇送气清塞音'},
  {sym:'m', jp:'m', ex:'媽', exjp:'maa1', note:'双唇鼻音'},
  {sym:'f', jp:'f', ex:'花', exjp:'faa1', note:'唇齿清擦音'},
  {sym:'d', jp:'d', ex:'打', exjp:'daa2', note:'舌尖不送气清塞音'},
  {sym:'t', jp:'t', ex:'他', exjp:'taa1', note:'舌尖送气清塞音'},
  {sym:'n', jp:'n', ex:'那', exjp:'naa5', note:'舌尖鼻音'},
  {sym:'l', jp:'l', ex:'啦', exjp:'laa1', note:'舌尖边音'},
  {sym:'g', jp:'g', ex:'家', exjp:'gaa1', note:'舌根不送气清塞音'},
  {sym:'k', jp:'k', ex:'卡', exjp:'kaa1', note:'舌根送气清塞音'},
  {sym:'ng', jp:'ng', ex:'牙', exjp:'ngaa4', note:'舌根鼻音'},
  {sym:'h', jp:'h', ex:'蝦', exjp:'haa1', note:'喉清擦音'},
  {sym:'gw', jp:'gw', ex:'瓜', exjp:'gwaa1', note:'圆唇舌根不送气'},
  {sym:'kw', jp:'kw', ex:'誇', exjp:'kwaa1', note:'圆唇舌根送气'},
  {sym:'w', jp:'w', ex:'蛙', exjp:'waa1', note:'圆唇半元音'},
  {sym:'z', jp:'z', ex:'渣', exjp:'zaa1', note:'舌尖不送气塞擦音'},
  {sym:'c', jp:'c', ex:'叉', exjp:'caa1', note:'舌尖送气塞擦音'},
  {sym:'s', jp:'s', ex:'沙', exjp:'saa1', note:'舌尖清擦音'},
  {sym:'j', jp:'j', ex:'也', exjp:'jaa5', note:'硬颚半元音'},
],

finals: [
  {sym:'aa', ex:'花 / 爸', exjp:'faa1 / baa1', grp:'a 系'},
  {sym:'aai', ex:'街', exjp:'gaai1', grp:'a 系'},
  {sym:'aau', ex:'咬', exjp:'ngaau5', grp:'a 系'},
  {sym:'aam', ex:'衫', exjp:'saam1', grp:'a 系'},
  {sym:'aan', ex:'山', exjp:'saan1', grp:'a 系'},
  {sym:'aang', ex:'行（口语）', exjp:'haang4', grp:'a 系'},
  {sym:'aap', ex:'鴨', exjp:'aap3', grp:'a 系 · 入声'},
  {sym:'aat', ex:'八', exjp:'baat3', grp:'a 系 · 入声'},
  {sym:'aak', ex:'百', exjp:'baak3', grp:'a 系 · 入声'},
  {sym:'ai', ex:'雞', exjp:'gai1', grp:'a 系'},
  {sym:'au', ex:'牛', exjp:'ngau4', grp:'a 系'},
  {sym:'am', ex:'心', exjp:'sam1', grp:'a 系'},
  {sym:'an', ex:'新', exjp:'san1', grp:'a 系'},
  {sym:'ang', ex:'生', exjp:'sang1', grp:'a 系'},
  {sym:'ap', ex:'十', exjp:'sap6', grp:'a 系 · 入声'},
  {sym:'at', ex:'一', exjp:'jat1', grp:'a 系 · 入声'},
  {sym:'ak', ex:'北', exjp:'bak1', grp:'a 系 · 入声'},
  {sym:'e', ex:'車', exjp:'ce1', grp:'e 系'},
  {sym:'ei', ex:'你', exjp:'nei5', grp:'e 系'},
  {sym:'eu', ex:'掉（口语）', exjp:'deu6', grp:'e 系'},
  {sym:'em', ex:'舔（口语）', exjp:'lem2', grp:'e 系'},
  {sym:'eng', ex:'贏', exjp:'jeng4', grp:'e 系'},
  {sym:'ep', ex:'夾（口语）', exjp:'gep6', grp:'e 系 · 入声'},
  {sym:'ek', ex:'石', exjp:'sek6', grp:'e 系 · 入声'},
  {sym:'eoi', ex:'水', exjp:'seoi2', grp:'eo 系'},
  {sym:'eon', ex:'春', exjp:'ceon1', grp:'eo 系'},
  {sym:'eong', ex:'雙', exjp:'soeng1', grp:'eo 系'},
  {sym:'eot', ex:'出', exjp:'ceot1', grp:'eo 系 · 入声'},
  {sym:'eok', ex:'削', exjp:'soek3', grp:'eo 系 · 入声'},
  {sym:'i', ex:'詩', exjp:'si1', grp:'i 系'},
  {sym:'iu', ex:'笑', exjp:'siu3', grp:'i 系'},
  {sym:'im', ex:'點', exjp:'dim2', grp:'i 系'},
  {sym:'in', ex:'天', exjp:'tin1', grp:'i 系'},
  {sym:'ing', ex:'聽', exjp:'ting1', grp:'i 系'},
  {sym:'ip', ex:'碟', exjp:'dip6', grp:'i 系 · 入声'},
  {sym:'it', ex:'熱', exjp:'jit6', grp:'i 系 · 入声'},
  {sym:'ik', ex:'食', exjp:'sik6', grp:'i 系 · 入声'},
  {sym:'o', ex:'火', exjp:'fo2', grp:'o 系'},
  {sym:'oi', ex:'菜', exjp:'coi3', grp:'o 系'},
  {sym:'ou', ex:'好', exjp:'hou2', grp:'o 系'},
  {sym:'on', ex:'乾', exjp:'gon1', grp:'o 系'},
  {sym:'ong', ex:'糖', exjp:'tong4', grp:'o 系'},
  {sym:'ot', ex:'渴', exjp:'hot3', grp:'o 系 · 入声'},
  {sym:'ok', ex:'落', exjp:'lok6', grp:'o 系 · 入声'},
  {sym:'u', ex:'夫', exjp:'fu1', grp:'u 系'},
  {sym:'ui', ex:'杯', exjp:'bui1', grp:'u 系'},
  {sym:'un', ex:'盤', exjp:'pun4', grp:'u 系'},
  {sym:'ung', ex:'東', exjp:'dung1', grp:'u 系'},
  {sym:'ut', ex:'闊', exjp:'fut3', grp:'u 系 · 入声'},
  {sym:'uk', ex:'屋', exjp:'uk1', grp:'u 系 · 入声'},
  {sym:'yu', ex:'書', exjp:'syu1', grp:'yu 系'},
  {sym:'yun', ex:'圈', exjp:'hyun1', grp:'yu 系'},
  {sym:'yut', ex:'月', exjp:'jyut6', grp:'yu 系 · 入声'},
  {sym:'m', ex:'唔', exjp:'m4', grp:'鼻音韵（自成音节）'},
  {sym:'ng', ex:'五', exjp:'ng5', grp:'鼻音韵（自成音节）'},
],

tones: [
  {num:'1', name:'阴平', contour:'55', desc:'高平：声音平而高，像唱歌定音', ex:'詩', exjp:'si1', ex2:'衣', ex2jp:'ji1'},
  {num:'2', name:'阴上', contour:'35', desc:'高升：由中音升到高音，像疑问上扬', ex:'史', exjp:'si2', ex2:'椅', ex2jp:'ji2'},
  {num:'3', name:'阴去', contour:'33', desc:'中平：不高不低，平直输出', ex:'試', exjp:'si3', ex2:'意', ex2jp:'ji3'},
  {num:'4', name:'阳平', contour:'21', desc:'低降：从低再往下降，低沉', ex:'時', exjp:'si4', ex2:'移', ex2jp:'ji4'},
  {num:'5', name:'阳上', contour:'13', desc:'低升：从最低升起来，像问"嗯？"', ex:'市', exjp:'si5', ex2:'耳', ex2jp:'ji5'},
  {num:'6', name:'阳去', contour:'22', desc:'低平：比第3声低，平直', ex:'事', exjp:'si6', ex2:'二', ex2jp:'ji6'},
  {num:'7', name:'上入', contour:'1', desc:'入声·高：韵尾 -p/-t/-k，短促收尾', ex:'色', exjp:'sik1', ex2:'一', ex2jp:'jat1'},
  {num:'8', name:'中入', contour:'3', desc:'入声·中：短促收尾，高度同第3声', ex:'錫', exjp:'sik3', ex2:'八', ex2jp:'baat3'},
  {num:'9', name:'下入', contour:'6', desc:'入声·低：短促收尾，高度同第6声', ex:'食', exjp:'sik6', ex2:'月', ex2jp:'jyut6'},
],

/* ---------- 2. 场景词汇 ---------- */
vocabCategories: [
{
  id:'food', name:'饮食', icon:'🍜', words:[
    {han:'饮茶', jp:'jam2 caa4', mand:'喝早茶', ex:'我哋听日去饮茶。', exjp:'ngo5 dei6 ting1 jat6 heoi3 jam2 caa4.', exmand:'我们明天去喝早茶。'},
    {han:'虾饺', jp:'haa1 gaau2', mand:'虾饺', ex:'虾饺好鲜。', exjp:'haa1 gaau2 hou2 sin1.', exmand:'虾饺很鲜美。'},
    {han:'烧卖', jp:'siu1 maai2', mand:'烧麦', ex:'一笼烧卖几钱？', exjp:'jat1 lung4 siu1 maai2 gei2 cin2?', exmand:'一笼烧麦多少钱？'},
    {han:'蛋挞', jp:'daan6 taat1', mand:'蛋挞', ex:'新鲜出炉嘅蛋挞。', exjp:'san1 sin1 ceot1 lou2 ge3 daan6 taat1.', exmand:'新鲜出炉的蛋挞。'},
    {han:'云吞面', jp:'wan4 tan1 min6', mand:'馄饨面', ex:'我食云吞面，唔该。', exjp:'ngo5 sik6 wan4 tan1 min6, m4 goi1.', exmand:'我要馄饨面，谢谢。'},
    {han:'煲仔饭', jp:'bou1 zai2 faan6', mand:'煲仔饭', ex:'煲仔饭要等十五分钟。', exjp:'bou1 zai2 faan6 jiu3 dang2 sap6 ng5 fan1 zung1.', exmand:'煲仔饭要等十五分钟。'},
    {han:'叉烧', jp:'caa1 siu1', mand:'叉烧', ex:'叉烧饭加例汤。', exjp:'caa1 siu1 faan6 gaa1 lai6 tong1.', exmand:'叉烧饭加例汤。'},
    {han:'奶茶', jp:'naai5 caa4', mand:'奶茶', ex:'奶茶飞冰，唔该。', exjp:'naai5 caa4 fei1 bing1, m4 goi1.', exmand:'奶茶不加冰，谢谢。'},
    {han:'菠萝油', jp:'bo1 lo4 jau2', mand:'菠萝油', ex:'菠萝油配冻柠茶一流。', exjp:'bo1 lo4 jau2 pui3 dung3 ning2 caa4 jat1 lau4.', exmand:'菠萝油配冻柠檬茶一流。'},
    {han:'肠粉', jp:'coeng2 fan2', mand:'肠粉', ex:'斋肠粉落豉油。', exjp:'zaai1 coeng2 fan2 lok6 si6 jau4.', exmand:'斋肠粉加酱油。'},
    {han:'白粥', jp:'baak6 zuk1', mand:'白粥', ex:'病咗饮白粥好啲。', exjp:'beng6 zo2 jam2 baak6 zuk1 hou2 di1.', exmand:'生病了喝白粥好一些。'},
    {han:'大排档', jp:'daai6 paai4 dong3', mand:'大排档', ex:'大排档啲镬气十足。', exjp:'daai6 paai4 dong3 di1 wok6 hei3 sap6 zuk1.', exmand:'大排档的锅气很足。'},
  ]},
{
  id:'transport', name:'交通', icon:'🚌', words:[
    {han:'巴士', jp:'baa1 si2', mand:'公交车', ex:'我搭巴士返工。', exjp:'ngo5 daap3 baa1 si2 faan1 gung1.', exmand:'我坐公交上班。'},
    {han:'地铁', jp:'dei6 tit3', mand:'地铁', ex:'坐地铁最快。', exjp:'co5 dei6 tit3 zeoi3 faai3.', exmand:'坐地铁最快。'},
    {han:'的士', jp:'dik1 si2', mand:'出租车', ex:'帮我截架的士。', exjp:'bong1 ngo5 zit6 gaa3 dik1 si2.', exmand:'帮我拦辆出租车。'},
    {han:'小巴', jp:'siu2 baa1', mand:'小巴', ex:'小巴冇位就唔上。', exjp:'siu2 baa1 mou5 wai2 zau6 m4 soeng5.', exmand:'小巴没座位就不上。'},
    {han:'电车', jp:'din6 ce1', mand:'叮叮车', ex:'电车慢行睇风景。', exjp:'din6 ce1 maan6 haang4 tai2 fung1 ging2.', exmand:'叮叮车慢行看风景。'},
    {han:'渡轮', jp:'dou6 leon4', mand:'渡轮', ex:'坐渡轮过海睇维港。', exjp:'co5 dou6 leon4 gwo3 hoi2 tai2 wai4 gong2.', exmand:'坐渡轮过海看维港。'},
    {han:'红绿灯', jp:'hung4 luk6 dang1', mand:'红绿灯', ex:'红绿灯转咗。', exjp:'hung4 luk6 dang1 zyun3 zo2.', exmand:'红绿灯变了。'},
    {han:'上车', jp:'soeng5 ce1', mand:'上车', ex:'唔该，我哋上车先。', exjp:'m4 goi1, ngo5 dei6 soeng5 ce1 sin1.', exmand:'不好意思，我们先上车。'},
    {han:'落车', jp:'lok6 ce1', mand:'下车', ex:'我下一站落车。', exjp:'ngo5 haa6 jat1 zaam6 lok6 ce1.', exmand:'我下一站下车。'},
    {han:'转车', jp:'zyun3 ce1', mand:'换乘', ex:'金钟要转车。', exjp:'gam1 zung1 jiu3 zyun3 ce1.', exmand:'金钟要换乘。'},
    {han:'八达通', jp:'baat3 daat6 tung1', mand:'八达通卡', ex:'八达通嘟一嘟就得。', exjp:'baat3 daat6 tung1 duk1 jat1 duk1 zau6 dak1.', exmand:'八达通刷一下就行。'},
    {han:'车站', jp:'ce1 zaam6', mand:'车站', ex:'我喺车站等你。', exjp:'ngo5 hai2 ce1 zaam6 dang2 nei5.', exmand:'我在车站等你。'},
  ]},
{
  id:'shopping', name:'购物', icon:'🛍️', words:[
    {han:'买嘢', jp:'maai5 je5', mand:'买东西', ex:'我出去买嘢。', exjp:'ngo5 ceot1 heoi3 maai5 je5.', exmand:'我出去买东西。'},
    {han:'平价', jp:'peng4 gaa3', mand:'便宜', ex:'呢度啲嘢好平价。', exjp:'ni1 dou6 di1 je5 hou2 peng4 gaa3.', exmand:'这里的东西很便宜。'},
    {han:'贵', jp:'gwai3', mand:'贵', ex:'太贵啦，平啲啦。', exjp:'taai3 gwai3 laa1, peng4 di1 laa1.', exmand:'太贵了，便宜点吧。'},
    {han:'减价', jp:'gaam2 gaa3', mand:'降价', ex:'大减价，买二送一。', exjp:'daai6 gaam2 gaa3, maai5 ji6 sung3 jat1.', exmand:'大减价，买二送一。'},
    {han:'收银处', jp:'sau1 ngan4 cyu5', mand:'收银台', ex:'去收银处埋单。', exjp:'heoi3 sau1 ngan4 cyu5 maai4 daan1.', exmand:'去收银台结账。'},
    {han:'袋', jp:'doi6', mand:'袋子', ex:'唔该畀个胶袋我。', exjp:'m4 goi1 bei2 go3 gaau1 doi6 ngo5.', exmand:'请给我一个塑料袋。'},
    {han:'找钱', jp:'zaau2 cin2', mand:'找零', ex:'唔使找钱喇。', exjp:'m4 sai2 zaau2 cin2 laa3.', exmand:'不用找零了。'},
    {han:'试身', jp:'si3 san1', mand:'试穿', ex:'呢件可以试身吗？', exjp:'ni1 gin6 ho2 ji5 si3 san1 maa1?', exmand:'这件可以试穿吗？'},
    {han:'尺寸', jp:'cek3 cyun3', mand:'尺寸', ex:'有冇大一个码？', exjp:'jau5 mou5 daai6 jat1 go3 maa5?', exmand:'有没有大一码？'},
    {han:'现金', jp:'jin6 gam1', mand:'现金', ex:'用现金定八达通？', exjp:'jung6 jin6 gam1 ding6 baat3 daat6 tung1?', exmand:'用现金还是八达通？'},
    {han:'信用卡', jp:'seon3 jung6 kaat1', mand:'信用卡', ex:'信用卡埋单，多谢。', exjp:'seon3 jung6 kaat1 maai4 daan1, do1 ze6.', exmand:'信用卡结账，谢谢。'},
    {han:'打折', jp:'daa2 zit3', mand:'打折', ex:'依家打七折。', exjp:'ji1 gaa1 daa2 cat1 zit3.', exmand:'现在打七折。'},
  ]},
{
  id:'social', name:'社交', icon:'🙋', words:[
    {han:'你好', jp:'nei5 hou2', mand:'你好', ex:'你好，我系小明。', exjp:'nei5 hou2, ngo5 hai6 siu2 ming4.', exmand:'你好，我是小明。'},
    {han:'早晨', jp:'zou2 san4', mand:'早上好', ex:'早晨，饮咗茶未？', exjp:'zou2 san4, jam2 zo2 caa4 mei6?', exmand:'早上好，喝过早茶了吗？'},
    {han:'唔该', jp:'m4 goi1', mand:'谢谢 / 劳驾', ex:'唔该晒！', exjp:'m4 goi1 saai3!', exmand:'太感谢了！'},
    {han:'多谢', jp:'do1 ze6', mand:'谢谢（受赠）', ex:'多谢你帮我。', exjp:'do1 ze6 nei5 bong1 ngo5.', exmand:'谢谢你帮我。'},
    {han:'对唔住', jp:'deoi3 m4 zyu6', mand:'对不起', ex:'对唔住，我迟到咗。', exjp:'deoi3 m4 zyu6, ngo5 ci4 dou3 zo2.', exmand:'对不起，我迟到了。'},
    {han:'再见', jp:'zoi3 gin3', mand:'再见', ex:'再见，下次见。', exjp:'zoi3 gin3, haa6 ci3 gin3.', exmand:'再见，下次见。'},
    {han:'系呀', jp:'hai6 aa3', mand:'是的', ex:'系呀，我系香港人。', exjp:'hai6 aa3, ngo5 hai6 hoeng1 gong2 jan4.', exmand:'是的，我是香港人。'},
    {han:'唔系', jp:'m4 hai6', mand:'不是', ex:'唔系，你认错人喇。', exjp:'m4 hai6, nei5 jing6 co3 jan4 laa3.', exmand:'不是，你认错人了。'},
    {han:'倾偈', jp:'king1 gai2', mand:'聊天', ex:'得闲过嚟倾偈。', exjp:'dak1 haan4 gwo3 lai4 king1 gai2.', exmand:'有空过来聊天。'},
    {han:'得闲', jp:'dak1 haan4', mand:'有空', ex:'你得闲吗？', exjp:'nei5 dak1 haan4 maa1?', exmand:'你有空吗？'},
    {han:'恭喜', jp:'gung1 hei2', mand:'恭喜', ex:'恭喜发财！', exjp:'gung1 hei2 faat3 coi4!', exmand:'恭喜发财！'},
    {han:'几好', jp:'gei2 hou2', mand:'挺好', ex:'最近点呀？几好呀。', exjp:'zeoi3 gan6 dim2 aa3? gei2 hou2 aa3.', exmand:'最近怎么样？挺好的。'},
  ]},
{
  id:'family', name:'家庭', icon:'👨‍👩‍👧', words:[
    {han:'老豆', jp:'lou5 dau6', mand:'爸爸', ex:'我老豆好中意饮茶。', exjp:'ngo5 lou5 dau6 hou2 zung1 ji3 jam2 caa4.', exmand:'我爸爸很喜欢喝早茶。'},
    {han:'阿妈', jp:'aa3 maa1', mand:'妈妈', ex:'阿妈煮饭好好食。', exjp:'aa3 maa1 zyu2 faan6 hou2 hou2 sik6.', exmand:'妈妈做饭很好吃。'},
    {han:'阿哥', jp:'aa3 go1', mand:'哥哥', ex:'我阿哥喺银行做嘢。', exjp:'ngo5 aa3 go1 hai2 ngan4 hong4 zou6 je5.', exmand:'我哥哥在银行工作。'},
    {han:'家姐', jp:'gaa1 ze1', mand:'姐姐', ex:'家姐教我讲粤语。', exjp:'gaa1 ze1 gaau3 ngo5 gong2 jyut6 jyu5.', exmand:'姐姐教我讲粤语。'},
    {han:'细佬', jp:'sai3 lou2', mand:'弟弟', ex:'细佬成日打机。', exjp:'sai3 lou2 seng4 jat6 daa2 gei1.', exmand:'弟弟整天打游戏。'},
    {han:'细妹', jp:'sai3 mui6', mand:'妹妹', ex:'细妹好锡我。', exjp:'sai3 mui6 hou2 sek3 ngo5.', exmand:'妹妹很疼我。'},
    {han:'阿爷', jp:'aa3 je4', mand:'爷爷', ex:'阿爷朝早去晨运。', exjp:'aa3 je4 ziu1 zou2 heoi3 san4 wan6.', exmand:'爷爷早上晨练。'},
    {han:'阿嫲', jp:'aa3 maa4', mand:'奶奶', ex:'阿嫲讲古仔好叻。', exjp:'aa3 maa4 gong2 gu2 zai2 hou2 lek1.', exmand:'奶奶很会讲故事。'},
    {han:'老婆', jp:'lou5 po4', mand:'老婆', ex:'我老婆系老师。', exjp:'ngo5 lou5 po4 hai6 lou5 si1.', exmand:'我老婆是老师。'},
    {han:'老公', jp:'lou5 gung1', mand:'老公', ex:'我老公煮嘢好叻。', exjp:'ngo5 lou5 gung1 zyu2 je5 hou2 lek1.', exmand:'我老公很会做饭。'},
    {han:'仔', jp:'zai2', mand:'儿子', ex:'我个仔读小学。', exjp:'ngo5 go3 zai2 duk6 siu2 hok6.', exmand:'我儿子上小学。'},
    {han:'女', jp:'neoi5', mand:'女儿', ex:'我个女好乖。', exjp:'ngo5 go3 neoi5 hou2 gwaai1.', exmand:'我女儿很乖。'},
  ]},
{
  id:'weather', name:'天气', icon:'🌧️', words:[
    {han:'天气', jp:'tin1 hei3', mand:'天气', ex:'今日天气好好。', exjp:'gam1 jat6 tin1 hei3 hou2 hou2.', exmand:'今天天气很好。'},
    {han:'落雨', jp:'lok6 jyu5', mand:'下雨', ex:'落雨记得带遮。', exjp:'lok6 jyu5 gei3 dak1 daai3 ze1.', exmand:'下雨记得带伞。'},
    {han:'打风', jp:'daa2 fung1', mand:'台风来袭', ex:'听日打风，唔使返工。', exjp:'ting1 jat6 daa2 fung1, m4 sai2 faan1 gung1.', exmand:'明天台风，不用上班。'},
    {han:'热', jp:'jit6', mand:'热', ex:'今日热到飞起。', exjp:'gam1 jat6 jit6 dou3 fei1 hei2.', exmand:'今天热得不行。'},
    {han:'冻', jp:'dung3', mand:'冷', ex:'好冻，着多件衫。', exjp:'hou2 dung3, zoek3 do1 gin6 saam1.', exmand:'很冷，多穿件衣服。'},
    {han:'潮湿', jp:'ciu4 sap1', mand:'潮湿', ex:'春天好潮湿。', exjp:'ceon1 tin1 hou2 ciu4 sap1.', exmand:'春天很潮湿。'},
    {han:'晴朗', jp:'cing4 long5', mand:'晴朗', ex:'天朗气清，去行山。', exjp:'tin1 long5 hei3 cing1, heoi3 haang4 saan1.', exmand:'天朗气清，去爬山。'},
    {han:'阴天', jp:'jam1 tin1', mand:'阴天', ex:'阴天冇太阳，好舒服。', exjp:'jam1 tin1 mou5 taai3 joeng4, hou2 syu1 fuk6.', exmand:'阴天没太阳，很舒服。'},
    {han:'打雷', jp:'daa2 leoi4', mand:'打雷', ex:'打雷落大雨。', exjp:'daa2 leoi4 lok6 daai6 jyu5.', exmand:'打雷下大雨。'},
    {han:'彩虹', jp:'coi2 hung4', mand:'彩虹', ex:'雨后有彩虹。', exjp:'jyu5 hau6 jau5 coi2 hung4.', exmand:'雨后出彩虹。'},
  ]},
{
  id:'time', name:'时间', icon:'🕐', words:[
    {han:'而家', jp:'ji4 gaa1', mand:'现在', ex:'而家几点？', exjp:'ji4 gaa1 gei2 dim2?', exmand:'现在几点？'},
    {han:'今日', jp:'gam1 jat6', mand:'今天', ex:'今日系星期几？', exjp:'gam1 jat6 hai6 sing1 kei4 gei2?', exmand:'今天星期几？'},
    {han:'听日', jp:'ting1 jat6', mand:'明天', ex:'听日见。', exjp:'ting1 jat6 gin3.', exmand:'明天见。'},
    {han:'寻日', jp:'cam4 jat6', mand:'昨天', ex:'寻日去咗边？', exjp:'cam4 jat6 heoi3 zo2 bin1?', exmand:'昨天去哪儿了？'},
    {han:'朝早', jp:'ziu1 zou2', mand:'早上', ex:'朝早做运动。', exjp:'ziu1 zou2 zou6 wan6 dung6.', exmand:'早上做运动。'},
    {han:'晏昼', jp:'aan3 zau3', mand:'中午', ex:'晏昼食咩呀？', exjp:'aan3 zau3 sik6 me1 aa3?', exmand:'中午吃什么？'},
    {han:'下昼', jp:'haa6 zau3', mand:'下午', ex:'下昼三点开会。', exjp:'haa6 zau3 saam1 dim2 hoi1 wui2.', exmand:'下午三点开会。'},
    {han:'夜晚', jp:'je6 maan5', mand:'晚上', ex:'夜晚出去食饭。', exjp:'je6 maan5 ceot1 heoi3 sik6 faan6.', exmand:'晚上出去吃饭。'},
    {han:'几点', jp:'gei2 dim2', mand:'几点', ex:'你几点返到屋企？', exjp:'nei5 gei2 dim2 faan1 dou3 uk1 kei2?', exmand:'你几点回到家？'},
    {han:'一分钟', jp:'jat1 fan1 zung1', mand:'一分钟', ex:'等我一分钟。', exjp:'dang2 ngo5 jat1 fan1 zung1.', exmand:'等我一下。'},
    {han:'礼拜', jp:'lai5 baai3', mand:'星期', ex:'礼拜六去街。', exjp:'lai5 baai3 luk6 heoi3 gaai1.', exmand:'星期六逛街。'},
    {han:'依家', jp:'ji1 gaa1', mand:'现在（口语）', ex:'依家冇时间。', exjp:'ji1 gaa1 mou5 si4 gaan3.', exmand:'现在没时间。'},
  ]},
{
  id:'numbers', name:'数字', icon:'🔢', words:[
    {han:'一', jp:'jat1', mand:'一', ex:'我饮一杯奶茶。', exjp:'ngo5 jam2 jat1 bui1 naai5 caa4.', exmand:'我喝一杯奶茶。'},
    {han:'二', jp:'ji6', mand:'二', ex:'两个人食饭。（量词前多说"两"）', exjp:'loeng5 go3 jan4 sik6 faan6.', exmand:'两个人吃饭。'},
    {han:'三', jp:'saam1', mand:'三', ex:'三杯咖啡。', exjp:'saam1 bui1 gaa3 fe1.', exmand:'三杯咖啡。'},
    {han:'四', jp:'sei3', mand:'四', ex:'四张飞。（四谐"死"，港人避讳）', exjp:'sei3 zoeng1 fei1.', exmand:'四张票。'},
    {han:'五', jp:'ng5', mand:'五', ex:'五蚊一个。', exjp:'ng5 man1 jat1 go3.', exmand:'五块钱一个。'},
    {han:'六', jp:'luk6', mand:'六', ex:'六六大顺。', exjp:'luk6 luk6 daai6 seon6.', exmand:'六六大顺。'},
    {han:'七', jp:'cat1', mand:'七', ex:'七点钟起身。', exjp:'cat1 dim2 zung1 hei2 san1.', exmand:'七点起床。'},
    {han:'八', jp:'baat3', mand:'八', ex:'八蚊一支水。（八谐"发"）', exjp:'baat3 man1 jat1 zi1 seoi2.', exmand:'八块钱一瓶水。'},
    {han:'九', jp:'gau2', mand:'九', ex:'九点开会。', exjp:'gau2 dim2 hoi1 wui2.', exmand:'九点开会。'},
    {han:'十', jp:'sap6', mand:'十', ex:'十蚊找返两蚊。', exjp:'sap6 man1 zaau2 faan1 loeng5 man1.', exmand:'十块钱找两块。'},
    {han:'百', jp:'baak3', mand:'百', ex:'呢件衫要几百蚊。', exjp:'ni1 gin6 saam1 jiu3 gei2 baak3 man1.', exmand:'这件衣服要几百块。'},
    {han:'万', jp:'maan6', mand:'万', ex:'香港有七百几万人。', exjp:'hoeng1 gong2 jau5 cat1 baak3 gei2 maan6 jan4.', exmand:'香港有七百多万人。'},
  ]},
],

/* ---------- 3. 对话场景 ---------- */
dialogues: [
{
  id:'dimsum', title:'茶楼饮茶', emoji:'🍵', level:'初级', desc:'点心纸、点心车，坐低叹番一盅两件。', tags:['饮食','礼貌','点餐'], lines:[
    {speaker:'侍应', han:'早晨，几位呀？', jp:'zou2 san4, gei2 wai2 aa3?', mand:'早上好，几位呀？'},
    {speaker:'食客', han:'两位，唔该。', jp:'loeng5 wai2, m4 goi1.', mand:'两位，谢谢。'},
    {speaker:'侍应', han:'饮咩茶呀？', jp:'jam2 me1 caa4 aa3?', mand:'喝什么茶呀？'},
    {speaker:'食客', han:'普洱啦。', jp:'pou2 lei2 laa1.', mand:'普洱吧。'},
    {speaker:'侍应', han:'要啲咩点心？', jp:'jiu3 di1 me1 dim2 sam1?', mand:'要点什么点心？'},
    {speaker:'食客', han:'虾饺同烧卖，仲要一碟肠粉。', jp:'haa1 gaau2 tung4 siu1 maai2, zung6 jiu3 jat1 dip6 coeng2 fan2.', mand:'虾饺和烧麦，还要一碟肠粉。'},
    {speaker:'侍应', han:'好，唔该稍等。', jp:'hou2, m4 goi1 saau1 dang2.', mand:'好的，请稍等。'},
    {speaker:'食客', han:'唔该，埋单！', jp:'m4 goi1, maai4 daan1!', mand:'麻烦，买单！'},
    {speaker:'侍应', han:'盛惠八十八蚊。', jp:'sing6 wai6 baat3 sap6 baat3 man1.', mand:'一共八十八块。'},
  ]},
{
  id:'market', title:'街市买菜', emoji:'🥬', level:'初级', desc:'问价、讲价、称重，街市对话最生活化。', tags:['购物','砍价','食物'], lines:[
    {speaker:'档主', han:'早晨，想买啲咩呀？', jp:'zou2 san4, soeng2 maai5 di1 me1 aa3?', mand:'早上好，想买点什么呀？'},
    {speaker:'顾客', han:'呢啲菜新唔新鲜㗎？', jp:'ni1 di1 coi3 san1 m4 san1 sin1 gaa3?', mand:'这菜新鲜吗？'},
    {speaker:'档主', han:'好新鲜㗎，今朝先到。', jp:'hou2 san1 sin1 gaa3, gam1 ziu1 sin1 dou3.', mand:'很新鲜，今早刚到。'},
    {speaker:'顾客', han:'几钱一斤呀？', jp:'gei2 cin2 jat1 gan1 aa3?', mand:'多少钱一斤呀？'},
    {speaker:'档主', han:'十蚊一斤咋。', jp:'sap6 man1 jat1 gan1 zaa3.', mand:'才十块钱一斤。'},
    {speaker:'顾客', han:'咁平？畀两斤我啦。', jp:'gam3 peng4? bei2 loeng5 gan1 ngo5 laa1.', mand:'这么便宜？给我两斤吧。'},
    {speaker:'档主', han:'好，廿蚊。仲要唔要啲咩？', jp:'hou2, jaa6 man1. zung6 jiu3 m4 jiu3 di1 me1?', mand:'好，二十块。还要点别的吗？'},
    {speaker:'顾客', han:'唔使喇，唔该。', jp:'m4 sai2 laa3, m4 goi1.', mand:'不用了，谢谢。'},
    {speaker:'档主', han:'多谢，慢慢行！', jp:'do1 ze6, maan6 maan6 haang4!', mand:'谢谢，慢走！'},
  ]},
{
  id:'bus', title:'搭巴士', emoji:'🚌', level:'入门', desc:'问路线上车、拍八达通、报站落车。', tags:['交通','问询'], lines:[
    {speaker:'乘客', han:'唔该，呢架车去唔去中环㗎？', jp:'m4 goi1, ni1 gaa3 ce1 heoi3 m4 heoi3 zung1 waan4 gaa3?', mand:'请问，这趟车去不去中环呀？'},
    {speaker:'司机', han:'去，上嚟啦。', jp:'heoi3, soeng5 lai4 laa1.', mand:'去，上来吧。'},
    {speaker:'乘客', han:'唔该，八达通。', jp:'m4 goi1, baat3 daat6 tung1.', mand:'谢谢，刷八达通。'},
    {speaker:'司机', han:'得喇。', jp:'dak1 laa3.', mand:'行了。'},
    {speaker:'乘客', han:'司机，中环站系咪下一个站呀？', jp:'si1 gei1, zung1 waan4 zaam6 hai6 mai6 haa6 jat1 go3 zaam6 aa3?', mand:'司机，中环站是下一站吗？'},
    {speaker:'司机', han:'唔系，仲有一个站先到。', jp:'m4 hai6, zung6 jau5 jat1 go3 zaam6 sin1 dou3.', mand:'不是，还要一个站才到。'},
    {speaker:'乘客', han:'咁到咗话我知得唔得呀？', jp:'gam3 dou3 zo2 waa6 ngo5 zi1 dak1 m4 dak1 aa3?', mand:'那到了叫我一声行吗？'},
    {speaker:'司机', han:'冇问题。', jp:'mou5 man6 tai4.', mand:'没问题。'},
  ]},
{
  id:'chachaanteng', title:'茶餐厅落单', emoji:'🍛', level:'入门', desc:'常餐、冻饮加钱、飞冰走糖，港式快餐暗语。', tags:['饮食','点餐'], lines:[
    {speaker:'侍应', han:'食啲咩呀？', jp:'sik6 di1 me1 aa3?', mand:'吃点什么呀？'},
    {speaker:'顾客', han:'一个常餐，冻奶茶，飞冰。', jp:'jat1 go3 soeng4 caan1, dung3 naai5 caa4, fei1 bing1.', mand:'一个常餐，冻奶茶，去冰。'},
    {speaker:'侍应', han:'常餐跟餐饮，冻饮加两蚊喎。', jp:'soeng4 caan1 gan1 caan1 jam2, dung3 jam2 gaa1 loeng5 man1 wo3.', mand:'常餐含饮品，冻饮要加两块钱哦。'},
    {speaker:'顾客', han:'冇所谓，照要。', jp:'mou5 so2 wai6, ziu3 jiu3.', mand:'没关系，照要。'},
    {speaker:'侍应', han:'好嘅，即刻嚟。', jp:'hou2 ge3, zik1 hak1 lai4.', mand:'好的，马上来。'},
  ]},
{
  id:'direction', title:'问路', emoji:'🗺️', level:'入门', desc:'在街头向路人问路，练习方位与指路表达。', tags:['出行','问询'], lines:[
    {speaker:'游客', han:'唔该，我想去星光大道，点样行呀？', jp:'m4 goi1, ngo5 soeng2 heoi3 sing1 gwong1 daai6 dou6, dim2 joeng2 haang4 aa3?', mand:'请问，我想去星光大道，怎么走呀？'},
    {speaker:'路人', han:'沿住海旁一直行，五分钟就到。', jp:'jyun4 zyu6 hoi2 pong4 jat1 zik6 haang4, ng5 fan1 zung1 zau6 dou3.', mand:'沿着海边一直走，五分钟就到。'},
    {speaker:'游客', han:'咁近㗎，唔该晒！', jp:'gam3 kan5 gaa3, m4 goi1 saai3!', mand:'这么近呀，太感谢了！'},
    {speaker:'路人', han:'唔使客气。', jp:'m4 sai2 haak3 hei3.', mand:'不客气。'},
  ]},
{
  id:'doctor', title:'睇医生', emoji:'🩺', level:'初级', desc:'挂号问诊，描述病症，听懂医嘱。', tags:['健康','就医'], lines:[
    {speaker:'护士', han:'你边度唔舒服呀？', jp:'nei5 bin1 dou6 m4 syu1 fuk6 aa3?', mand:'你哪里不舒服呀？'},
    {speaker:'病人', han:'我头痛，仲有啲发烧。', jp:'ngo5 tau4 tung3, zung6 jau5 di1 faat3 siu1.', mand:'我头痛，还有点发烧。'},
    {speaker:'护士', han:'几耐喇？', jp:'gei2 noi6 laa3?', mand:'多久了？'},
    {speaker:'病人', han:'两日喇。', jp:'loeng5 jat6 laa3.', mand:'两天了。'},
    {speaker:'护士', han:'好，坐低等阵，医生好快叫你。', jp:'hou2, co5 dai1 dang2 zan6, ji1 sang1 hou2 faai3 giu3 nei5.', mand:'好，坐下等会儿，医生很快叫你。'},
  ]},
],

/* ---------- 4. 语法专栏 ---------- */
grammar: [
{
  id:'measure', num:'01', title:'量词面面观：个、只、条、嚿…', intro:'粤语的量词比普通话更"精细"：同一物品在两种语言里可能用不同的量词，同一个量词也可能覆盖完全不同的物品。量词用错，一听就知道不是本地人。',
  sections:[
    {h:'高频量词速查', type:'table', head:['量词','常用对象','例句'],
     rows:[['个 go3','人、家庭、职业','一个朋友 / 呢个问题'],['只 zek3','动物、鞋子、碗','一只鸡 / 三只鞋'],['条 tiu4','长条物、鱼、路','一条鱼 / 呢条街'],['张 zoeng1','纸、桌子、票','一张飞（票）'],['件 gin6','衣服、事情、行李','一件衫 / 一件大事'],['杯 bui1','饮品','一杯奶茶'],['碗 wun2','饭、面','一碗云吞面'],['碟 dip6','菜、点心','一碟肠粉'],['樽 zeon1','瓶装物','一樽水'],['部 bou6','机器、车辆','一部手机 / 一部车'],['架 gaa3','车辆','一架的士'],['粒 nap1','小圆物、药','一粒糖 / 一粒药'],['嚿 gau6','块状物（粗粝感）','一嚿石 / 一嚿饭'],['碌 luk1','柱状物','一碌蔗（甘蔗）'],['份 fan6','文件、套餐','一份报纸']]},
    {h:'易混量词对比', type:'table', head:['场景','粤语','普通话'],
     rows:[['一辆车','一架车 / 一部车','一辆车'],['一栋楼','一幢楼 / 一楝楼','一栋楼'],['一床被子','一张被','一床被子'],['一条裤子','一条裤','一条裤子'],['一只狗','一只狗','一只狗（一条狗）'],['一家餐厅','一间餐厅','一家餐厅']]},
    {h:'小贴士', type:'note', body:'量词前接「呢 / 嗰」表"这 / 那"：呢个（这个）、嗰只（那只）。「一」在量词前常读轻声 jat1，口语常说成"咁多"时要记得数一数量词配搭。'},
  ],
  examples:[
    {han:'呢个问题好简单。', jp:'ni1 go3 man6 tai4 hou2 gaan2 daan1.', mand:'这个问题很简单。'},
    {han:'我要一碟肠粉同两杯奶茶。', jp:'ngo5 jiu3 jat1 dip6 coeng2 fan2 tung4 loeng5 bui1 naai5 caa4.', mand:'我要一碟肠粉和两杯奶茶。'},
    {han:'嗰只猫好得意。', jp:'go2 zek3 maau1 hou2 dak1 ji3.', mand:'那只猫很可爱。'},
    {han:'一嚿饭都食唔晒。', jp:'jat1 gau6 faan6 dou1 sik6 m4 saai3.', mand:'一坨饭都吃不完。'},
  ]},
{
  id:'particles', num:'02', title:'语气词大观：啦、喎、㗎、咩、咋…', intro:'语气词是粤语的灵魂。同样的句子，换上不同的句尾语气词，意思、态度天差地别。这也是普通话母语者最头疼、也最"出味"的部分。',
  sections:[
    {h:'句尾语气词速查', type:'table', head:['语气词','语气/含义','例句'],
     rows:[['啦 laa1','肯定、催促、舒缓','唔该埋单啦。'],['喎 wo3','提醒对方不知道的事','冻饮加两蚊喎。'],['㗎 gaa3','反问/强调事实','佢好叻㗎！'],['咩 me1','疑问（意外）','你唔系去咗咩？'],['咋 zaa3','仅此而已（轻描淡写）','十蚊咋。'],['啫 ze1','而已（略不耐）','慢慢嚟啫。'],['呀 aa3','疑问（轻松）','你食咗饭未呀？'],['喇 laa3','已然、完成','我食完喇。'],['啦嘛 laa1 maa3','理所当然','冇办法啦嘛。'],['先 sin1','先、再（句尾表"再说"）','你睇下先。']]},
    {h:'三个高频词细说', type:'text', body:'「啦」：表肯定与商量，普通话的"吧/了"都有它的影子。「喎」：提醒对方一个TA不知道的事实，带点"喂，听我说"的意味。「㗎」：反问或强调，句调往上扬。'},
    {h:'小贴士', type:'note', body:'语气词可以和「呀」「啦」叠加，如"得啦呀"。语气词发音要轻而短，语调才是真正决定含义的部分——多听多模仿。'},
  ],
  examples:[
    {han:'唔该，埋单啦。', jp:'m4 goi1, maai4 daan1 laa1.', mand:'麻烦，买单吧。'},
    {han:'呢度好出名㗎！', jp:'ni1 dou6 hou2 ceot1 meng2 gaa3!', mand:'这里很有名呢！'},
    {han:'你唔系话嚟咩？', jp:'nei5 m4 hai6 waa6 lai4 me1?', mand:'你不是说要来吗？'},
    {han:'唔使惊喎，我喺度。', jp:'m4 sai2 geng1 wo3, ngo5 hai2 dou6.', mand:'别怕哦，我在这。'},
  ]},
{
  id:'aspect', num:'03', title:'动词体貌：咗、紧、过、开、下', intro:'粤语用句尾助词表达动作的状态，跟普通话的"了、着、过"大致对应，但用法更精细、更日常。',
  sections:[
    {h:'体貌助词速查', type:'table', head:['助词','含义','例句'],
     rows:[['咗 zo2','完成（类似"了"）','我食咗饭。'],['紧 gan2','进行中（类似"着"）','佢睇紧电视。'],['过 gwo3','曾经经历','我去过香港。'],['开 hoi1','习惯性动作','我食开呢间。'],['下 haa5','尝试一下','试下先。'],['完 jyun4','完成（尾）','我做完工先讲。']]},
    {h:'「咗」和「紧」', type:'text', body:'「咗」表示动作已经完成，相当于"……了"；「紧」表示正在进行，相当于"……着/正在……"。注意它们都放在动词后面、宾语前面。'},
    {h:'「开」的妙用', type:'text', body:'「食开」「做开」表示一直以来的习惯，隐含"我经常这样，所以理所当然"。例如「我食开呢间茶餐厅」= 我常来这家，很熟。'},
  ],
  examples:[
    {han:'我食咗饭喇。', jp:'ngo5 sik6 zo2 faan6 laa3.', mand:'我吃过饭了。'},
    {han:'佢而家睇紧电视。', jp:'keoi5 ji4 gaa1 tai2 gan2 din6 si6.', mand:'他现在正在看电视。'},
    {han:'你去过广州未呀？', jp:'nei5 heoi3 gwo3 gwong2 zau1 mei6 aa3?', mand:'你去过广州没有呀？'},
    {han:'试下先啦。', jp:'si3 haa5 sin1 laa1.', mand:'先试试看吧。'},
  ]},
{
  id:'hai6', num:'04', title:'「系」字家族：系、唔系、系咪…', intro:'粤语的「系」对应普通话的"是"，但衍生出一整套高频表达，几乎每句话都绕不开它。',
  sections:[
    {h:'「系」的用法', type:'table', head:['表达','含义','例句'],
     rows:[['系 hai6','是','我系老师。'],['唔系 m4 hai6','不是','我唔系老师。'],['系咪 hai6 mai6','是不是（疑问）','佢系咪嚟㗎？'],['系咩 hai6 me1','是吗（反问）','系咩？唔系啩。'],['系啦 hai6 laa1','对啊（附和）','系啦，我都咁话。'],['系话 hai6 waa6','就是说','系话，不如去饮茶？']]},
    {h:'「系」vs 普通话"是"', type:'text', body:'粤语「系」除了表判断，还常用来附和对方（系啦！）。疑问句常用「系咪」直接问，不用"是不是"那么长的结构。'},
  ],
  examples:[
    {han:'我系香港人。', jp:'ngo5 hai6 hoeng1 gong2 jan4.', mand:'我是香港人。'},
    {han:'佢系咪你朋友呀？', jp:'keoi5 hai6 mai6 nei5 pang4 jau5 aa3?', mand:'他是不是你朋友呀？'},
    {han:'系啦，我都系咁谂。', jp:'hai6 laa1, ngo5 dou1 hai6 gam2 nam2.', mand:'是啊，我也这么想。'},
  ]},
{
  id:'position', num:'05', title:'位置与虚词：喺、响、嚟、去、俾、同', intro:'几个小词撑起粤语的空间与关系表达：在哪、去哪、给谁、跟谁。',
  sections:[
    {h:'位置词', type:'table', head:['词','含义','例句'],
     rows:[['喺 hai2','在（某处）','我喺屋企。'],['响 hoeng2','在（口语，同"喺"）','佢响公司。'],['嚟 lai4','来','你快啲嚟！'],['去 heoi3','去','我哋去街。'],['返 faan1','回','放工返屋企。']]},
    {h:'关系词', type:'table', head:['词','含义','例句'],
     rows:[['俾 bei2','给 / 被','俾支笔我；俾人闹'],['同 tung4','和 / 跟','我同你去。'],['帮 bong1','帮','帮我影张相。'],['畀 bei2','给（同"俾"）','畀钱先。']]},
    {h:'「俾」的双重身份', type:'text', body:'「俾」既是"给"（俾我 = 给我），也是被动标记（俾人闹 = 被人骂）。小心别混淆。'},
  ],
  examples:[
    {han:'我而家喺地铁站。', jp:'ngo5 ji4 gaa1 hai2 dei6 tit3 zaam6.', mand:'我现在在地铁站。'},
    {han:'快啲嚟啦，等你啊。', jp:'faai3 di1 lai4 laa1, dang2 nei5 aa3.', mand:'快点来啦，等你呢。'},
    {han:'俾支笔我用下。', jp:'bei2 zi1 bat1 ngo5 jung6 haa5.', mand:'借支笔给我用一下。'},
    {han:'我同朋友食紧饭。', jp:'ngo5 tung4 pang4 jau5 sik6 gan2 faan6.', mand:'我和朋友正在吃饭。'},
  ]},
{
  id:'compare', num:'06', title:'比较句：A 好过 B', intro:'粤语比较句用「过」不用"比"：A 好过 B = A 比 B 好。结构简洁，一学就会。',
  sections:[
    {h:'基本结构', type:'table', head:['结构','含义','例句'],
     rows:[['A + 形容词 + 过 + B','A比B更…','地铁快过巴士。'],['A + 形容词 + 过 + B + 好多','A比B…得多','佢高过我好多。'],['有 + B + 咁 + 形容词','有B那么…','你有佢咁高咩？'],['冇 + B + 咁 + 形容词','没B那么…','我冇佢咁高。']]},
    {h:'程度加强', type:'text', body:'要表示"得多"，在「过」后面加「好多」；表示"一点"，加「啲」：好过佢啲（比他好一点）。'},
  ],
  examples:[
    {han:'地铁快过巴士。', jp:'dei6 tit3 faai3 gwo3 baa1 si2.', mand:'地铁比公交快。'},
    {han:'佢高过我好多。', jp:'keoi5 gou1 gwo3 ngo5 hou2 do1.', mand:'他比我高很多。'},
    {han:'我冇你咁识讲嘢。', jp:'ngo5 mou5 nei5 gam3 sik1 gong2 je5.', mand:'我没你那么会说话。'},
  ]},
{
  id:'negation', num:'07', title:'否定表达：唔、冇、未、咪、唔使…', intro:'粤语的否定词各有分工：唔=不、冇=没有、未=还没、咪=别。用错一个，意思就变了。',
  sections:[
    {h:'否定词速查', type:'table', head:['词','含义','例句'],
     rows:[['唔 m4','不','唔好 / 唔得 / 唔知'],['冇 mou5','没有','冇钱 / 冇时间'],['未 mei6','还没','未食饭'],['咪 mai5','别（祈使）','咪乱讲！'],['唔使 m4 sai2','不用','唔使客气'],['唔该 m4 goi1','劳驾/谢谢','唔该埋单']]},
    {h:'「唔」的否定小词', type:'text', body:'唔好（不好/别）、唔得（不行）、唔知（不知道）、唔明（不明白）……「唔」后面直接加动词或形容词，像普通话"不"一样灵活。'},
    {h:'「冇」vs「未」', type:'text', body:'「冇」强调"没有"这个状态（冇钱=没钱）；「未」强调"还没做"（未食饭=还没吃饭）。回答"食咗饭未？"时，说「未呀」就是"还没呢"。'},
  ],
  examples:[
    {han:'我唔知佢喺边。', jp:'ngo5 m4 zi1 keoi5 hai2 bin1.', mand:'我不知道他在哪。'},
    {han:'我冇钱买飞。', jp:'ngo5 mou5 cin4 maai5 fei1.', mand:'我没钱买票。'},
    {han:'你食咗饭未？未呀。', jp:'nei5 sik6 zo2 faan6 mei6? mei6 aa3.', mand:'你吃饭了吗？还没呢。'},
    {han:'咪嘈啦！', jp:'mai5 cou4 laa1!', mand:'别吵啦！'},
  ]},
{
  id:'question', num:'08', title:'疑问词全家福：咩、点、几时、边度、点解…', intro:'粤语疑问词和普通话差异较大，但数量少、规律强，记熟这一套就能问遍天下。',
  sections:[
    {h:'疑问词速查', type:'table', head:['粤语','含义','例句'],
     rows:[['咩 me1','什么','食咩呀？'],['边个 bin1 go3','谁','边个嚟㗎？'],['边度 bin1 dou6','哪里','去边度呀？'],['几时 gei2 si4','什么时候','几时出发？'],['点解 dim2 gaai2','为什么','点解迟到呀？'],['点 dim2','怎么','点去呀？'],['几点 gei2 dim2','几点','而家几点？'],['几多 gei2 do1','多少','几多钱呀？'],['点样 dim2 joeng2','怎么样','点样行呀？']]},
    {h:'「咩」的多重身份', type:'text', body:'「咩」表"什么"（食咩=吃什么），也可以单独用在句尾表反问（你唔嚟咩？=你不来吗？）。'},
    {h:'正反疑问', type:'text', body:'用「A唔A」结构：去唔去（去不去）、系唔系（是不是）、好唔好（好不好），加句尾「呀」更自然。'},
  ],
  examples:[
    {han:'你食咩呀？', jp:'nei5 sik6 me1 aa3?', mand:'你吃什么呀？'},
    {han:'呢度去边度最近？', jp:'ni1 dou6 heoi3 bin1 dou6 zeoi3 kan5?', mand:'这里去哪最近？'},
    {han:'点解你唔嚟？', jp:'dim2 gaai2 nei5 m4 lai4?', mand:'为什么你不来？'},
    {han:'你听日去唔去饮茶？', jp:'nei5 ting1 jat6 heoi3 m4 heoi3 jam2 caa4?', mand:'你明天去不去喝早茶？'},
  ]},
{
  id:'degree', num:'09', title:'程度副词：好、几、劲、超、鬼咁…', intro:'普通话说"很、非常"，粤语说「好、几、劲」。口语里还有一堆夸张又生动的说法，越地道越有趣。',
  sections:[
    {h:'程度副词速查', type:'table', head:['副词','程度','例句'],
     rows:[['好 hou2','很（中性）','好靓'],['几 gei2','挺（温和）','几好食'],['劲 ging6','超（夸张）','劲好玩'],['超 ciu1','超（年轻人口语）','超正'],['鬼咁 gwai2 gam3','超（俏皮）','鬼咁靓'],['冇得顶 mou5 dak1 deng2','没得顶/极好','佢嘅厨艺冇得顶']]},
    {h:'「好」的用法', type:'text', body:'「好」是最高频的程度副词：好靓、好正、好正点。注意「好」也可以单用表"好/行/可以"（好！= 好！行！）。'},
    {h:'夸张系表达', type:'text', body:'「鬼咁」带俏皮感：「鬼咁靓」= 靓到爆。「冇得顶」= 无可挑剔。这种带情绪的夸张说法，最能体现粤语的生猛。'},
  ],
  examples:[
    {han:'呢间嘢好正㗎！', jp:'ni1 gaan1 je5 hou2 zeng3 gaa3!', mand:'这家店超棒的呢！'},
    {han:'今日热到飞起。', jp:'gam1 jat6 jit6 dou3 fei1 hei2.', mand:'今天热得要命。'},
    {han:'佢讲粤语鬼咁流利。', jp:'keoi5 gong2 jyut6 jyu5 gwai2 gam3 lau4 lei6.', mand:'他说粤语超级流利。'},
    {han:'呢碟叉烧冇得顶！', jp:'ni1 dip6 caa1 siu1 mou5 dak1 deng2!', mand:'这碟叉烧没得挑！'},
  ]},
{
  id:'reduplication', num:'10', title:'叠字口语：食食下、行行下、谂谂吓', intro:'动词叠用+「下」表示动作进行到一半，是粤语特有的节奏感表达。',
  sections:[
    {h:'核心结构', type:'table', head:['结构','含义','例句'],
     rows:[['V + V + 下','正…到一半（突然）','食食下先发现冇餸'],['V + V + 吓','试着做做','谂谂吓先'],['V + 咗 + V','做完（强调完成）','做咗先讲'],['V + 嚟 + V + 去','反复折腾','行来行去']]},
    {h:'「食食下」的妙处', type:'text', body:'「食食下」= 吃着吃着，后面常接转折：食食下先发现（吃着吃着才发现）。这种"动作中途"的表达，普通话里没有直接对应，是粤语味的标志。'},
  ],
  examples:[
    {han:'我行行下先记起冇带锁匙。', jp:'ngo5 haang4 haang4 haa5 sin1 gei3 hei2 mou5 daai3 so2 si4.', mand:'我走着走着才想起没带钥匙。'},
    {han:'佢讲讲下突然停咗。', jp:'keoi5 gong2 gong2 haa5 dat6 jin4 ting4 zo2.', mand:'他说着说着突然停了。'},
    {han:'你谂谂吓先，唔使急。', jp:'nei5 nam2 nam2 haa5 sin1, m4 sai2 gap1.', mand:'你先想想，不用急。'},
  ]},
],

/* ---------- 5. 文化趣知 ---------- */
culture: {
  sayings: [
    {han:'马死落地行', jp:'maa5 sei2 lok6 dei6 haang4', meaning:'车到山前必有路，办法总比困难多。', story:'旧时出行靠马，马死了就只能下地走路。比喻遇到变故也要继续前行，办法总比困难多。'},
    {han:'有钱使得鬼推磨', jp:'jau5 cin4 sai2 dak1 gwai2 teoi1 mo6', meaning:'有钱能使鬼推磨。', story:'只要有钱，连鬼都愿意替你干活。讽刺金钱万能，也提醒人别被钱牵着走。'},
    {han:'鸡髀打人牙铰软', jp:'gai1 bei2 daa2 jan4 ngaa4 gaau3 jyun5', meaning:'吃人嘴软，拿人手短。', story:'髀=鸡腿，牙铰=下巴。用鸡腿"打"你的下巴，你的嘴就软了——收了人家的好处，自然说不出硬话。'},
    {han:'食得咸鱼抵得渴', jp:'sik6 dak1 haam4 jyu2 dai2 dak1 hot3', meaning:'敢做就要敢当，拿了好处就要承担后果。', story:'吃了咸鱼就要忍得住口渴。比喻既然选择了一条路，就要接受它带来的麻烦。'},
    {han:'执输行头，惨过败家', jp:'zap1 syu1 haang4 tau4, caam2 gwo3 baai6 gaa1', meaning:'样样落后于人，比败家更惨。', story:'执输=吃亏落后；行头=走在最前（此处反语）。事事抢不到先机，比挥霍家产还惨，提醒人要进取。'},
    {han:'苏州过后无艇搭', jp:'sou1 zau1 gwo3 hau6 mou4 teng5 daap3', meaning:'机不可失，时不再来。', story:'以前坐船去苏州，错过了就没船了。比喻机会稍纵即逝，要当机立断。'},
  ],
  xiehou: [
    {front:'老公泼扇', back:'凄（妻）凉', jp:'lou5 gung1 put3 sin3 — cat1 loeng4', meaning:'形容处境凄凉、寒酸。', story:'老公给老婆扇扇子——"妻凉"谐音"凄凉"，一语双关，冷幽默十足。'},
    {front:'哑巴食黄连', back:'有苦自己知', jp:'aa2 baa1 sik6 wong4 lin4 — jau5 fu2 zi6 gei2 zi1', meaning:'有苦说不出，只能自己扛。', story:'黄连极苦，哑巴吃了说不出，只能自己知道。粤语版比普通话版更强调"自己扛"。'},
    {front:'老鼠拉龟', back:'冇哂符', jp:'lou2 syu2 laai1 gwai1 — mou5 saai3 fu4', meaning:'无从下手，无计可施。', story:'老鼠想拖走乌龟，龟壳太滑太硬，怎么都使不上劲——"冇哂符"= 没辙了。'},
    {front:'茶楼搬家', back:'另起炉灶', jp:'caa4 lau2 bun1 gaa1 — ling6 hei2 lou4 zou3', meaning:'另起炉灶，重新开始。', story:'茶楼搬走，蒸笼炉灶自然要重新搭。比喻放弃旧摊子，从头再来。'},
    {front:'猫儿洗面', back:'咁上吓', jp:'maau1 ji4 sai2 min6 — gam3 soeng5 haa5', meaning:'随便应付，敷衍了事。', story:'猫洗脸只是随意抹两下，哪算认真洗？"咁上吓"= 差不多应付过去。'},
  ],
  life: [
    {title:'茶餐厅：丝袜奶茶与暗语', tag:'饮食', desc:'丝袜奶茶、鸳鸯、飞冰、走糖、多士……茶餐厅有自己的语言系统。', story:'茶餐厅是香港的"平民食堂"：奶茶用丝袜滤网反复撞茶，香浓顺滑；"飞冰"=不要冰块，"走糖"=不加糖。点一份"常餐"（套餐），就是最地道的港式体验。'},
    {title:'叮叮车：百年电车', tag:'交通', desc:'1904年开到今天的香港电车，因"叮叮"的铃声得名。', story:'沿着港岛北岸缓缓穿行的双层电车，是香港最便宜的观光方式。坐上层前排，吹着海风看街景，是本地人的怀旧仪式。'},
    {title:'大排档：街头镬气', tag:'饮食', desc:'街头小炒摊档，讲究大火快炒的"镬气"。', story:'铁锅猛火，油星四溅，一碟干炒牛河端上来还冒着烟——这就是大排档的魅力。可惜如今传统大排档越来越少，能吃到的都是情怀。'},
    {title:'凉茶铺：苦口良药', tag:'生活', desc:'廿四味、龟苓膏、五花茶，一碗苦茶治百病。', story:'广东人信"苦口良药"：廿四味用二十四种草药熬制，苦到皱眉，却是降火神器。以前街头凉茶铺挂个铜葫芦，就是招牌。'},
    {title:'鹅颈桥打小人', tag:'习俗', desc:'惊蛰日到鹅颈桥，把小人踩在脚下。', story:'每年惊蛰，湾仔鹅颈桥下就热闹起来：阿婆用拖鞋狠狠拍打纸扎小人，口中念念有词，把霉运统统赶走。这是香港最"出圈"的民间习俗之一。'},
    {title:'盆菜：围村大宴', tag:'习俗', desc:'新界围村的传统菜式，一层层堆满好意头。', story:'一个大木盆，由下而上堆着萝卜、猪肉、鸡、鱼、蚝豉，寓意"盆满钵满"。逢年过节，全村围坐一桌，一盆菜吃出团圆味。'},
    {title:'霓虹灯：不夜城的名片', tag:'城市', desc:'密密匝匝的霓虹招牌，曾是香港夜景的标志。', story:'"东方之珠"的夜景，一半靠维港灯光，一半靠街角招牌。如今传统霓虹渐被LED取代，但霓虹仍是香港留给世界的文化符号。'},
    {title:'「一盅两件」叹世界', tag:'饮食', desc:'一壶茶、两件点心，慢慢叹（享受）。', story:'"叹茶"的"叹"是享受的意思。清晨茶楼里，老伯看报，阿婆倾偈，一盅两件可以坐一上午——这种慢，是香港另一种节奏。'},
  ],
}
};
