/* ============================================================
   粵學堂 · 粤语歌学习数据
   ------------------------------------------------------------
   歌词、粤拼与普通话释义用于粤语发音和跟唱练习。
   歌曲及歌词版权归原作者和相关权利人所有；本站不提供歌曲音源。
   如权利人认为相关内容不宜展示，可联系维护者处理。
   ============================================================ */

const SONGS = [
{
  id:'ocean', title:'海闊天空', artist:'Beyond', year:1993,
  emoji:'🌊', level:'中级', tags:['经典','励志'],
  colors:['#0f3443','#34a2a2'],
  intro:'Beyond 的代表作，适合练习开阔元音、入声收尾和长句气息。',
  lyric:[
    {han:'今天我 寒夜裏看雪飄過', jp:'gam1 tin1 ngo5 hon4 je6 leoi5 hon3 syut3 piu1 gwo3', mand:'今天我，寒夜里看雪飘过', d:5.5},
    {han:'懷著冷卻了的心窩漂遠方', jp:'waai4 zoek6 laang5 kyut3 liu5 dik1 sam1 wo1 piu1 jyun5 fong1', mand:'怀着冷却了的心窝漂向远方', d:5.0},
    {han:'風雨裏追趕 霧裏分不清影蹤', jp:'fung1 jyu5 leoi5 zeoi1 gon2 mou6 leoi5 fan1 bat1 cing1 jing2 zung1', mand:'风雨里追赶，雾里分不清影踪', d:5.5},
    {han:'天空海闊你與我 可會變', jp:'tin1 hung1 hoi2 fut3 nei5 jyu5 ngo5 ho2 wui5 bin3', mand:'天空海阔你与我，可会变', d:5.0},
    {han:'多少次 迎著冷眼與嘲笑', jp:'do1 siu1 ci3 jing4 zoek6 laang5 ngaan5 jyu5 ziu1 siu3', mand:'多少次，迎着冷眼与嘲笑', d:5.5},
    {han:'從沒有放棄過心中的理想', jp:'cung4 mut6 jau5 fong3 hei3 gwo3 sam1 zung1 dik1 lei5 soeng2', mand:'从没有放弃过心中的理想', d:5.5},
    {han:'一剎那恍惚 若有所失的感覺', jp:'jat1 saat3 naa5 fong2 fat1 joek6 jau5 so2 sat1 dik1 gam2 gok3', mand:'一刹那恍惚，若有所失的感觉', d:5.5},
    {han:'不知不覺已變淡 心中愛', jp:'bat1 zi1 bat1 gok3 ji5 bin3 taam5 sam1 zung1 oi3', mand:'不知不觉已变淡，心中爱', d:5.5},
    {han:'原諒我這一生不羈放縱愛自由', jp:'jyun4 loeng6 ngo5 ze5 jat1 sang1 bat1 gei1 fong3 zung3 oi3 zi6 jau4', mand:'原谅我这一生不羁放纵爱自由', d:5.5},
    {han:'也會怕有一天會跌倒', jp:'je5 wui5 paa3 jau5 jat1 tin1 wui5 dit3 dou2', mand:'也会怕有一天会跌倒', d:4.5},
    {han:'背棄了理想 誰人都可以', jp:'bui3 hei3 liu5 lei5 soeng2 seoi4 jan4 dou1 ho2 ji5', mand:'背弃了理想，谁人都可以', d:5.0},
    {han:'哪會怕有一天只你共我', jp:'naa5 wui5 paa3 jau5 jat1 tin1 zi2 nei5 gung6 ngo5', mand:'哪会怕有一天只你共我', d:5.0},
    {han:'仍然自由自我 永遠高唱我歌 走遍千里', jp:'jing4 jin4 zi6 jau4 zi6 ngo5 wing5 jyun5 gou1 coeng3 ngo5 go1 zau2 pin3 cin1 lei5', mand:'仍然自由自我，永远高唱我歌，走遍千里', d:6.5},
  ],
  notes:[
    {target:'不羈 bat1 gei1', tip:'「羈」读 gei1，不是 gik1。不羈 = 不受束缚、洒脱。'},
    {target:'跌倒 dit3 dou2', tip:'「跌」是入声 -t 尾（dit3），短促收住，像"滴"一样戛然而止，别拖长。'},
    {target:'背棄 bui3 hei3', tip:'「背」读 bui3（背叛义），与"后背 bui3"同音，别读成 bei1。'},
    {target:'懷著 waai4 zoek6', tip:'「著」读 zoek6（承受/携带义），唱歌时常唱成"怀住"，都可。'},
    {target:'走遍 zau2 pin3', tip:'「遍」读 pin3，轻声短促，与"骗"同音。'},
    {target:'剎那 saat3 naa5', tip:'「剎」saat3（入声 -t 尾），"那"naa5，连读要快而准。'},
  ],
},
{
  id:'qianqian', title:'千千闕歌', artist:'陳慧嫻', year:1989,
  emoji:'🌙', level:'初级', tags:['经典','抒情'],
  colors:['#3a1c71','#b5651d'],
  intro:'旋律舒缓、吐字清晰，适合初学者练习连贯气息和句尾收音。',
  lyric:[
    {han:'徐徐回望 曾屬於彼此的晚上', jp:'ceoi4 ceoi4 wui4 mong6 cang4 suk6 jyu1 bei2 ci2 dik1 maan5 soeng6', mand:'徐徐回望，曾属于彼此的晚上', d:5.5},
    {han:'紅紅仍是你 贈我的心中艷陽', jp:'hung4 hung4 jing4 si6 nei5 zang6 ngo5 dik1 sam1 zung1 jim6 joeng4', mand:'红红仍是你，赠我的心中艳阳', d:5.5},
    {han:'如流傻淚 祈望可體諒兼見諒', jp:'jyu4 lau4 so4 leoi6 kei4 mong6 ho2 tai2 loeng6 gim1 gin3 loeng6', mand:'如流傻泪，祈望可体谅兼见谅', d:6.0},
    {han:'明晨離別你 路也許孤單得漫長', jp:'ming4 san4 lei4 bit6 nei5 lou6 jaa5 heoi2 gu1 daan1 dak1 maan6 coeng4', mand:'明晨离别你，路也许孤单得漫长', d:6.0},
    {han:'一瞬間 太多東西要講', jp:'jat1 zan6 gaan1 taai3 do1 dung1 sai1 jiu3 gong2', mand:'一瞬间，太多东西要讲', d:4.5},
    {han:'可惜即將在各一方', jp:'ho2 sik1 zik1 zoeng1 zoi6 gok3 jat1 fong1', mand:'可惜即将在各一方', d:4.5},
    {han:'只好深深這刻再凝望 夜空', jp:'zik1 hou2 sam1 sam1 ze5 hak1 zoi3 jing4 mong6 je6 hung1', mand:'只好深深这刻再凝望夜空', d:5.0},
    {han:'臨行臨別 才頓感哀傷的漂亮', jp:'lam4 hang4 lam4 bit6 coi4 deon6 gam2 oi1 soeng1 dik1 piu3 loeng6', mand:'临行临别，才顿感哀伤的漂亮', d:6.0},
    {han:'原來全是你 令我的思憶漫長', jp:'jyun4 loi4 cyun4 si6 nei5 ling6 ngo5 dik1 si1 jik1 maan6 coeng4', mand:'原来全是你，令我的思忆漫长', d:5.5},
    {han:'何年何月 才又可今宵一樣', jp:'ho4 nin4 ho4 jyut6 coi4 jau6 ho2 gam1 siu1 jat1 joeng6', mand:'何年何月，才又可今宵一样', d:5.5},
    {han:'停留凝望裏 讓眼睛講彼此立場', jp:'ting4 lau4 jing4 mong6 leoi5 joeng6 ngaan5 zing1 gong2 bei2 ci2 laap6 coeng4', mand:'停留凝望里，让眼睛讲彼此立场', d:6.0},
    {han:'當某天 雨點輕敲你窗', jp:'dong1 mau5 tin1 jyu5 dim2 hing1 haau1 nei5 coeng1', mand:'当某天，雨点轻敲你窗', d:4.5},
    {han:'當風聲吹亂你構想', jp:'dong1 fung1 sing1 ceoi1 lyun6 nei5 kau3 soeng2', mand:'当风声吹乱你构想', d:4.5},
    {han:'可否抽空想這張舊模樣', jp:'ho2 fau2 cau1 hung1 soeng2 ze5 zoeng1 gau6 mou4 joeng6', mand:'可否抽空想这张旧模样', d:5.0},
    {han:'來日縱使千千闕歌 飄於遠方我路上', jp:'loi4 jat6 zung3 si2 cin1 cin1 kyut3 go1 piu1 jyu1 jyun5 fong1 ngo5 lou6 soeng6', mand:'来日纵使千千阙歌，飘于远方我路上', d:6.5},
    {han:'來日縱使千千晚星 亮過今晚月亮', jp:'loi4 jat6 zung3 si2 cin1 cin1 maan5 sing1 loeng6 gwo3 gam1 maan5 jyut6 loeng6', mand:'来日纵使千千晚星，亮过今晚月亮', d:6.5},
    {han:'都比不起這宵美麗 亦絕不可使我更欣賞', jp:'dou1 bei2 bat1 hei2 ze5 siu1 mei5 lai6 jik6 zyut6 bat1 ho2 si2 ngo5 gang3 jan1 soeng2', mand:'都比不起这宵美丽，亦绝不可使我更欣赏', d:7.0},
    {han:'因你今晚共我唱', jp:'jan1 nei5 gam1 maan5 gung6 ngo5 coeng3', mand:'因你今晚共我唱', d:4.5},
    {han:'怎都比不起這宵美麗', jp:'zam2 dou1 bei2 bat1 hei2 ze5 siu1 mei5 lai6', mand:'怎都比不起这宵美丽', d:5.0},
    {han:'因你今晚共我唱', jp:'jan1 nei5 gam1 maan5 gung6 ngo5 coeng3', mand:'因你今晚共我唱', d:4.5},
  ],
  notes:[
    {target:'闕歌 kyut3 go1', tip:'「闕」读 kyut3（入声 -t 尾），是歌曲的量词，写作"千千阕歌"。'},
    {target:'艷陽 jim6 joeng4', tip:'「艷」读 jim6 不是 jin6，注意韵母 im。'},
    {target:'傻淚 so4 leoi6', tip:'「傻」读 so4（s-o），不是普通话的 shǎ；「淚」读 leoi6。'},
    {target:'離別 lei4 bit6', tip:'「別」读 bit6（入声 -t 尾），短促收尾。'},
    {target:'縱使 zung3 si2', tip:'「縱」读 zung3，与"中意 zung1 ji3"的 zung 同族。'},
    {target:'構想 kau3 soeng2', tip:'「構」读 kau3 不是 gau3，k- 送气音要清晰。'},
  ],
},
{
  id:'redsun', title:'紅日', artist:'李克勤', year:1992,
  emoji:'🔥', level:'进阶', tags:['经典','快歌'],
  colors:['#8e0e00','#c94b4b'],
  intro:'节奏明快、语句密集，适合进阶学习者练口齿、节拍和连续入声。',
  lyric:[
    {han:'命運就算顛沛流離 命運就算曲折離奇', jp:'ming6 wan6 zau6 syun3 din1 pui3 lau4 lei4 ming6 wan6 zau6 syun3 kuk1 zit3 lei4 kei4', mand:'命运就算颠沛流离，命运就算曲折离奇', d:5.5},
    {han:'命運就算恐嚇著你做人沒趣味', jp:'ming6 wan6 zau6 syun3 hung2 haak3 zoek6 nei5 zou6 jan4 mut6 ceoi3 mei6', mand:'命运就算恐吓着你做人没趣味', d:5.5},
    {han:'別流淚 心酸 更不應捨棄', jp:'bit6 lau4 leoi6 sam1 syun1 gang3 bat1 jing1 se2 hei3', mand:'别流泪，心酸，更不应舍弃', d:5.0},
    {han:'我願能 一生永遠陪伴你', jp:'ngo5 jyun6 nang4 jat1 sang1 wing5 jyun5 pui4 bun6 nei5', mand:'我愿能，一生永远陪伴你', d:5.0},
    {han:'紅日之火 燃點真的我', jp:'hung4 jat6 zi1 fo2 jin4 dim2 zan1 dik1 ngo5', mand:'红日之火，燃点真的我', d:4.5},
    {han:'結伴行 千山也定能踏過', jp:'git6 bun6 haang4 cin1 saan1 jaa5 ding6 nang4 daap6 gwo3', mand:'结伴行，千山也定能踏过', d:5.0},
    {han:'讓晚風輕輕吹過 伴送著清幽花香 像是在祝福你我', jp:'joeng6 maan5 fung1 hing1 hing1 ceoi1 gwo3 bun6 sung3 zoek6 cing1 jau1 faa1 hoeng1 zoeng6 hai6 zoi6 zuk1 fuk1 nei5 ngo5', mand:'让晚风轻轻吹过，伴送着清幽花香，像是在祝福你我', d:7.0},
    {han:'讓晚星輕輕閃過 閃出你每個希冀如浪花 快要沾濕我', jp:'joeng6 maan5 sing1 hing1 hing1 sim2 gwo3 sim2 ceot1 nei5 mui5 go3 hei1 kei3 jyu4 long6 faa1 faai3 jiu3 zim1 sap1 ngo5', mand:'让晚星轻轻闪过，闪出你每个希冀如浪花，快要沾湿我', d:7.0},
    {han:'一生之中兜兜轉轉 哪會看清楚', jp:'jat1 sang1 zi1 zung1 dau1 dau1 zyun3 zyun3 naa5 wui5 hon3 cing1 co2', mand:'一生之中兜兜转转，哪会看清楚', d:5.5},
    {han:'徬徨時我也試過獨坐一角像是沒協助', jp:'pong4 wong4 si4 ngo5 jaa5 si3 gwo3 duk6 co5 jat1 gok3 zoeng6 si6 mut6 hip3 zo6', mand:'彷徨时我也试过独坐一角像是没协助', d:6.5},
    {han:'在某年 那幼小的我', jp:'zoi6 mau5 nin4 naa5 jau3 siu2 dik1 ngo5', mand:'在某年，那幼小的我', d:4.5},
    {han:'跌倒過幾多幾多落淚在雨夜滂沱', jp:'dit3 dou2 gwo3 gei2 do1 gei2 do1 lok6 leoi6 zoi6 jyu5 je6 pong4 to4', mand:'跌倒过几多几多落泪在雨夜滂沱', d:6.5},
    {han:'一生之中彎彎曲曲我也要走過', jp:'jat1 sang1 zi1 zung1 waan1 waan1 kuk1 kuk1 ngo5 jaa5 jiu3 zau2 gwo3', mand:'一生之中弯弯曲曲我也要走过', d:6.0},
    {han:'從何時有你 有你伴我給我熱烈地拍和', jp:'cung4 ho4 si4 jau5 nei5 jau5 nei5 bun6 ngo5 kap1 ngo5 jit6 lit6 dei6 paak3 wo6', mand:'从何时有你，有你伴我给我热烈地拍和', d:6.5},
    {han:'像紅日之火 燃點真的我', jp:'zoeng6 hung4 jat6 zi1 fo2 jin4 dim2 zan1 dik1 ngo5', mand:'像红日之火，燃点真的我', d:5.0},
    {han:'結伴行 千山也定能踏過', jp:'git6 bun6 haang4 cin1 saan1 jaa5 ding6 nang4 daap6 gwo3', mand:'结伴行，千山也定能踏过', d:5.0},
  ],
  notes:[
    {target:'顛沛流離 din1 pui3 lau4 lei4', tip:'「沛」读 pui3 不是 pei4；四个字全是口语高频音，练绕口令就靠它。'},
    {target:'恐嚇 hung2 haak3', tip:'「嚇」读 haak3（入声 -k 尾），不是 haa3。'},
    {target:'捨棄 se2 hei3', tip:'「捨」读 se2，与"舍"同字；别读成普通话 shě 的粤化音。'},
    {target:'燃點 jin4 dim2', tip:'「燃」读 jin4（j-i-n），"點"读 dim2，连读 jin4 dim2。'},
    {target:'希冀 hei1 kei3', tip:'「冀」读 kei3，是"希望"的书面语，唱歌时别读成 ji3。'},
    {target:'沾濕 zim1 sap1', tip:'「沾」读 zim1（z-i-m），"濕"读 sap1（入声 -p 尾，闭口收）。'},
    {target:'滂沱 pong4 to4', tip:'「滂」pong4、「沱」to4，唱"雨夜滂沱"时注意 ng 尾和 o 韵。'},
  ],
},
{
  id:'lihuanxi', title:'喜歡你', artist:'Beyond', year:1988,
  emoji:'💛', level:'初级', tags:['经典','情歌'],
  colors:['#654ea3','#eaafc8'],
  intro:'旋律温柔、字音清晰，适合新手练习稳定发声和自然口型。',
  lyric:[
    {han:'細雨帶風濕透黃昏的街道', jp:'sai3 jyu5 daai3 fung1 sap1 tau3 wong4 fan1 dik1 gaai1 dou6', mand:'细雨带风湿透黄昏的街道', d:5.5},
    {han:'抹去雨水雙眼無故地仰望', jp:'maat3 heoi3 jyu5 seoi2 soeng1 ngaan5 mou4 gu3 dei6 ngong5 mong6', mand:'抹去雨水，双眼无故地仰望', d:5.5},
    {han:'望向孤單的晚燈 是那傷感的記憶', jp:'mong6 hoeng3 gu1 daan1 dik1 maan5 dang1 si6 naa5 soeng1 gam2 dik1 gei3 jik1', mand:'望向孤单的晚灯，是那伤感的记忆', d:6.0},
    {han:'再次泛起心裏無數的思念', jp:'zoi3 ci3 faan6 hei2 sam1 leoi5 mou5 sou3 dik1 si1 nim6', mand:'再次泛起心里无数的思念', d:5.5},
    {han:'以往片刻歡笑仍掛在臉上', jp:'ji5 wong5 pin3 hak1 fun1 siu3 jing4 gwaa3 zoi6 lim5 soeng6', mand:'以往片刻欢笑仍挂在脸上', d:5.5},
    {han:'願你此刻可會知 是我衷心的說話', jp:'jyun6 nei5 ci2 hak1 ho2 wui5 zi1 si6 ngo5 zung1 sam1 dik1 syut3 waa6', mand:'愿你此刻可会知，是我衷心的说话', d:6.0},
    {han:'喜歡你 那雙眼動人 笑聲更迷人', jp:'hei2 fun1 nei5 naa5 soeng1 ngaan5 dung6 jan4 siu3 sing1 gang3 mai4 jan4', mand:'喜欢你，那双眼动人，笑声更迷人', d:6.0},
    {han:'願再可 輕撫你那可愛面容', jp:'jyun6 zoi3 ho2 hing1 fu2 nei5 naa5 ho2 oi3 min6 jung4', mand:'愿再可，轻抚你那可爱面容', d:5.5},
    {han:'挽手說夢話 像昨天 你共我', jp:'waan5 sau2 syut3 mung6 waa6 zoeng6 zok3 tin1 nei5 gung6 ngo5', mand:'挽手说梦话，像昨天，你共我', d:5.5},
    {han:'每晚夜裏自我獨行 隨處蕩 多冰冷', jp:'mui5 maan5 je6 leoi5 zi6 ngo5 duk6 haang4 ceoi4 cyu5 dong6 do1 bing1 laang5', mand:'每晚夜里自我独行，随处荡，多冰冷', d:6.5},
    {han:'已為了愛心 倦透也歸家', jp:'ji5 wai6 liu5 oi3 sam1 gyun6 tau3 jaa5 gwai1 gaa1', mand:'已为了爱心，倦透也归家', d:5.0},
  ],
  notes:[
    {target:'濕透 sap1 tau3', tip:'「濕」是入声 -p 尾（sap1），闭口收住，唱时要短促。'},
    {target:'仰望 ngong5 mong6', tip:'「仰」读 ngong5，带 ng- 鼻音开头，别吞掉。'},
    {target:'衷心的 zung1 sam1', tip:'「衷」读 zung1，与"中意 zung1 ji3"同音。'},
    {target:'挽手 waan5 sau2', tip:'「挽」读 waan5，a-a-n 长韵，圆唇过渡。'},
    {target:'倦透 gyun6 tau3', tip:'「倦」读 gyun6，与"眷顧"同音；透 tau3。'},
  ],
},
{
  id:'zhenai', title:'真的愛你', artist:'Beyond', year:1989,
  emoji:'💖', level:'初级', tags:['经典','母亲'],
  colors:['#ad5389','#3c1053'],
  intro:'节奏稳定、吐字清楚，适合初学者开嗓和练习情绪表达。',
  lyric:[
    {han:'無法可修飾的一對手', jp:'mou4 faat3 ho2 sau1 sik1 dik1 jat1 deoi3 sau2', mand:'无法可修饰的一对手', d:5.0},
    {han:'帶出溫暖永遠在背後', jp:'daai3 ceot1 wan1 nyun5 wing5 jyun5 zoi6 bui3 hau6', mand:'带出温暖永远在背后', d:5.0},
    {han:'縱使囉嗦始終關注 不懂珍惜太內咎', jp:'zung3 si2 lo1 so1 ci2 zung1 gwaan1 zyu3 bat1 dung2 zan1 sik1 taai3 noi6 gau3', mand:'纵使啰嗦始终关注，不懂珍惜太内疚', d:6.0},
    {han:'沉醉於音階她不讚賞 母親的愛卻永未退讓', jp:'cam4 zeoi3 jyu1 jam1 gaai1 taa1 bat1 zaan3 soeng2 mou5 can1 dik1 oi3 koek3 wing5 mei6 teoi3 joeng6', mand:'沉醉于音阶她不赞赏，母亲的爱却永未退让', d:6.5},
    {han:'決心衝開心中掙扎 親恩終可報答', jp:'kyut3 sam1 cung1 hoi1 sam1 zung1 zaang1 zaat3 can1 jan1 zung1 ho2 bou3 daap3', mand:'决心冲开心中挣扎，亲恩终可报答', d:6.0},
    {han:'春風化雨暖透我的心 一生眷顧無言地送贈', jp:'ceon1 fung1 faa3 jyu5 nyun5 tau3 ngo5 dik1 sam1 jat1 sang1 gyun3 gu3 mou4 jin4 dei6 sung3 zang6', mand:'春风化雨暖透我的心，一生眷顾无言地送赠', d:6.5},
    {han:'是你多麼溫馨的目光', jp:'si6 nei5 do1 mo1 wan1 hing1 dik1 muk6 gwong1', mand:'是你多么温馨的目光', d:5.0},
    {han:'教我堅毅望著前路 叮囑我跌倒不應放棄', jp:'gaau3 ngo5 gin1 ngai6 mong6 zoek6 cin4 lou6 ding1 zuk1 ngo5 dit3 dou2 bat1 jing1 fong3 hei3', mand:'教我坚毅望着前路，叮嘱我跌倒不应放弃', d:7.0},
    {han:'沒法解釋怎可報盡親恩', jp:'mut6 faat3 gaai2 sik1 zam2 ho2 bou3 zeon6 can1 jan1', mand:'没法解释怎可报尽亲恩', d:5.5},
    {han:'愛意寬大是無限 請准我說聲真的愛你', jp:'oi3 ji3 fun1 daai6 si6 mou4 haan6 cing2 zeon2 ngo5 syut3 sing1 zan1 dik1 oi3 nei5', mand:'爱意宽大是无限，请准我说声真的爱你', d:7.0},
    {han:'仍記起溫馨的一對手 給我安心給我暖透', jp:'jing4 gei3 hei2 wan1 hing1 dik1 jat1 deoi3 sau2 kap1 ngo5 on1 sam1 kap1 ngo5 nyun5 tau3', mand:'仍记起温馨的一对手，给我安心给我暖透', d:6.5},
  ],
  notes:[
    {target:'修飾 sau1 sik1', tip:'「飾」是入声 -k 尾（sik1），短促；"修饰"别拖长。'},
    {target:'囉嗦 lo1 so1', tip:'「囉」读 lo1，叠词节奏要干脆。'},
    {target:'眷顧 gyun3 gu3', tip:'「眷」读 gyun3，圆唇韵母，唱时嘴型要收圆。'},
    {target:'送贈 sung3 zang6', tip:'「贈」读 zang6 不是 zan6，注意 ng 尾。'},
    {target:'堅毅 gin1 ngai6', tip:'「毅」读 ngai6，ng- 鼻音开头。'},
    {target:'叮囑 ding1 zuk1', tip:'「囑」读 zuk1（入声 -k 尾），短促。'},
  ],
},
{
  id:'glory', title:'光輝歲月', artist:'Beyond', year:1990,
  emoji:'🕊️', level:'中级', tags:['经典','励志'],
  colors:['#4568dc','#b06ab3'],
  intro:'适合练习圆唇声母、长句气息和有力度的副歌表达。',
  lyric:[
    {han:'鐘聲響起歸家的訊號', jp:'zung1 sing1 hoeng2 hei2 gwai1 gaa1 dik1 seon3 hou6', mand:'钟声响起归家的讯号', d:5.0},
    {han:'在他生命裏 彷彿帶點唏噓', jp:'zoi6 taa1 sang1 ming6 leoi5 fong2 fat1 daai3 dim2 hei1 heoi1', mand:'在他生命里，仿佛带点唏嘘', d:5.5},
    {han:'黑色肌膚給他的意義', jp:'hung1 sik1 gei1 fu1 kap1 taa1 dik1 ji3 ji6', mand:'黑色肌肤给他的意义', d:5.0},
    {han:'是一生奉獻 膚色鬥爭中', jp:'si6 jat1 sang1 fung6 hin3 fu1 sik1 dau3 zaang1 zung1', mand:'是一生奉献，肤色斗争中', d:5.5},
    {han:'年月把擁有變做失去', jp:'nin6 jyut6 baa2 jung5 jau5 bin3 zou6 sat1 heoi3', mand:'年月把拥有变做失去', d:5.0},
    {han:'疲倦的雙眼帶著期望', jp:'pei4 gyun6 dik1 soeng1 ngaan5 daai3 zoek6 kei4 mong6', mand:'疲倦的双眼带着期望', d:5.0},
    {han:'今天只有殘留的軀殼 迎接光輝歲月', jp:'gam1 tin1 zi2 jau5 caan4 lau4 dik1 keoi1 hok3 jing4 zip3 gwong1 fai1 seoi3 jyut6', mand:'今天只有残留的躯壳，迎接光辉岁月', d:6.5},
    {han:'風雨中抱緊自由', jp:'fung1 jyu5 zung1 pou5 gan2 zi6 jau4', mand:'风雨中抱紧自由', d:4.5},
    {han:'一生經過徬徨的掙扎', jp:'jat1 sang1 ging1 gwo3 pong4 wong4 dik1 zaang1 zaat3', mand:'一生经过彷徨的挣扎', d:5.5},
    {han:'自信可改變未來', jp:'zi6 seon3 ho2 goi2 bin3 mei6 loi4', mand:'自信可改变未来', d:4.5},
    {han:'問誰又能做到', jp:'man6 seoi4 jau6 nang4 zou6 dou3', mand:'问谁又能做到', d:4.0},
    {han:'可否不分膚色的界限', jp:'ho2 fau2 bat1 fan1 fu1 sik1 dik1 gaai3 haan6', mand:'可否不分肤色的界限', d:5.5},
    {han:'願這土地裏 不分你我高低', jp:'jyun6 ze5 tou2 dei6 leoi5 bat1 fan1 nei5 ngo5 gou1 dai1', mand:'愿这土地里，不分你我高低', d:5.5},
    {han:'繽紛色彩閃出的美麗', jp:'ban1 fan1 sik1 coi2 sim2 ceot1 dik1 mei5 lai6', mand:'缤纷色彩闪出的美丽', d:5.0},
    {han:'是因它沒有 分開每種色彩', jp:'si6 jan1 taa1 mut6 jau5 fan1 hoi1 mui5 zung2 sik1 coi2', mand:'是因它没有，分开每种色彩', d:5.5},
  ],
  notes:[
    {target:'唏噓 hei1 heoi1', tip:'「唏」hei1、「噓」heoi1，两个不同韵母，连读练口腔开合。'},
    {target:'奉獻 fung6 hin3', tip:'「獻」读 hin3 不是 haan3，注意 i-n 韵。'},
    {target:'軀殼 keoi1 hok3', tip:'「殼」是入声 -k 尾（hok3），短促收住。'},
    {target:'光輝 gwong1 fai1', tip:'「光」读 gwong1，圆唇 gw- 开头，唱时别发成 gong。'},
    {target:'徬徨 pong4 wong4', tip:'「徬」pong4、「徨」wong4，两字都带 ng 尾。'},
    {target:'繽紛 ban1 fan1', tip:'「繽」读 ban1（b-a-n），别发成 bin1。'},
  ],
},
{
  id:'shanghai', title:'上海灘', artist:'葉麗儀', year:1980,
  emoji:'🌊', level:'中级', tags:['经典','大气'],
  colors:['#0f2027','#203a43'],
  intro:'旋律起伏鲜明，适合练长音、胸腔共鸣和句尾力度。',
  lyric:[
    {han:'浪奔浪流 萬里滔滔江水永不休', jp:'long6 ban1 long6 lau4 maan6 leoi5 tou4 tou4 gong1 seoi2 wing5 bat1 jau1', mand:'浪奔浪流，万里滔滔江水永不休', d:6.0},
    {han:'淘盡了世間事 混作滔滔一片潮流', jp:'tou4 zeon6 liu5 sai3 gaan1 si6 wan6 zok3 tou4 tou4 jat1 pin3 ciu4 lau4', mand:'淘尽了世间事，混作滔滔一片潮流', d:6.0},
    {han:'是喜是愁 浪裏分不清歡笑悲憂', jp:'si6 hei2 si6 sau4 long6 leoi5 fan1 bat1 cing1 fun1 siu3 bei1 jau1', mand:'是喜是愁，浪里分不清欢笑悲忧', d:6.0},
    {han:'成功失敗 浪裏看不出有未有', jp:'sing4 gung1 sat1 baai6 long6 leoi5 hon3 bat1 ceot1 jau5 mei6 jau5', mand:'成功失败，浪里看不出有未有', d:6.0},
    {han:'愛你恨你 問君知否', jp:'oi3 nei5 han6 nei5 man6 gwan1 zi1 fau2', mand:'爱你恨你，问君知否', d:4.5},
    {han:'似大江一發不收', jp:'ci5 daai6 gong1 jat1 faat3 bat1 sau1', mand:'似大江一发不收', d:4.5},
    {han:'轉千彎轉千灘 亦未平復此中爭鬥', jp:'zyun3 cin1 waan1 zyun3 cin1 taan1 jik6 mei6 ping4 fuk6 ci2 zung1 zaang1 dau3', mand:'转千弯转千滩，亦未平复此中争斗', d:6.0},
    {han:'又有喜又有愁 就算分不清歡笑悲憂', jp:'jau6 jau5 hei2 jau6 jau5 sau4 zau6 syun3 fan1 bat1 cing1 fun1 siu3 bei1 jau1', mand:'又有喜又有愁，就算分不清欢笑悲忧', d:6.0},
    {han:'仍願翻 百千浪 在我心中起伏夠', jp:'jing4 jyun6 faan1 baak3 cin1 long6 zoi6 ngo5 sam1 zung1 hei2 fuk6 gau3', mand:'仍愿翻，百千浪，在我心中起伏够', d:6.0},
  ],
  notes:[
    {target:'滔滔 tou4 tou4', tip:'「滔」读 tou4，叠字唱出江水奔涌的连绵感。'},
    {target:'悲憂 bei1 jau1', tip:'「悲」bei1、「憂」jau1，两字韵母不同，练清。'},
    {target:'問君 man6 gwan1', tip:'「君」读 gwan1，圆唇 gw-，唱时嘴型收圆。'},
    {target:'轉千彎 zyun3 cin1 waan1', tip:'「彎」读 waan1，a-a-n 长韵，拉长音练习的黄金句。'},
    {target:'起伏夠 hei2 fuk6 gau3', tip:'「伏」fuk6（入声 -k 尾），"夠"gau3，收尾干脆。'},
  ],
},
{
  id:'lion', title:'獅子山下', artist:'羅文', year:1979,
  emoji:'🦁', level:'中级', tags:['经典','香港精神'],
  colors:['#232526','#414345'],
  intro:'慢板且层次清楚，适合练习字正腔圆、共鸣和叙事感。',
  lyric:[
    {han:'人生中有歡喜 難免亦常有淚', jp:'jan4 sang1 zung1 jau5 fun1 hei2 naan4 min5 jik6 soeng4 jau5 leoi6', mand:'人生中有欢喜，难免亦常有泪', d:5.5},
    {han:'我哋大家在獅子山下相遇上', jp:'ngo5 dei6 daai6 gaa1 zoi6 si1 zi2 saan1 haa6 soeng1 jyu6 soeng6', mand:'我们大家在狮子山下相遇上', d:6.0},
    {han:'總算是歡笑多於唏噓', jp:'zung2 syun3 si6 fun1 siu3 do1 jyu1 hei1 heoi1', mand:'总算是欢笑多于唏嘘', d:5.0},
    {han:'人生不免崎嶇 難以絕無掛慮', jp:'jan4 sang1 bat1 min5 kei1 keoi1 naan4 ji5 zyut6 mou4 gwaa3 leoi6', mand:'人生不免崎岖，难以绝无挂虑', d:5.5},
    {han:'既是同舟 在獅子山下 且共濟', jp:'gai3 si6 tung4 zau1 zoi6 si1 zi2 saan1 haa6 ce2 gung6 zai3', mand:'既是同舟，在狮子山下，且共济', d:6.0},
    {han:'拋棄區分求共對 放開彼此心中矛盾', jp:'pau1 hei3 keoi1 fan1 kau4 gung6 deoi3 fong3 hoi1 bei2 ci2 sam1 zung1 mau5 teon5', mand:'抛弃区分求共对，放开彼此心中矛盾', d:6.5},
    {han:'理想一起去追 同舟人誓相隨', jp:'lei5 soeng2 jat1 hei2 heoi3 zeoi1 tung4 zau1 jan4 sai3 soeng1 ceoi4', mand:'理想一起去追，同舟人誓相随', d:5.5},
    {han:'無畏更無懼 攜手踏平崎嶇', jp:'mou4 wai6 gang3 mou4 geoi6 kwai4 sau2 daap6 ping4 kei1 keoi1', mand:'无畏更无惧，携手踏平崎岖', d:5.5},
    {han:'我哋大家 用艱辛努力寫下那不朽香江名句', jp:'ngo5 dei6 daai6 gaa1 jung6 gaan1 san1 nou5 lik6 se2 haa6 naa5 bat1 jau2 hoeng1 gong1 ming4 geoi3', mand:'我们大家，用艰辛努力写下那不朽香江名句', d:7.5},
  ],
  notes:[
    {target:'唏噓 hei1 heoi1', tip:'同《光辉岁月》：hei1 + heoi1，练两韵。'},
    {target:'崎嶇 kei1 keoi1', tip:'「崎」kei1、「嶇」keoi1，叠词连读是难点也是亮点。'},
    {target:'同舟 tung4 zau1', tip:'「舟」读 zau1，z-a-u，别发成 zh-ou。'},
    {target:'誓相隨 sai3 soeng1 ceoi4', tip:'「誓」sai3、「隨」ceoi4，一短一长，节奏感练习。'},
    {target:'不朽 bat1 jau2', tip:'「朽」读 jau2（j-a-u），"不朽"= 不会磨灭。'},
  ],
},
{
  id:'manbu', title:'漫步人生路', artist:'鄧麗君', year:1983,
  emoji:'🌅', level:'初级', tags:['经典','抒情'],
  colors:['#ee9ca7','#ffdde1'],
  intro:'旋律轻快、节奏平稳，适合练习连读和自然的粤语语流。',
  lyric:[
    {han:'在你身邊路雖遠未疲倦', jp:'zoi6 nei5 san1 bin1 lou6 seoi1 jyun5 mei6 pei4 gyun6', mand:'在你身边路虽远未疲倦', d:5.5},
    {han:'伴你漫行一段接一段', jp:'bun6 nei5 maan6 haang4 jat1 dyun6 zip3 jat1 dyun6', mand:'伴你漫行一段接一段', d:5.0},
    {han:'越過高峰另一高峰卻飛越 在我倆面前', jp:'yut6 gwo3 gou1 fung1 ling6 jat1 gou1 fung1 koek3 fei1 jyut6 zoi6 ngo5 loeng5 min6 cin4', mand:'越过高峰另一高峰却飞越，在我俩面前', d:6.5},
    {han:'願你路漫漫 世事如雲煙', jp:'jyun6 nei5 lou6 maan6 maan6 sai3 si6 jyu4 wan4 jin1', mand:'愿你路漫漫，世事如云烟', d:5.0},
    {han:'崎嶇路 快踏上 讓心境自然', jp:'kei1 keoi1 lou6 faai3 daap6 soeng6 joeng6 sam1 ging2 zi6 jin4', mand:'崎岖路，快踏上，让心境自然', d:5.5},
    {han:'風雨來 亦走遠 要留低溫暖', jp:'fung1 jyu5 loi4 jik6 zau2 jyun5 jiu3 lau4 dai1 wan1 nyun5', mand:'风雨来，亦走远，要留低温暖', d:5.5},
    {han:'一生之中尋尋覓覓 夢已遠 留下淡淡地 一片真情留心底', jp:'jat1 sang1 zi1 zung1 cam4 cam4 mik6 mik6 mung6 ji5 jyun5 lau4 haa6 daam6 daam6 dei6 jat1 pin3 zan1 cing4 lau4 sam1 dai2', mand:'一生之中寻寻觅觅，梦已远，留下淡淡地一片真情留心底', d:7.5},
    {han:'願你將愛心傾出 染上我的腳印', jp:'jyun6 nei5 zoeng1 oi3 sam1 king1 ceot1 jim5 soeng6 ngo5 dik1 goek3 jan3', mand:'愿你将爱心倾出，染上我的脚印', d:6.0},
    {han:'願你將真心傾出 愛意盡回贈', jp:'jyun6 nei5 zoeng1 zan1 sam1 king1 ceot1 oi3 ji3 zeon6 wui4 zang6', mand:'愿你将真心倾出，爱意尽回赠', d:5.5},
    {han:'願你共我同行 永遠不分 你我一心', jp:'jyun6 nei5 gung6 ngo5 tung4 haang4 wing5 jyun5 bat1 fan1 nei5 ngo5 jat1 sam1', mand:'愿你共我同行，永远不分，你我一心', d:6.5},
    {han:'願你知 情真 愛意全真 一生一心', jp:'jyun6 nei5 zi1 cing4 zan1 oi3 ji3 cyun4 zan1 jat1 sang1 jat1 sam1', mand:'愿你知，情真，爱意全真，一生一心', d:6.0},
  ],
  notes:[
    {target:'越過 yut6 gwo3', tip:'「越」yut6 是入声 -t 尾，短促；「過」gwo3 圆唇。'},
    {target:'雲煙 wan4 jin1', tip:'「雲」读 wan4 不是 wen，w-a-n 开口音。'},
    {target:'尋尋覓覓 cam4 cam4 mik6 mik6', tip:'「覓」mik6 入声 -k 尾，四字连读练节奏。'},
    {target:'留低 lau4 dai1', tip:'「留低」= 留下，粤语歌高频口语词。'},
    {target:'傾出 king1 ceot1', tip:'「傾」king1（k-i-ng），「出」ceot1 入声 -t 尾。'},
    {target:'腳印 goek3 jan3', tip:'「腳」读 goek3（g-o-e-k），入声 -k 尾，短促。'},
  ],
},
{
  id:'pianpian', title:'偏偏喜歡你', artist:'陳百強', year:1983,
  emoji:'🌸', level:'初级', tags:['经典','情歌'],
  colors:['#c94b4b','#4b134f'],
  intro:'旋律线较长，适合练气息控制、咬字和抒情表达。',
  lyric:[
    {han:'愁緒揮不去苦悶散不去', jp:'sau4 seoi5 fai1 bat1 heoi3 fu2 mun6 saan3 bat1 heoi3', mand:'愁绪挥不去苦闷散不去', d:5.5},
    {han:'為何我心一片空虛', jp:'wai6 ho4 ngo5 sam1 jat1 pin3 hung1 heoi1', mand:'为何我心一片空虚', d:5.0},
    {han:'感情已失去一切都失去', jp:'gam4 cing4 ji5 sat1 heoi3 jat1 cai4 dou1 sat1 heoi3', mand:'感情已失去一切都失去', d:5.5},
    {han:'滿腔恨愁不可消除', jp:'mun5 hong1 han6 sau4 bat1 ho2 siu1 ceoi4', mand:'满腔恨愁不可消除', d:5.0},
    {han:'為何你的嘴裏總是那一句', jp:'wai6 ho4 nei5 dik1 zeoi2 leoi5 zung2 si6 naa5 jat1 geoi3', mand:'为何你的嘴里总是那一句', d:5.5},
    {han:'為何我的心不會死', jp:'wai6 ho4 ngo5 dik1 sam1 bat1 wui5 sei2', mand:'为何我的心不会死', d:4.5},
    {han:'明白到愛失去一切都不對', jp:'ming4 baak6 dou3 oi3 sat1 heoi3 jat1 cai4 dou1 bat1 deoi3', mand:'明白到爱失去一切都不对', d:5.5},
    {han:'我又為何偏偏喜歡你', jp:'ngo5 jau6 wai6 ho4 pin1 pin1 hei2 fun1 nei5', mand:'我又为何偏偏喜欢你', d:5.5},
    {han:'愛已是負累 相愛似受罪', jp:'oi3 ji5 si6 fu6 leoi6 soeng1 oi3 ci5 sau6 zeoi6', mand:'爱已是负累，相爱似受罪', d:5.0},
    {han:'心底如今滿苦淚', jp:'sam1 dai2 jyu4 gam1 mun5 fu2 leoi6', mand:'心底如今满苦泪', d:4.5},
    {han:'舊日情如醉 此際怕再追', jp:'gau6 jat6 cing4 jyu4 zeoi3 ci2 zai3 paa3 zoi3 zeoi1', mand:'旧日情如醉，此际怕再追', d:5.0},
    {han:'偏偏癡心見絕對', jp:'pin1 pin1 ci1 sam1 gin3 zyut6 deoi3', mand:'偏偏痴心见绝对', d:4.5},
    {han:'你為何那麼遠 縱使執著亦無謂', jp:'nei5 wai6 ho4 naa5 mo1 jyun5 zung3 si2 zap1 zoek6 jik6 mou4 wai6', mand:'你为何那么远，纵使执着亦无谓', d:6.0},
    {han:'我仍然相信你 總會等到我', jp:'ngo5 jing4 jin4 soeng1 seon3 nei5 zung2 wui5 dang2 dou3 ngo5', mand:'我仍然相信你，总会等到我', d:5.5},
  ],
  notes:[
    {target:'愁緒 sau4 seoi5', tip:'「緒」读 seoi5，与"水 seoi2"同韵不同调。'},
    {target:'空虛 hung1 heoi1', tip:'「虛」heoi1，注意 eo 圆唇音。'},
    {target:'滿腔 mun5 hong1', tip:'「腔」读 hong1，h-o-ng，别发成 koeng。'},
    {target:'偏偏 pin1 pin1', tip:'两个 p- 送气音，唱出无奈感。'},
    {target:'負累 fu6 leoi6', tip:'「累」读 leoi6，与"淚 leoi6"同音不同字。'},
    {target:'執著 zap1 zoek6', tip:'「執」zap1（-p 尾）、「著」zoek6（-k 尾），两个入声连读。'},
  ],
},
{
  id:'fenfenzhong', title:'分分鐘需要你', artist:'林子祥', year:1980,
  emoji:'🚀', level:'进阶', tags:['经典','轻快'],
  colors:['#11998e','#38ef7d'],
  intro:'节奏轻快跳脱，适合练口语腔调、连续咬字和节拍感。',
  lyric:[
    {han:'願我會揸火箭 帶你到天空去', jp:'jyun6 ngo5 wui5 zaa1 fo2 zin3 daai3 nei5 dou3 tin1 hung1 heoi3', mand:'愿我会揸火箭，带你到天空去', d:5.5},
    {han:'在太空中兩人住', jp:'zoi6 taai3 hung1 zung1 loeng5 jan4 zyu6', mand:'在太空中两人住', d:4.5},
    {han:'活到一千歲 都一般心醉', jp:'wut6 dou3 jat1 cin1 seoi3 dou1 jat1 bun1 sam1 zeoi3', mand:'活到一千岁，都一般心醉', d:5.0},
    {han:'有你在身邊多樂趣', jp:'jau5 nei5 zoi6 san1 bin1 do1 lok6 ceoi3', mand:'有你在身边多乐趣', d:4.5},
    {han:'共你雙雙對 好得戚好得意', jp:'tung4 nei5 soeng1 soeng1 deoi3 hou2 dak1 cik1 hou2 dak1 ji3', mand:'共你双双对，好得戚好得意', d:5.5},
    {han:'地冧天崩當閒事', jp:'dei6 lam3 tin1 bang1 dong3 haan4 si6', mand:'地冧天崩当闲事', d:4.5},
    {han:'就算翻風雨 只需睇到你', jp:'zau6 syun3 faan1 fung1 jyu5 zi2 seoi1 tai2 dou3 nei5', mand:'就算翻风雨，只需睇到你', d:5.5},
    {han:'似見陽光驅散滿天晦氣', jp:'ci5 gin3 joeng4 gwong1 keoi1 saan3 mun5 tin1 fui3 hei3', mand:'似见阳光驱散满天晦气', d:5.5},
    {han:'我哋要永遠在一起', jp:'ngo5 dei6 jiu3 wing5 jyun5 zoi6 jat1 hei2', mand:'我们要永远在一起', d:4.5},
  ],
  notes:[
    {target:'揸火箭 zaa1 fo2 zin3', tip:'「揸」zaa1 = 开/驾驶，最地道的粤语口语动词。'},
    {target:'得戚 dak1 cik1', tip:'「得戚」= 得意洋洋，两个入声字连读（-k 尾）。'},
    {target:'地冧天崩 dei6 lam3 tin1 bang1', tip:'「冧」lam3 = 倒塌，粤语特色动词；「崩」bang1 带 ng 尾。'},
    {target:'晦氣 fui3 hei3', tip:'「晦」读 fui3，f-u-i，别发成 wui。'},
  ],
},
];

/* 歌词常用字词小词典 */
const LYRIC_WORDS = [
  {char:'嘅', jp:'ge3', mand:'的（定语助词）', ex:'我嘅心 = 我的心'},
  {char:'唔', jp:'m4', mand:'不', ex:'唔知 = 不知道'},
  {char:'喺', jp:'hai2', mand:'在（某处）', ex:'喺屋企 = 在家里'},
  {char:'嚟', jp:'lai4', mand:'来', ex:'過嚟 = 过来'},
  {char:'佢', jp:'keoi5', mand:'他/她/它', ex:'佢哋 = 他们'},
  {char:'哋', jp:'dei6', mand:'们（复数）', ex:'我哋 = 我们'},
  {char:'冇', jp:'mou5', mand:'没有', ex:'冇時間 = 没时间'},
  {char:'睇', jp:'tai2', mand:'看', ex:'睇戲 = 看电影'},
  {char:'咗', jp:'zo2', mand:'了（完成体）', ex:'走咗 = 走了'},
  {char:'係', jp:'hai6', mand:'是', ex:'就係你 = 就是你'},
  {char:'攞', jp:'lo2', mand:'拿', ex:'攞走 = 拿走'},
  {char:'喎', jp:'wo3', mand:'语气词（提醒）', ex:'小心啲喎！'},
  {char:'㗎', jp:'gaa3', mand:'语气词（强调/反问）', ex:'好正㗎！'},
  {char:'傾偈', jp:'king1 gai2', mand:'聊天', ex:'傾吓偈 = 聊聊天'},
  {char:'得閒', jp:'dak1 haan4', mand:'有空', ex:'得閒飲茶 = 有空喝早茶'},
];
